// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"fmt"
	"runtime"
	_ "runtime/cgo"
	"strings"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #cgo pkg-config: atspi-2 atk
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeModifierType = coreglib.Type(C.atspi_modifier_type_get_type())
	GTypeCache        = coreglib.Type(C.atspi_cache_get_type())
	GTypeAction       = coreglib.Type(C.atspi_action_get_type())
	GTypeDocument     = coreglib.Type(C.atspi_document_get_type())
	GTypeEditableText = coreglib.Type(C.atspi_editable_text_get_type())
	GTypeImage        = coreglib.Type(C.atspi_image_get_type())
	GTypeTableCell    = coreglib.Type(C.atspi_table_cell_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeModifierType, F: marshalModifierType},
		coreglib.TypeMarshaler{T: GTypeCache, F: marshalCache},
		coreglib.TypeMarshaler{T: GTypeAction, F: marshalAction},
		coreglib.TypeMarshaler{T: GTypeDocument, F: marshalDocument},
		coreglib.TypeMarshaler{T: GTypeEditableText, F: marshalEditableText},
		coreglib.TypeMarshaler{T: GTypeImage, F: marshalImage},
		coreglib.TypeMarshaler{T: GTypeTableCell, F: marshalTableCell},
	})
}

type ModifierType C.gint

const (
	// ModifierShift: left or right 'Shift' key.
	ModifierShift ModifierType = 0
	// ModifierShiftlock: shiftLock or CapsLock key.
	ModifierShiftlock ModifierType = 1
	// ModifierControl: 'Control'/'Ctrl'.
	ModifierControl ModifierType = 2
	// ModifierAlt: alt key (as opposed to AltGr).
	ModifierAlt ModifierType = 3
	// ModifierMeta: depending on the platform, this may map to 'Window',
	// 'Function', 'Meta', 'Menu', or 'NumLock'. Such 'Meta keys' will map to
	// one of META, META2, META3. On X Windows platforms these META values
	// map to the modifier masks Mod1Mask, Mod2Mask, Mod3Mask, e.g. an event
	// having ATSPI_MODIFIER_META2 means that the 'Mod2Mask' bit is set in the
	// corresponding XEvent.
	ModifierMeta ModifierType = 4
	// ModifierMeta2: see ATSPI_MODIFIER_META.
	ModifierMeta2 ModifierType = 5
	// ModifierMeta3: see ATSPI_MODIFIER_META.
	ModifierMeta3 ModifierType = 6
	// ModifierNumlock: symbolic meta key name that is mapped by AT-SPI to the
	// appropriate META value, for the convenience of the client.
	ModifierNumlock ModifierType = 14
)

func marshalModifierType(p uintptr) (interface{}, error) {
	return ModifierType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for ModifierType.
func (m ModifierType) String() string {
	switch m {
	case ModifierShift:
		return "Shift"
	case ModifierShiftlock:
		return "Shiftlock"
	case ModifierControl:
		return "Control"
	case ModifierAlt:
		return "Alt"
	case ModifierMeta:
		return "Meta"
	case ModifierMeta2:
		return "Meta2"
	case ModifierMeta3:
		return "Meta3"
	case ModifierNumlock:
		return "Numlock"
	default:
		return fmt.Sprintf("ModifierType(%d)", m)
	}
}

type Cache C.guint

const (
	CacheNone        Cache = 0b0
	CacheParent      Cache = 0b1
	CacheChildren    Cache = 0b10
	CacheName        Cache = 0b100
	CacheDescription Cache = 0b1000
	CacheStates      Cache = 0b10000
	CacheRole        Cache = 0b100000
	CacheInterfaces  Cache = 0b1000000
	CacheAttributes  Cache = 0b10000000
	CacheAll         Cache = 0b111111111111111111111111111111
	CacheDefault     Cache = 0b1111111
	CacheUndefined   Cache = 0b1000000000000000000000000000000
)

func marshalCache(p uintptr) (interface{}, error) {
	return Cache(coreglib.ValueFromNative(unsafe.Pointer(p)).Flags()), nil
}

// String returns the names in string for Cache.
func (c Cache) String() string {
	if c == 0 {
		return "Cache(0)"
	}

	var builder strings.Builder
	builder.Grow(153)

	for c != 0 {
		next := c & (c - 1)
		bit := c - next

		switch bit {
		case CacheNone:
			builder.WriteString("None|")
		case CacheParent:
			builder.WriteString("Parent|")
		case CacheChildren:
			builder.WriteString("Children|")
		case CacheName:
			builder.WriteString("Name|")
		case CacheDescription:
			builder.WriteString("Description|")
		case CacheStates:
			builder.WriteString("States|")
		case CacheRole:
			builder.WriteString("Role|")
		case CacheInterfaces:
			builder.WriteString("Interfaces|")
		case CacheAttributes:
			builder.WriteString("Attributes|")
		case CacheAll:
			builder.WriteString("All|")
		case CacheDefault:
			builder.WriteString("Default|")
		case CacheUndefined:
			builder.WriteString("Undefined|")
		default:
			builder.WriteString(fmt.Sprintf("Cache(0b%b)|", bit))
		}

		c = next
	}

	return strings.TrimSuffix(builder.String(), "|")
}

// Has returns true if c contains other.
func (c Cache) Has(other Cache) bool {
	return (c & other) == other
}

//
// Action wraps an interface. This means the user can get the
// underlying type by calling Cast().
type Action struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Action)(nil)
)

// Actioner describes Action's interface methods.
type Actioner interface {
	coreglib.Objector

	// DoAction: invoke the action indicated by #index.
	DoAction(i int) error
	// ActionDescription: get the description of 'i-th' action invocable on an
	// object implementing Action.
	ActionDescription(i int) (string, error)
	// KeyBinding: get the keybindings for the i-th action invocable on an
	// object implementing Action, if any are defined.
	KeyBinding(i int) (string, error)
	// LocalizedName: get the name of the 'i-th' action invocable on an object
	// implementing Action.
	LocalizedName(i int) (string, error)
	// NActions: get the number of actions invokable on an Action implementor.
	NActions() (int, error)
	// ActionName: get the name of the 'i-th' action invocable on an object
	// implementing Action.
	ActionName(i int) (string, error)
}

var _ Actioner = (*Action)(nil)

func wrapAction(obj *coreglib.Object) *Action {
	return &Action{
		Object: obj,
	}
}

func marshalAction(p uintptr) (interface{}, error) {
	return wrapAction(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// DoAction: invoke the action indicated by #index.
//
// The function takes the following parameters:
//
//   - i: integer specifying which action to invoke.
func (obj *Action) DoAction(i int) error {
	var _arg0 *C.AtspiAction // out
	var _arg1 C.gint         // out
	var _cerr *C.GError      // in

	_arg0 = (*C.AtspiAction)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(i)

	C.atspi_action_do_action(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(i)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// ActionDescription: get the description of 'i-th' action invocable on an
// object implementing Action.
//
// Deprecated: Use atspi_action_get_action_description instead.
//
// The function takes the following parameters:
//
//   - i: integer indicating which action to query.
//
// The function returns the following values:
//
//   - utf8: UTF-8 string describing the 'i-th' invocable action.
func (obj *Action) ActionDescription(i int) (string, error) {
	var _arg0 *C.AtspiAction // out
	var _arg1 C.gint         // out
	var _cret *C.gchar       // in
	var _cerr *C.GError      // in

	_arg0 = (*C.AtspiAction)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(i)

	_cret = C.atspi_action_get_description(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(i)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// KeyBinding: get the keybindings for the i-th action invocable on an object
// implementing Action, if any are defined. The keybindings string format is as
// follows: there are multiple parts to a keybinding string (typically 3). They
// are delimited with ";". The first is the action's keybinding which is usable
// if the object implementing the action is currently posted to the screen, e.g.
// if a menu is posted then these keybindings for the corresponding menu-items
// are available. The second keybinding substring is the full key sequence
// necessary to post the action's widget and activate it, e.g. for a menu item
// such as "File->Open" it would both post the menu and activate the item.
// Thus the second keybinding string is available during the lifetime of the
// containing toplevel window as a whole, whereas the first keybinding string
// only works while the object implementing AtkAction is posted. The third (and
// optional) keybinding string is the "keyboard shortcut" which invokes the
// action without posting any menus. Meta-keys are indicated by the conventional
// strings "&lt;Control&gt;", "&lt;Alt&gt;", "&lt;Shift&gt;", "&lt;Mod2&gt;",
// etc. (we use the same string as gtk_accelerator_name() in gtk+-2.X.
//
// The function takes the following parameters:
//
//   - i: integer indicating which action to query.
//
// The function returns the following values:
//
//   - utf8: UTF-8 string which can be parsed to determine the i-th invocable
//     action's keybindings.
func (obj *Action) KeyBinding(i int) (string, error) {
	var _arg0 *C.AtspiAction // out
	var _arg1 C.gint         // out
	var _cret *C.gchar       // in
	var _cerr *C.GError      // in

	_arg0 = (*C.AtspiAction)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(i)

	_cret = C.atspi_action_get_key_binding(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(i)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// LocalizedName: get the name of the 'i-th' action invocable on an object
// implementing Action.
//
// The function takes the following parameters:
//
//   - i: integer indicating which action to query.
//
// The function returns the following values:
//
//   - utf8: name of the action, as a UTF-8 string.
func (obj *Action) LocalizedName(i int) (string, error) {
	var _arg0 *C.AtspiAction // out
	var _arg1 C.gint         // out
	var _cret *C.gchar       // in
	var _cerr *C.GError      // in

	_arg0 = (*C.AtspiAction)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(i)

	_cret = C.atspi_action_get_localized_name(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(i)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// NActions: get the number of actions invokable on an Action implementor.
//
// The function returns the following values:
//
//   - gint: integer indicating the number of invocable actions.
func (obj *Action) NActions() (int, error) {
	var _arg0 *C.AtspiAction // out
	var _cret C.gint         // in
	var _cerr *C.GError      // in

	_arg0 = (*C.AtspiAction)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_action_get_n_actions(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// ActionName: get the name of the 'i-th' action invocable on an object
// implementing Action.
//
// Deprecated: Use atspi_action_get_action_name instead.
//
// The function takes the following parameters:
//
//   - i: integer indicating which action to query.
//
// The function returns the following values:
//
//   - utf8: non-localized name of the action, as a UTF-8 string.
func (obj *Action) ActionName(i int) (string, error) {
	var _arg0 *C.AtspiAction // out
	var _arg1 C.gint         // out
	var _cret *C.gchar       // in
	var _cerr *C.GError      // in

	_arg0 = (*C.AtspiAction)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(i)

	_cret = C.atspi_action_get_name(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(i)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

//
// Document wraps an interface. This means the user can get the
// underlying type by calling Cast().
type Document struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Document)(nil)
)

// Documenter describes Document's interface methods.
type Documenter interface {
	coreglib.Objector

	// DocumentAttributeValue gets the value of a single attribute, if specified
	// for the document as a whole.
	DocumentAttributeValue(attribute string) (string, error)
	// DocumentAttributes gets all constant attributes for the document as a
	// whole.
	DocumentAttributes() (map[string]string, error)
	// CurrentPageNumber gets the current page number of an Document object.
	CurrentPageNumber() (int, error)
	// Locale gets the locale associated with the document's content, e.g.
	Locale() (string, error)
	// PageCount gets the page count of an Document object.
	PageCount() (int, error)
	// TextSelections returns an array of AtspiTextSelections within this
	// document.
	TextSelections() ([]TextSelection, error)
	// SetTextSelections makes 1 or more selections within this document denoted
	// by the given array of AtspiTextSelections.
	SetTextSelections(selections []TextSelection) error
}

var _ Documenter = (*Document)(nil)

func wrapDocument(obj *coreglib.Object) *Document {
	return &Document{
		Object: obj,
	}
}

func marshalDocument(p uintptr) (interface{}, error) {
	return wrapDocument(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// DocumentAttributeValue gets the value of a single attribute, if specified for
// the document as a whole.
//
// Deprecated: Use atspi_document_get_document_attribute_value instead.
//
// The function takes the following parameters:
//
//   - attribute: string indicating the name of a specific attribute.
//
// The function returns the following values:
//
//   - utf8: string corresponding to the value of the specified attribute,
//     or an empty string if the attribute is unspecified for the object.
func (obj *Document) DocumentAttributeValue(attribute string) (string, error) {
	var _arg0 *C.AtspiDocument // out
	var _arg1 *C.gchar         // out
	var _cret *C.gchar         // in
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiDocument)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(attribute)))
	defer C.free(unsafe.Pointer(_arg1))

	_cret = C.atspi_document_get_attribute_value(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(attribute)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// DocumentAttributes gets all constant attributes for the document as
// a whole. For attributes that change within the document content, see
// atspi_text_get_attribute_run instead.
//
// Deprecated: Use atspi_document_get_document_attributes instead.
//
// The function returns the following values:
//
//   - hashTable: Table containing the constant attributes of the document,
//     as name-value pairs.
func (obj *Document) DocumentAttributes() (map[string]string, error) {
	var _arg0 *C.AtspiDocument // out
	var _cret *C.GHashTable    // in
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiDocument)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_document_get_attributes(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _hashTable map[string]string // out
	var _goerr error                 // out

	_hashTable = make(map[string]string, gextras.HashTableSize(unsafe.Pointer(_cret)))
	gextras.MoveHashTable(unsafe.Pointer(_cret), true, func(k, v unsafe.Pointer) {
		ksrc := *(**C.gchar)(k)
		vsrc := *(**C.gchar)(v)
		var kdst string // out
		var vdst string // out
		kdst = C.GoString((*C.gchar)(unsafe.Pointer(ksrc)))
		defer C.free(unsafe.Pointer(ksrc))
		vdst = C.GoString((*C.gchar)(unsafe.Pointer(vsrc)))
		defer C.free(unsafe.Pointer(vsrc))
		_hashTable[kdst] = vdst
	})
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _hashTable, _goerr
}

// CurrentPageNumber gets the current page number of an Document object.
//
// The function returns the following values:
//
//   - gint indicating the current page number in the Document object.
func (obj *Document) CurrentPageNumber() (int, error) {
	var _arg0 *C.AtspiDocument // out
	var _cret C.gint           // in
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiDocument)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_document_get_current_page_number(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// Locale gets the locale associated with the document's content, e.g. the
// locale for LOCALE_TYPE_MESSAGES.
//
// The function returns the following values:
//
//   - utf8: string compliant with the POSIX standard for locale description.
func (obj *Document) Locale() (string, error) {
	var _arg0 *C.AtspiDocument // out
	var _cret *C.gchar         // in
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiDocument)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_document_get_locale(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// PageCount gets the page count of an Document object.
//
// The function returns the following values:
//
//   - gint indicating the page count of an Document object.
func (obj *Document) PageCount() (int, error) {
	var _arg0 *C.AtspiDocument // out
	var _cret C.gint           // in
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiDocument)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_document_get_page_count(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// TextSelections returns an array of AtspiTextSelections within this document.
//
// The function returns the following values:
//
//   - textSelections: GArray of AtspiTextSelection structures representing the
//     selection.
func (document *Document) TextSelections() ([]TextSelection, error) {
	var _arg0 *C.AtspiDocument // out
	var _cret *C.GArray        // in
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiDocument)(unsafe.Pointer(coreglib.InternObject(document).Native()))

	_cret = C.atspi_document_get_text_selections(_arg0, &_cerr)
	runtime.KeepAlive(document)

	var _textSelections []TextSelection // out
	var _goerr error                    // out

	{
		var len uintptr
		p := C.g_array_steal(&_cret, (*C.gsize)(&len))
		src := unsafe.Slice((*C.GArray)(p), len)
		_textSelections = make([]TextSelection, len)
		for i := 0; i < len; i++ {
			_textSelections[i] = *(*TextSelection)(gextras.NewStructNative(unsafe.Pointer((&src[i]))))
			runtime.SetFinalizer(
				gextras.StructIntern(unsafe.Pointer(&_textSelections[i])),
				func(intern *struct{ C unsafe.Pointer }) {
					C.free(intern.C)
				},
			)
		}
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _textSelections, _goerr
}

// SetTextSelections makes 1 or more selections within this document denoted
// by the given array of AtspiTextSelections. Any existing physical selection
// (inside or outside this document) is replaced by the new selections.
// All objects within the given selection ranges must be descendants of this
// document. Otherwise FALSE will be returned.
//
// The function takes the following parameters:
//
//   - selections: GArray of AtspiTextSelections to be selected.
func (document *Document) SetTextSelections(selections []TextSelection) error {
	var _arg0 *C.AtspiDocument // out
	var _arg1 *C.GArray        // out
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiDocument)(unsafe.Pointer(coreglib.InternObject(document).Native()))
	_arg1 = C.g_array_sized_new(false, false, C.guint(C.sizeof_GArray), C.guint(len(selections)))
	_arg1 = C.g_array_set_size(_arg1, C.guint(len(selections)))
	defer C.g_array_unref(_arg1)
	{
		out := unsafe.Slice(_arg1.data, len(selections))
		for i := range selections {
			out[i] = *(*C.GArray)(gextras.StructNative(unsafe.Pointer((&selections[i]))))
		}
	}

	C.atspi_document_set_text_selections(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(document)
	runtime.KeepAlive(selections)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

//
// EditableText wraps an interface. This means the user can get the
// underlying type by calling Cast().
type EditableText struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*EditableText)(nil)
)

// EditableTexter describes EditableText's interface methods.
type EditableTexter interface {
	coreglib.Objector

	// CopyText copies text from an EditableText object into the system
	// clipboard.
	CopyText(startPos, endPos int) error
	// CutText deletes text from an EditableText object, copying the excised
	// portion into the system clipboard.
	CutText(startPos, endPos int) error
	// DeleteText deletes text from an EditableText object, without copying the
	// excised portion into the system clipboard.
	DeleteText(startPos, endPos int) error
	// InsertText inserts text into an EditableText object.
	InsertText(position int, text string) error
	// PasteText inserts text from the system clipboard into an EditableText
	// object.
	PasteText(position int) error
	// SetTextContents: replace the entire text contents of an EditableText
	// object.
	SetTextContents(newContents string) error
}

var _ EditableTexter = (*EditableText)(nil)

func wrapEditableText(obj *coreglib.Object) *EditableText {
	return &EditableText{
		Object: obj,
	}
}

func marshalEditableText(p uintptr) (interface{}, error) {
	return wrapEditableText(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// CopyText copies text from an EditableText object into the system clipboard.
//
// see: #atspi_editable_text_paste_text.
//
// The function takes the following parameters:
//
//   - startPos indicating the starting character offset of the text to copy.
//   - endPos indicating the offset of the first character past the end of the
//     text section to be copied.
func (obj *EditableText) CopyText(startPos, endPos int) error {
	var _arg0 *C.AtspiEditableText // out
	var _arg1 C.gint               // out
	var _arg2 C.gint               // out
	var _cerr *C.GError            // in

	_arg0 = (*C.AtspiEditableText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(startPos)
	_arg2 = C.gint(endPos)

	C.atspi_editable_text_copy_text(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(startPos)
	runtime.KeepAlive(endPos)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// CutText deletes text from an EditableText object, copying the excised portion
// into the system clipboard.
//
// see: #atspi_editable_text_paste_text.
//
// The function takes the following parameters:
//
//   - startPos indicating the starting character offset of the text to cut.
//   - endPos indicating the offset of the first character past the end of the
//     text section to be cut.
func (obj *EditableText) CutText(startPos, endPos int) error {
	var _arg0 *C.AtspiEditableText // out
	var _arg1 C.gint               // out
	var _arg2 C.gint               // out
	var _cerr *C.GError            // in

	_arg0 = (*C.AtspiEditableText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(startPos)
	_arg2 = C.gint(endPos)

	C.atspi_editable_text_cut_text(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(startPos)
	runtime.KeepAlive(endPos)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// DeleteText deletes text from an EditableText object, without copying the
// excised portion into the system clipboard.
//
// see: #atspi_editable_text_cut_text.
//
// The function takes the following parameters:
//
//   - startPos indicating the starting character offset of the text to delete.
//   - endPos indicating the offset of the first character past the end of the
//     text section to be deleted.
func (obj *EditableText) DeleteText(startPos, endPos int) error {
	var _arg0 *C.AtspiEditableText // out
	var _arg1 C.gint               // out
	var _arg2 C.gint               // out
	var _cerr *C.GError            // in

	_arg0 = (*C.AtspiEditableText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(startPos)
	_arg2 = C.gint(endPos)

	C.atspi_editable_text_delete_text(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(startPos)
	runtime.KeepAlive(endPos)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// InsertText inserts text into an EditableText object. As with all character
// offsets, the specified position may not be the same as the resulting byte
// offset, since the text is in a variable-width encoding.
//
// The function takes the following parameters:
//
//   - position indicating the character offset at which to insert the new text.
//   - text: string representing the text to insert, in UTF-8 encoding.
func (obj *EditableText) InsertText(position int, text string) error {
	var _arg0 *C.AtspiEditableText // out
	var _arg1 C.gint               // out
	var _arg2 *C.gchar             // out
	var _arg3 C.gint
	var _cerr *C.GError // in

	_arg0 = (*C.AtspiEditableText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(position)
	_arg3 = (C.gint)(len(text))
	_arg2 = (*C.gchar)(C.calloc(C.size_t((len(text) + 1)), C.size_t(C.sizeof_gchar)))
	copy(unsafe.Slice((*byte)(unsafe.Pointer(_arg2)), len(text)), text)
	defer C.free(unsafe.Pointer(_arg2))

	C.atspi_editable_text_insert_text(_arg0, _arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(position)
	runtime.KeepAlive(text)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// PasteText inserts text from the system clipboard into an EditableText object.
// As with all character offsets, the specified position may not be the same as
// the resulting byte offset, since the text is in a variable-width encoding.
//
// The function takes the following parameters:
//
//   - position indicating the character offset at which to insert the new text.
func (obj *EditableText) PasteText(position int) error {
	var _arg0 *C.AtspiEditableText // out
	var _arg1 C.gint               // out
	var _cerr *C.GError            // in

	_arg0 = (*C.AtspiEditableText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(position)

	C.atspi_editable_text_paste_text(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(position)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// SetTextContents: replace the entire text contents of an EditableText object.
//
// The function takes the following parameters:
//
//   - newContents: character string, encoded in UTF-8, which is to become the
//     new text contents of the EditableText object.
func (obj *EditableText) SetTextContents(newContents string) error {
	var _arg0 *C.AtspiEditableText // out
	var _arg1 *C.gchar             // out
	var _cerr *C.GError            // in

	_arg0 = (*C.AtspiEditableText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(newContents)))
	defer C.free(unsafe.Pointer(_arg1))

	C.atspi_editable_text_set_text_contents(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(newContents)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

//
// Image wraps an interface. This means the user can get the
// underlying type by calling Cast().
type Image struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Image)(nil)
)

// Imager describes Image's interface methods.
type Imager interface {
	coreglib.Objector

	// ImageDescription gets the description of the image displayed in an Image
	// object.
	ImageDescription() (string, error)
	// ImageExtents gets the bounding box of the image displayed in a specified
	// Image implementor.
	ImageExtents(ctype CoordType) (*Rect, error)
	// ImageLocale gets the locale associated with an image and its textual
	// representation.
	ImageLocale() (string, error)
	// ImagePosition gets the minimum x and y coordinates of the image displayed
	// in a specified Image implementor.
	ImagePosition(ctype CoordType) (*Point, error)
	// ImageSize gets the size of the image displayed in a specified Image
	// object.
	ImageSize() (*Point, error)
}

var _ Imager = (*Image)(nil)

func wrapImage(obj *coreglib.Object) *Image {
	return &Image{
		Object: obj,
	}
}

func marshalImage(p uintptr) (interface{}, error) {
	return wrapImage(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// ImageDescription gets the description of the image displayed in an Image
// object.
//
// The function returns the following values:
//
//   - utf8: UTF-8 string describing the image.
func (obj *Image) ImageDescription() (string, error) {
	var _arg0 *C.AtspiImage // out
	var _cret *C.gchar      // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiImage)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_image_get_image_description(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// ImageExtents gets the bounding box of the image displayed in a specified
// Image implementor. The returned values are meaningful only if the Image has
// both STATE_VISIBLE and STATE_SHOWING.
//
// The function takes the following parameters:
//
//   - ctype: desired coordinate system into which to return the results, (e.g.
//     ATSPI_COORD_TYPE_WINDOW, ATSPI_COORD_TYPE_SCREEN).
//
// The function returns the following values:
//
//   - rect: pointer to an Rect corresponding to the image's bounding box.
//     The minimum x and y coordinates, width, and height are specified.
func (obj *Image) ImageExtents(ctype CoordType) (*Rect, error) {
	var _arg0 *C.AtspiImage    // out
	var _arg1 C.AtspiCoordType // out
	var _cret *C.AtspiRect     // in
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiImage)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.AtspiCoordType(ctype)

	_cret = C.atspi_image_get_image_extents(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(ctype)

	var _rect *Rect  // out
	var _goerr error // out

	_rect = (*Rect)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_rect)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _rect, _goerr
}

// ImageLocale gets the locale associated with an image and its textual
// representation.
//
// The function returns the following values:
//
//   - utf8: POSIX LC_MESSAGES-style locale value for image description and
//     text.
func (obj *Image) ImageLocale() (string, error) {
	var _arg0 *C.AtspiImage // out
	var _cret *C.gchar      // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiImage)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_image_get_image_locale(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// ImagePosition gets the minimum x and y coordinates of the image displayed in
// a specified Image implementor. The returned values are meaningful only if the
// Image has both STATE_VISIBLE and STATE_SHOWING.
//
// The function takes the following parameters:
//
//   - ctype: desired coordinate system into which to return the results, (e.g.
//     ATSPI_COORD_TYPE_WINDOW, ATSPI_COORD_TYPE_SCREEN).
//
// The function returns the following values:
//
//   - point: pointer to an Point where x and y correspond to the minimum
//     coordinates of the displayed image.
func (obj *Image) ImagePosition(ctype CoordType) (*Point, error) {
	var _arg0 *C.AtspiImage    // out
	var _arg1 C.AtspiCoordType // out
	var _cret *C.AtspiPoint    // in
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiImage)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.AtspiCoordType(ctype)

	_cret = C.atspi_image_get_image_position(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(ctype)

	var _point *Point // out
	var _goerr error  // out

	_point = (*Point)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_point)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _point, _goerr
}

// ImageSize gets the size of the image displayed in a specified Image object.
// The returned values are meaningful only if the Image has both STATE_VISIBLE
// and STATE_SHOWING.
//
// The function returns the following values:
//
//   - point: pointer to an Point where x corresponds to the image's width and y
//     corresponds to the image's height.
func (obj *Image) ImageSize() (*Point, error) {
	var _arg0 *C.AtspiImage // out
	var _cret *C.AtspiPoint // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiImage)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_image_get_image_size(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _point *Point // out
	var _goerr error  // out

	_point = (*Point)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_point)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _point, _goerr
}

//
// TableCell wraps an interface. This means the user can get the
// underlying type by calling Cast().
type TableCell struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*TableCell)(nil)
)

// TableCeller describes TableCell's interface methods.
type TableCeller interface {
	coreglib.Objector

	ColumnIndex() (int, error)
	// ColumnSpan returns the number of columns occupied by this cell
	// accessible.
	ColumnSpan() (int, error)
	// Position retrieves the tabular position of this cell.
	Position() (row, column, gint int, goerr error)
	// RowColumnSpan gets the row and column indexes and extents of this cell
	// accessible.
	RowColumnSpan() (row, column, rowSpan, columnSpan int, goerr error)
	// RowSpan returns the number of rows occupied by this cell accessible.
	RowSpan() (int, error)
	// Table returns a reference to the accessible of the containing table.
	Table() (*Accessible, error)
}

var _ TableCeller = (*TableCell)(nil)

func wrapTableCell(obj *coreglib.Object) *TableCell {
	return &TableCell{
		Object: obj,
	}
}

func marshalTableCell(p uintptr) (interface{}, error) {
	return wrapTableCell(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

func (obj *TableCell) ColumnIndex() (int, error) {
	var _arg0 *C.AtspiTableCell // out
	var _cret C.gint            // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiTableCell)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_cell_get_column_index(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// ColumnSpan returns the number of columns occupied by this cell accessible.
// The returned values are meaningful only if the table cell has both
// STATE_VISIBLE and STATE_SHOWING.
//
// The function returns the following values:
//
//   - gint representing the number of columns occupied by this cell, or 0 if
//     the cell does not implement this method.
func (obj *TableCell) ColumnSpan() (int, error) {
	var _arg0 *C.AtspiTableCell // out
	var _cret C.gint            // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiTableCell)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_cell_get_column_span(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// Position retrieves the tabular position of this cell.
//
// The function returns the following values:
//
//   - row of the given cell.
//   - column of the given cell.
//   - gint: TRUE if successful, FALSE otherwise.
func (obj *TableCell) Position() (row, column, gint int, goerr error) {
	var _arg0 *C.AtspiTableCell // out
	var _arg1 C.gint            // in
	var _arg2 C.gint            // in
	var _cret C.gint            // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiTableCell)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_cell_get_position(_arg0, &_arg1, &_arg2, &_cerr)
	runtime.KeepAlive(obj)

	var _row int     // out
	var _column int  // out
	var _gint int    // out
	var _goerr error // out

	_row = int(_arg1)
	_column = int(_arg2)
	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _row, _column, _gint, _goerr
}

// RowColumnSpan gets the row and column indexes and extents of this cell
// accessible. The returned values are meaningful only if the table cell has
// both STATE_VISIBLE and STATE_SHOWING.
//
// The function returns the following values:
//
//   - row index of the given cell.
//   - column index of the given cell.
//   - rowSpan: number of rows occupied by this cell.
//   - columnSpan: number of columns occupied by this cell.
func (obj *TableCell) RowColumnSpan() (row, column, rowSpan, columnSpan int, goerr error) {
	var _arg0 *C.AtspiTableCell // out
	var _arg1 C.gint            // in
	var _arg2 C.gint            // in
	var _arg3 C.gint            // in
	var _arg4 C.gint            // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiTableCell)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	C.atspi_table_cell_get_row_column_span(_arg0, &_arg1, &_arg2, &_arg3, &_arg4, &_cerr)
	runtime.KeepAlive(obj)

	var _row int        // out
	var _column int     // out
	var _rowSpan int    // out
	var _columnSpan int // out
	var _goerr error    // out

	_row = int(_arg1)
	_column = int(_arg2)
	_rowSpan = int(_arg3)
	_columnSpan = int(_arg4)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _row, _column, _rowSpan, _columnSpan, _goerr
}

// RowSpan returns the number of rows occupied by this cell accessible. The
// returned values are meaningful only if the table cell has both STATE_VISIBLE
// and STATE_SHOWING.
//
// The function returns the following values:
//
//   - gint representing the number of rows occupied by this cell, or 0 if the
//     cell does not implement this method.
func (obj *TableCell) RowSpan() (int, error) {
	var _arg0 *C.AtspiTableCell // out
	var _cret C.gint            // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiTableCell)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_cell_get_row_span(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// Table returns a reference to the accessible of the containing table.
//
// The function returns the following values:
//
//   - accessible: atspiAccessible for the containing table.
func (obj *TableCell) Table() (*Accessible, error) {
	var _arg0 *C.AtspiTableCell  // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiTableCell)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_cell_get_table(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _accessible *Accessible // out
	var _goerr error            // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}
