// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeStateSet = coreglib.Type(C.atspi_state_set_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeStateSet, F: marshalStateSet},
	})
}

// StateSetOverrides contains methods that are overridable.
type StateSetOverrides struct {
}

func defaultStateSetOverrides(v *StateSet) StateSetOverrides {
	return StateSetOverrides{}
}

// StateSet: atspi-stateset objects implement wrappers around a bitmap of
// accessible states.
type StateSet struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*StateSet)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*StateSet, *StateSetClass, StateSetOverrides](
		GTypeStateSet,
		initStateSetClass,
		wrapStateSet,
		defaultStateSetOverrides,
	)
}

func initStateSetClass(gclass unsafe.Pointer, overrides StateSetOverrides, classInitFunc func(*StateSetClass)) {
	if classInitFunc != nil {
		class := (*StateSetClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapStateSet(obj *coreglib.Object) *StateSet {
	return &StateSet{
		Object: obj,
	}
}

func marshalStateSet(p uintptr) (interface{}, error) {
	return wrapStateSet(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewStateSet generates an StateSet with the given states.
//
// The function takes the following parameters:
//
//   - states: array of states with which the method initializes the state set.
//
// The function returns the following values:
//
//   - stateSet: new StateSet with the given states.
func NewStateSet(states []StateType) *StateSet {
	var _arg1 *C.GArray        // out
	var _cret *C.AtspiStateSet // in

	_arg1 = C.g_array_sized_new(false, false, C.guint(C.sizeof_GArray), C.guint(len(states)))
	_arg1 = C.g_array_set_size(_arg1, C.guint(len(states)))
	defer C.g_array_unref(_arg1)
	{
		out := unsafe.Slice(_arg1.data, len(states))
		for i := range states {
			out[i] = C.GArray(states[i])
		}
	}

	_cret = C.atspi_state_set_new(_arg1)
	runtime.KeepAlive(states)

	var _stateSet *StateSet // out

	_stateSet = wrapStateSet(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _stateSet
}

// Add adds a particular State to an StateSet (i.e. sets the given state to UE
// in the stateset).
//
// The function takes the following parameters:
//
//   - state to be added to the specified StateSet.
func (set *StateSet) Add(state StateType) {
	var _arg0 *C.AtspiStateSet // out
	var _arg1 C.AtspiStateType // out

	_arg0 = (*C.AtspiStateSet)(unsafe.Pointer(coreglib.InternObject(set).Native()))
	_arg1 = C.AtspiStateType(state)

	C.atspi_state_set_add(_arg0, _arg1)
	runtime.KeepAlive(set)
	runtime.KeepAlive(state)
}

// Compare determines the differences between two instances of StateSet.
//
// see #atspi_state_set_equals.
//
// The function takes the following parameters:
//
//   - set2: pointer to the second StateSet object on which to operate.
//
// The function returns the following values:
//
//   - stateSet object containing all states contained on one of the two sets
//     but not the other.
func (set *StateSet) Compare(set2 *StateSet) *StateSet {
	var _arg0 *C.AtspiStateSet // out
	var _arg1 *C.AtspiStateSet // out
	var _cret *C.AtspiStateSet // in

	_arg0 = (*C.AtspiStateSet)(unsafe.Pointer(coreglib.InternObject(set).Native()))
	_arg1 = (*C.AtspiStateSet)(unsafe.Pointer(coreglib.InternObject(set2).Native()))

	_cret = C.atspi_state_set_compare(_arg0, _arg1)
	runtime.KeepAlive(set)
	runtime.KeepAlive(set2)

	var _stateSet *StateSet // out

	_stateSet = wrapStateSet(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _stateSet
}

// Contains determines whether a given StateSet includes a given state; that is,
// whether state is true for the set in question.
//
// The function takes the following parameters:
//
//   - state for which the specified StateSet will be queried.
//
// The function returns the following values:
//
//   - ok if state is true/included in the given StateSet, otherwise LSE.
func (set *StateSet) Contains(state StateType) bool {
	var _arg0 *C.AtspiStateSet // out
	var _arg1 C.AtspiStateType // out
	var _cret C.gboolean       // in

	_arg0 = (*C.AtspiStateSet)(unsafe.Pointer(coreglib.InternObject(set).Native()))
	_arg1 = C.AtspiStateType(state)

	_cret = C.atspi_state_set_contains(_arg0, _arg1)
	runtime.KeepAlive(set)
	runtime.KeepAlive(state)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Equals determines whether two instances of StateSet are equivalent (i.e.
// consist of the same States). Useful for checking multiple state variables at
// once.
//
// see #atspi_state_set_compare.
//
// The function takes the following parameters:
//
//   - set2: pointer to the second StateSet object on which to operate.
//
// The function returns the following values:
//
//   - ok if the two StateSets are equivalent, otherwise LSE.
func (set *StateSet) Equals(set2 *StateSet) bool {
	var _arg0 *C.AtspiStateSet // out
	var _arg1 *C.AtspiStateSet // out
	var _cret C.gboolean       // in

	_arg0 = (*C.AtspiStateSet)(unsafe.Pointer(coreglib.InternObject(set).Native()))
	_arg1 = (*C.AtspiStateSet)(unsafe.Pointer(coreglib.InternObject(set2).Native()))

	_cret = C.atspi_state_set_equals(_arg0, _arg1)
	runtime.KeepAlive(set)
	runtime.KeepAlive(set2)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// States returns the states in an StateSet as an array.
//
// The function returns the following values:
//
//   - stateTypes of state types representing the current state.
func (set *StateSet) States() []StateType {
	var _arg0 *C.AtspiStateSet // out
	var _cret *C.GArray        // in

	_arg0 = (*C.AtspiStateSet)(unsafe.Pointer(coreglib.InternObject(set).Native()))

	_cret = C.atspi_state_set_get_states(_arg0)
	runtime.KeepAlive(set)

	var _stateTypes []StateType // out

	{
		var len uintptr
		p := C.g_array_steal(&_cret, (*C.gsize)(&len))
		src := unsafe.Slice((*C.GArray)(p), len)
		_stateTypes = make([]StateType, len)
		for i := 0; i < len; i++ {
			_stateTypes[i] = StateType(src[i])
		}
	}

	return _stateTypes
}

// The function returns the following values:
//
//   - ok if the state set contains no states; LSE otherwise.
func (set *StateSet) IsEmpty() bool {
	var _arg0 *C.AtspiStateSet // out
	var _cret C.gboolean       // in

	_arg0 = (*C.AtspiStateSet)(unsafe.Pointer(coreglib.InternObject(set).Native()))

	_cret = C.atspi_state_set_is_empty(_arg0)
	runtime.KeepAlive(set)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Remove removes a particular State to an StateSet (i.e. sets the given state
// to LSE in the stateset.).
//
// The function takes the following parameters:
//
//   - state to remove from the specified set.
func (set *StateSet) Remove(state StateType) {
	var _arg0 *C.AtspiStateSet // out
	var _arg1 C.AtspiStateType // out

	_arg0 = (*C.AtspiStateSet)(unsafe.Pointer(coreglib.InternObject(set).Native()))
	_arg1 = C.AtspiStateType(state)

	C.atspi_state_set_remove(_arg0, _arg1)
	runtime.KeepAlive(set)
	runtime.KeepAlive(state)
}

// SetByName enables/disables a state in an StateSet according to its name.
//
// The function takes the following parameters:
//
//   - name: string corresponding to a state name.
//   - enabled: if UE, name should be enabled in the set in question; otherwise,
//     it should be disabled.
func (set *StateSet) SetByName(name string, enabled bool) {
	var _arg0 *C.AtspiStateSet // out
	var _arg1 *C.gchar         // out
	var _arg2 C.gboolean       // out

	_arg0 = (*C.AtspiStateSet)(unsafe.Pointer(coreglib.InternObject(set).Native()))
	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(name)))
	defer C.free(unsafe.Pointer(_arg1))
	if enabled {
		_arg2 = C.TRUE
	}

	C.atspi_state_set_set_by_name(_arg0, _arg1, _arg2)
	runtime.KeepAlive(set)
	runtime.KeepAlive(name)
	runtime.KeepAlive(enabled)
}

// StateSetClass: instance of this type is always passed by reference.
type StateSetClass struct {
	*stateSetClass
}

// stateSetClass is the struct that's finalized.
type stateSetClass struct {
	native *C.AtspiStateSetClass
}
