// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
// extern gboolean _gotk4_atspi2_DeviceListenerClass_device_event(AtspiDeviceListener*, AtspiDeviceEvent*);
// gboolean _gotk4_atspi2_DeviceListener_virtual_device_event(void* fnptr, AtspiDeviceListener* arg0, AtspiDeviceEvent* arg1) {
//   return ((gboolean (*)(AtspiDeviceListener*, AtspiDeviceEvent*))(fnptr))(arg0, arg1);
// };
import "C"

// GType values.
var (
	GTypeDeviceListener = coreglib.Type(C.atspi_device_listener_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeDeviceListener, F: marshalDeviceListener},
	})
}

// DeviceListenerCB: callback function prototype via which clients receive
// device event notifications.
type DeviceListenerCB func(stroke *DeviceEvent) (ok bool)

// DeviceListenerOverrides contains methods that are overridable.
type DeviceListenerOverrides struct {
	DeviceEvent func(event *DeviceEvent) bool
}

func defaultDeviceListenerOverrides(v *DeviceListener) DeviceListenerOverrides {
	return DeviceListenerOverrides{
		DeviceEvent: v.deviceEvent,
	}
}

type DeviceListener struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*DeviceListener)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*DeviceListener, *DeviceListenerClass, DeviceListenerOverrides](
		GTypeDeviceListener,
		initDeviceListenerClass,
		wrapDeviceListener,
		defaultDeviceListenerOverrides,
	)
}

func initDeviceListenerClass(gclass unsafe.Pointer, overrides DeviceListenerOverrides, classInitFunc func(*DeviceListenerClass)) {
	pclass := (*C.AtspiDeviceListenerClass)(unsafe.Pointer(C.g_type_check_class_cast((*C.GTypeClass)(gclass), C.GType(GTypeDeviceListener))))

	if overrides.DeviceEvent != nil {
		pclass.device_event = (*[0]byte)(C._gotk4_atspi2_DeviceListenerClass_device_event)
	}

	if classInitFunc != nil {
		class := (*DeviceListenerClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapDeviceListener(obj *coreglib.Object) *DeviceListener {
	return &DeviceListener{
		Object: obj,
	}
}

func marshalDeviceListener(p uintptr) (interface{}, error) {
	return wrapDeviceListener(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

func (listener *DeviceListener) deviceEvent(event *DeviceEvent) bool {
	gclass := (*C.AtspiDeviceListenerClass)(coreglib.PeekParentClass(listener))
	fnarg := gclass.device_event

	var _arg0 *C.AtspiDeviceListener // out
	var _arg1 *C.AtspiDeviceEvent    // out
	var _cret C.gboolean             // in

	_arg0 = (*C.AtspiDeviceListener)(unsafe.Pointer(coreglib.InternObject(listener).Native()))
	_arg1 = (*C.AtspiDeviceEvent)(gextras.StructNative(unsafe.Pointer(event)))

	_cret = C._gotk4_atspi2_DeviceListener_virtual_device_event(unsafe.Pointer(fnarg), _arg0, _arg1)
	runtime.KeepAlive(listener)
	runtime.KeepAlive(event)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// DeviceListenerClass: instance of this type is always passed by reference.
type DeviceListenerClass struct {
	*deviceListenerClass
}

// deviceListenerClass is the struct that's finalized.
type deviceListenerClass struct {
	native *C.AtspiDeviceListenerClass
}
