// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
import "C"

//export _gotk4_atspi2_KeyCallback
func _gotk4_atspi2_KeyCallback(arg1 *C.AtspiDevice, arg2 C.gboolean, arg3 C.guint, arg4 C.guint, arg5 C.guint, arg6 *C.gchar, arg7 *C.void) {
	var fn KeyCallback
	{
		v := gbox.Get(uintptr(arg7))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(KeyCallback)
	}

	var _device *Device   // out
	var _pressed bool     // out
	var _keycode uint     // out
	var _keysym uint      // out
	var _modifiers uint   // out
	var _keystring string // out

	_device = wrapDevice(coreglib.Take(unsafe.Pointer(arg1)))
	if arg2 != 0 {
		_pressed = true
	}
	_keycode = uint(arg3)
	_keysym = uint(arg4)
	_modifiers = uint(arg5)
	_keystring = C.GoString((*C.gchar)(unsafe.Pointer(arg6)))

	fn(_device, _pressed, _keycode, _keysym, _modifiers, _keystring)
}
