// Code generated by girgen. DO NOT EDIT.

package atspi

// #include <stdlib.h>
// #include <atspi/atspi.h>
import "C"

// GetVersion returns the version of the AT-SPI library being used at runtime.
//
// The function returns the following values:
//
//   - major version.
//   - minor version.
//   - micro: micro/patch version.
func GetVersion() (major, minor, micro int) {
	var _arg1 C.gint // in
	var _arg2 C.gint // in
	var _arg3 C.gint // in

	C.atspi_get_version(&_arg1, &_arg2, &_arg3)

	var _major int // out
	var _minor int // out
	var _micro int // out

	_major = int(_arg1)
	_minor = int(_arg2)
	_micro = int(_arg3)

	return _major, _minor, _micro
}
