// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"github.com/diamondburned/gotk4/pkg/core/gbox"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
import "C"

//export _gotk4_atspi2_GenerateMouseEventCB
func _gotk4_atspi2_GenerateMouseEventCB(arg1 *C.void) {
	var fn GenerateMouseEventCB
	{
		v := gbox.Get(uintptr(arg1))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(GenerateMouseEventCB)
	}

	fn()
}
