// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeComponent = coreglib.Type(C.atspi_component_get_type())
	GTypePoint     = coreglib.Type(C.atspi_point_get_type())
	GTypeRect      = coreglib.Type(C.atspi_rect_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeComponent, F: marshalComponent},
		coreglib.TypeMarshaler{T: GTypePoint, F: marshalPoint},
		coreglib.TypeMarshaler{T: GTypeRect, F: marshalRect},
	})
}

// Component: interface implemented by objects which have onscreen visual
// representations.
//
// The Component interface is implemented by objects which occupy on-screen
// space, e.g. objects which have onscreen visual representations. The methods
// in Component allow clients to identify where the objects lie in the onscreen
// coordinate system, their relative size, stacking order, and position. It also
// provides a mechanism whereby keyboard focus may be transferred to specific
// user interface elements programmatically. This is a 2D API. Coordinates of 3D
// objects are projected into the 2-dimensional screen view for purposes of this
// interface.
//
// Component wraps an interface. This means the user can get the
// underlying type by calling Cast().
type Component struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Component)(nil)
)

// Componenter describes Component's interface methods.
type Componenter interface {
	coreglib.Objector

	// Contains queries whether a given Component contains a particular point.
	Contains(x, y int, ctype CoordType) error
	// AccessibleAtPoint gets the accessible child at a given coordinate within
	// an Component.
	AccessibleAtPoint(x, y int, ctype CoordType) (*Accessible, error)
	// Alpha gets the opacity/alpha value of a component, if alpha blending is
	// in use.
	Alpha() (float64, error)
	// Extents gets the bounding box of the specified Component.
	Extents(ctype CoordType) (*Rect, error)
	// Layer queries which layer the component is painted into, to help
	// determine its visibility in terms of stacking order.
	Layer() (ComponentLayer, error)
	// MDIZOrder queries the z stacking order of a component which is in the MDI
	// or window layer.
	MDIZOrder() (int16, error)
	// Position gets the minimum x and y coordinates of the specified Component.
	Position(ctype CoordType) (*Point, error)
	// Size gets the size of the specified Component.
	Size() (*Point, error)
	// GrabFocus attempts to set the keyboard input focus to the specified
	// Component.
	GrabFocus() error
	// ScrollTo scrolls whatever container of the Component object so it becomes
	// visible on the screen.
	ScrollTo(typ ScrollType) error
	// ScrollToPoint scrolls whatever container of the Component object so it
	// becomes visible on the screen at a given position.
	ScrollToPoint(coords CoordType, x, y int) error
	// SetExtents moves and resizes the specified component.
	SetExtents(x, y, width, height int, ctype CoordType) error
	// SetPosition moves the component to the specified position.
	SetPosition(x, y int, ctype CoordType) error
	// SetSize resizes the specified component to the given pixel dimensions.
	SetSize(width, height int) error
}

var _ Componenter = (*Component)(nil)

func wrapComponent(obj *coreglib.Object) *Component {
	return &Component{
		Object: obj,
	}
}

func marshalComponent(p uintptr) (interface{}, error) {
	return wrapComponent(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// Contains queries whether a given Component contains a particular point.
//
// The function takes the following parameters:
//
//   - x specifying the x coordinate in question.
//   - y specifying the y coordinate in question.
//   - ctype: desired coordinate system of the point (x, y) (e.g.
//     CSPI_COORD_TYPE_WINDOW, CSPI_COORD_TYPE_SCREEN).
func (obj *Component) Contains(x, y int, ctype CoordType) error {
	var _arg0 *C.AtspiComponent // out
	var _arg1 C.gint            // out
	var _arg2 C.gint            // out
	var _arg3 C.AtspiCoordType  // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(x)
	_arg2 = C.gint(y)
	_arg3 = C.AtspiCoordType(ctype)

	C.atspi_component_contains(_arg0, _arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)
	runtime.KeepAlive(ctype)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// AccessibleAtPoint gets the accessible child at a given coordinate within an
// Component.
//
// The function takes the following parameters:
//
//   - x specifying the x coordinate of the point in question.
//   - y specifying the y coordinate of the point in question.
//   - ctype: coordinate system of the point (x, y) (e.g.
//     ATSPI_COORD_TYPE_WINDOW, ATSPI_COORD_TYPE_SCREEN).
//
// The function returns the following values:
//
//   - accessible (optional): pointer to an Accessible child of the specified
//     component which contains the point (x, y), or NULL if no child contains
//     the point.
func (obj *Component) AccessibleAtPoint(x, y int, ctype CoordType) (*Accessible, error) {
	var _arg0 *C.AtspiComponent  // out
	var _arg1 C.gint             // out
	var _arg2 C.gint             // out
	var _arg3 C.AtspiCoordType   // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(x)
	_arg2 = C.gint(y)
	_arg3 = C.AtspiCoordType(ctype)

	_cret = C.atspi_component_get_accessible_at_point(_arg0, _arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)
	runtime.KeepAlive(ctype)

	var _accessible *Accessible // out
	var _goerr error            // out

	if _cret != nil {
		_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// Alpha gets the opacity/alpha value of a component, if alpha blending is in
// use.
//
// The function returns the following values:
//
//   - gdouble: opacity value of a component, as a #gdouble between 0.0 and 1.0.
func (obj *Component) Alpha() (float64, error) {
	var _arg0 *C.AtspiComponent // out
	var _cret C.gdouble         // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_component_get_alpha(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gdouble float64 // out
	var _goerr error     // out

	_gdouble = float64(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gdouble, _goerr
}

// Extents gets the bounding box of the specified Component. The returned
// values are meaningful only if the Component has both STATE_VISIBLE and
// STATE_SHOWING.
//
// The function takes the following parameters:
//
//   - ctype: desired coordinate system into which to return the results, (e.g.
//     ATSPI_COORD_TYPE_WINDOW, ATSPI_COORD_TYPE_SCREEN).
//
// The function returns the following values:
//
//   - rect giving the accessible's extents.
func (obj *Component) Extents(ctype CoordType) (*Rect, error) {
	var _arg0 *C.AtspiComponent // out
	var _arg1 C.AtspiCoordType  // out
	var _cret *C.AtspiRect      // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.AtspiCoordType(ctype)

	_cret = C.atspi_component_get_extents(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(ctype)

	var _rect *Rect  // out
	var _goerr error // out

	_rect = (*Rect)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_rect)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _rect, _goerr
}

// Layer queries which layer the component is painted into, to help determine
// its visibility in terms of stacking order.
//
// The function returns the following values:
//
//   - componentLayer into which this component is painted.
func (obj *Component) Layer() (ComponentLayer, error) {
	var _arg0 *C.AtspiComponent     // out
	var _cret C.AtspiComponentLayer // in
	var _cerr *C.GError             // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_component_get_layer(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _componentLayer ComponentLayer // out
	var _goerr error                   // out

	_componentLayer = ComponentLayer(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _componentLayer, _goerr
}

// MDIZOrder queries the z stacking order of a component which is in the MDI or
// window layer. (Bigger z-order numbers mean nearer the top).
//
// The function returns the following values:
//
//   - gshort indicating the stacking order of the component in the MDI layer,
//     or -1 if the component is not in the MDI layer.
func (obj *Component) MDIZOrder() (int16, error) {
	var _arg0 *C.AtspiComponent // out
	var _cret C.gshort          // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_component_get_mdi_z_order(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gshort int16 // out
	var _goerr error  // out

	_gshort = int16(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gshort, _goerr
}

// Position gets the minimum x and y coordinates of the specified Component. The
// returned values are meaningful only if the Component has both STATE_VISIBLE
// and STATE_SHOWING.
//
// The function takes the following parameters:
//
//   - ctype: desired coordinate system into which to return the results, (e.g.
//     ATSPI_COORD_TYPE_WINDOW, ATSPI_COORD_TYPE_SCREEN).
//
// The function returns the following values:
//
//   - point giving the obj's position.
func (obj *Component) Position(ctype CoordType) (*Point, error) {
	var _arg0 *C.AtspiComponent // out
	var _arg1 C.AtspiCoordType  // out
	var _cret *C.AtspiPoint     // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.AtspiCoordType(ctype)

	_cret = C.atspi_component_get_position(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(ctype)

	var _point *Point // out
	var _goerr error  // out

	_point = (*Point)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_point)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _point, _goerr
}

// Size gets the size of the specified Component. The returned values are
// meaningful only if the Component has both STATE_VISIBLE and STATE_SHOWING.
//
// The function returns the following values:
//
//   - point giving the obj's size.
func (obj *Component) Size() (*Point, error) {
	var _arg0 *C.AtspiComponent // out
	var _cret *C.AtspiPoint     // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_component_get_size(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _point *Point // out
	var _goerr error  // out

	_point = (*Point)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_point)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _point, _goerr
}

// GrabFocus attempts to set the keyboard input focus to the specified
// Component.
func (obj *Component) GrabFocus() error {
	var _arg0 *C.AtspiComponent // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	C.atspi_component_grab_focus(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// ScrollTo scrolls whatever container of the Component object so it becomes
// visible on the screen.
//
// The function takes the following parameters:
//
//   - typ indicating where the object should be placed on the screen.
func (obj *Component) ScrollTo(typ ScrollType) error {
	var _arg0 *C.AtspiComponent // out
	var _arg1 C.AtspiScrollType // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.AtspiScrollType(typ)

	C.atspi_component_scroll_to(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(typ)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// ScrollToPoint scrolls whatever container of the Component object so it
// becomes visible on the screen at a given position.
//
// The function takes the following parameters:
//
//   - coords indicating whether the coordinates are relative to the screen,
//     to the window, or to the parent object.
//   - x coordinate of the point to reach.
//   - y coordinate of the point to reach.
func (obj *Component) ScrollToPoint(coords CoordType, x, y int) error {
	var _arg0 *C.AtspiComponent // out
	var _arg1 C.AtspiCoordType  // out
	var _arg2 C.gint            // out
	var _arg3 C.gint            // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.AtspiCoordType(coords)
	_arg2 = C.gint(x)
	_arg3 = C.gint(y)

	C.atspi_component_scroll_to_point(_arg0, _arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(coords)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// SetExtents moves and resizes the specified component.
//
// The function takes the following parameters:
//
//   - x: new horizontal position to which the component should be moved.
//   - y: new vertical position to which the component should be moved.
//   - width to which the component should be resized.
//   - height to which the component should be resized.
//   - ctype: coordinate system in which the position is specified. (e.g.
//     ATSPI_COORD_TYPE_WINDOW, ATSPI_COORD_TYPE_SCREEN).
func (obj *Component) SetExtents(x, y, width, height int, ctype CoordType) error {
	var _arg0 *C.AtspiComponent // out
	var _arg1 C.gint            // out
	var _arg2 C.gint            // out
	var _arg3 C.gint            // out
	var _arg4 C.gint            // out
	var _arg5 C.AtspiCoordType  // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(x)
	_arg2 = C.gint(y)
	_arg3 = C.gint(width)
	_arg4 = C.gint(height)
	_arg5 = C.AtspiCoordType(ctype)

	C.atspi_component_set_extents(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)
	runtime.KeepAlive(width)
	runtime.KeepAlive(height)
	runtime.KeepAlive(ctype)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// SetPosition moves the component to the specified position.
//
// The function takes the following parameters:
//
//   - x: new horizontal position to which the component should be moved.
//   - y: new vertical position to which the component should be moved.
//   - ctype: coordinate system in which the position is specified. (e.g.
//     ATSPI_COORD_TYPE_WINDOW, ATSPI_COORD_TYPE_SCREEN).
func (obj *Component) SetPosition(x, y int, ctype CoordType) error {
	var _arg0 *C.AtspiComponent // out
	var _arg1 C.gint            // out
	var _arg2 C.gint            // out
	var _arg3 C.AtspiCoordType  // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(x)
	_arg2 = C.gint(y)
	_arg3 = C.AtspiCoordType(ctype)

	C.atspi_component_set_position(_arg0, _arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)
	runtime.KeepAlive(ctype)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// SetSize resizes the specified component to the given pixel dimensions.
//
// The function takes the following parameters:
//
//   - width to which the component should be resized.
//   - height to which the component should be resized.
func (obj *Component) SetSize(width, height int) error {
	var _arg0 *C.AtspiComponent // out
	var _arg1 C.gint            // out
	var _arg2 C.gint            // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiComponent)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(width)
	_arg2 = C.gint(height)

	C.atspi_component_set_size(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(width)
	runtime.KeepAlive(height)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// Point: instance of this type is always passed by reference.
type Point struct {
	*point
}

// point is the struct that's finalized.
type point struct {
	native *C.AtspiPoint
}

func marshalPoint(p uintptr) (interface{}, error) {
	b := coreglib.ValueFromNative(unsafe.Pointer(p)).Boxed()
	return &Point{&point{(*C.AtspiPoint)(b)}}, nil
}

// NewPoint creates a new Point instance from the given
// fields. Beware that this function allocates on the Go heap; be careful
// when using it!
func NewPoint(x, y int) Point {
	var f0 C.gint // out
	f0 = C.gint(x)
	var f1 C.gint // out
	f1 = C.gint(y)

	v := C.AtspiPoint{
		x: f0,
		y: f1,
	}

	return *(*Point)(gextras.NewStructNative(unsafe.Pointer(&v)))
}

func (p *Point) X() int {
	valptr := &p.native.x
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (p *Point) Y() int {
	valptr := &p.native.y
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (p *Point) SetX(x int) {
	valptr := &p.native.x
	*valptr = C.gint(x)
}

func (p *Point) SetY(y int) {
	valptr := &p.native.y
	*valptr = C.gint(y)
}

func (src *Point) Copy() *Point {
	var _arg0 *C.AtspiPoint // out
	var _cret *C.AtspiPoint // in

	_arg0 = (*C.AtspiPoint)(gextras.StructNative(unsafe.Pointer(src)))

	_cret = C.atspi_point_copy(_arg0)
	runtime.KeepAlive(src)

	var _point *Point // out

	_point = (*Point)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_point)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)

	return _point
}

// Rect: instance of this type is always passed by reference.
type Rect struct {
	*rect
}

// rect is the struct that's finalized.
type rect struct {
	native *C.AtspiRect
}

func marshalRect(p uintptr) (interface{}, error) {
	b := coreglib.ValueFromNative(unsafe.Pointer(p)).Boxed()
	return &Rect{&rect{(*C.AtspiRect)(b)}}, nil
}

// NewRect creates a new Rect instance from the given
// fields. Beware that this function allocates on the Go heap; be careful
// when using it!
func NewRect(x, y, width, height int) Rect {
	var f0 C.gint // out
	f0 = C.gint(x)
	var f1 C.gint // out
	f1 = C.gint(y)
	var f2 C.gint // out
	f2 = C.gint(width)
	var f3 C.gint // out
	f3 = C.gint(height)

	v := C.AtspiRect{
		x:      f0,
		y:      f1,
		width:  f2,
		height: f3,
	}

	return *(*Rect)(gextras.NewStructNative(unsafe.Pointer(&v)))
}

func (r *Rect) X() int {
	valptr := &r.native.x
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (r *Rect) Y() int {
	valptr := &r.native.y
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (r *Rect) Width() int {
	valptr := &r.native.width
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (r *Rect) Height() int {
	valptr := &r.native.height
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (r *Rect) SetX(x int) {
	valptr := &r.native.x
	*valptr = C.gint(x)
}

func (r *Rect) SetY(y int) {
	valptr := &r.native.y
	*valptr = C.gint(y)
}

func (r *Rect) SetWidth(width int) {
	valptr := &r.native.width
	*valptr = C.gint(width)
}

func (r *Rect) SetHeight(height int) {
	valptr := &r.native.height
	*valptr = C.gint(height)
}

func (src *Rect) Copy() *Rect {
	var _arg0 *C.AtspiRect // out
	var _cret *C.AtspiRect // in

	_arg0 = (*C.AtspiRect)(gextras.StructNative(unsafe.Pointer(src)))

	_cret = C.atspi_rect_copy(_arg0)
	runtime.KeepAlive(src)

	var _rect *Rect // out

	_rect = (*Rect)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_rect)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)

	return _rect
}
