// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeMatchRule = coreglib.Type(C.atspi_match_rule_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeMatchRule, F: marshalMatchRule},
	})
}

// MatchRuleOverrides contains methods that are overridable.
type MatchRuleOverrides struct {
}

func defaultMatchRuleOverrides(v *MatchRule) MatchRuleOverrides {
	return MatchRuleOverrides{}
}

// MatchRule: interface that allows the definition of match rules for accessible
// objects.
type MatchRule struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*MatchRule)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*MatchRule, *MatchRuleClass, MatchRuleOverrides](
		GTypeMatchRule,
		initMatchRuleClass,
		wrapMatchRule,
		defaultMatchRuleOverrides,
	)
}

func initMatchRuleClass(gclass unsafe.Pointer, overrides MatchRuleOverrides, classInitFunc func(*MatchRuleClass)) {
	if classInitFunc != nil {
		class := (*MatchRuleClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapMatchRule(obj *coreglib.Object) *MatchRule {
	return &MatchRule{
		Object: obj,
	}
}

func marshalMatchRule(p uintptr) (interface{}, error) {
	return wrapMatchRule(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// MatchRuleClass: instance of this type is always passed by reference.
type MatchRuleClass struct {
	*matchRuleClass
}

// matchRuleClass is the struct that's finalized.
type matchRuleClass struct {
	native *C.AtspiMatchRuleClass
}
