// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"fmt"
	"unsafe"

	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeCollectionMatchType         = coreglib.Type(C.atspi_collection_match_type_get_type())
	GTypeCollectionSortOrder         = coreglib.Type(C.atspi_collection_sort_order_get_type())
	GTypeCollectionTreeTraversalType = coreglib.Type(C.atspi_collection_tree_traversal_type_get_type())
	GTypeComponentLayer              = coreglib.Type(C.atspi_component_layer_get_type())
	GTypeCoordType                   = coreglib.Type(C.atspi_coord_type_get_type())
	GTypeEventType                   = coreglib.Type(C.atspi_event_type_get_type())
	GTypeKeyEventType                = coreglib.Type(C.atspi_key_event_type_get_type())
	GTypeKeySynthType                = coreglib.Type(C.atspi_key_synth_type_get_type())
	GTypeLive                        = coreglib.Type(C.atspi_live_get_type())
	GTypeLocaleType                  = coreglib.Type(C.atspi_locale_type_get_type())
	GTypeRelationType                = coreglib.Type(C.atspi_relation_type_get_type())
	GTypeRole                        = coreglib.Type(C.atspi_role_get_type())
	GTypeScrollType                  = coreglib.Type(C.atspi_scroll_type_get_type())
	GTypeStateType                   = coreglib.Type(C.atspi_state_type_get_type())
	GTypeTextBoundaryType            = coreglib.Type(C.atspi_text_boundary_type_get_type())
	GTypeTextClipType                = coreglib.Type(C.atspi_text_clip_type_get_type())
	GTypeTextGranularity             = coreglib.Type(C.atspi_text_granularity_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeCollectionMatchType, F: marshalCollectionMatchType},
		coreglib.TypeMarshaler{T: GTypeCollectionSortOrder, F: marshalCollectionSortOrder},
		coreglib.TypeMarshaler{T: GTypeCollectionTreeTraversalType, F: marshalCollectionTreeTraversalType},
		coreglib.TypeMarshaler{T: GTypeComponentLayer, F: marshalComponentLayer},
		coreglib.TypeMarshaler{T: GTypeCoordType, F: marshalCoordType},
		coreglib.TypeMarshaler{T: GTypeEventType, F: marshalEventType},
		coreglib.TypeMarshaler{T: GTypeKeyEventType, F: marshalKeyEventType},
		coreglib.TypeMarshaler{T: GTypeKeySynthType, F: marshalKeySynthType},
		coreglib.TypeMarshaler{T: GTypeLive, F: marshalLive},
		coreglib.TypeMarshaler{T: GTypeLocaleType, F: marshalLocaleType},
		coreglib.TypeMarshaler{T: GTypeRelationType, F: marshalRelationType},
		coreglib.TypeMarshaler{T: GTypeRole, F: marshalRole},
		coreglib.TypeMarshaler{T: GTypeScrollType, F: marshalScrollType},
		coreglib.TypeMarshaler{T: GTypeStateType, F: marshalStateType},
		coreglib.TypeMarshaler{T: GTypeTextBoundaryType, F: marshalTextBoundaryType},
		coreglib.TypeMarshaler{T: GTypeTextClipType, F: marshalTextClipType},
		coreglib.TypeMarshaler{T: GTypeTextGranularity, F: marshalTextGranularity},
	})
}

// COMPONENTLAYER_COUNT: one higher than the highest valid value of
// ComponentLayer.
const COMPONENTLAYER_COUNT = 9

// COORD_TYPE_COUNT: one higher than the highest valid value of CoordType.
const COORD_TYPE_COUNT = 3
const DBUS_INTERFACE_ACCESSIBLE = "org.a11y.atspi.Accessible"
const DBUS_INTERFACE_ACTION = "org.a11y.atspi.Action"
const DBUS_INTERFACE_APPLICATION = "org.a11y.atspi.Application"
const DBUS_INTERFACE_CACHE = "org.a11y.atspi.Cache"
const DBUS_INTERFACE_COLLECTION = "org.a11y.atspi.Collection"
const DBUS_INTERFACE_COMPONENT = "org.a11y.atspi.Component"
const DBUS_INTERFACE_DEC = "org.a11y.atspi.DeviceEventController"
const DBUS_INTERFACE_DEVICE_EVENT_LISTENER = "org.a11y.atspi.DeviceEventListener"
const DBUS_INTERFACE_DOCUMENT = "org.a11y.atspi.Document"
const DBUS_INTERFACE_EDITABLE_TEXT = "org.a11y.atspi.EditableText"
const DBUS_INTERFACE_EVENT_KEYBOARD = "org.a11y.atspi.Event.Keyboard"
const DBUS_INTERFACE_EVENT_MOUSE = "org.a11y.atspi.Event.Mouse"
const DBUS_INTERFACE_EVENT_OBJECT = "org.a11y.atspi.Event.Object"
const DBUS_INTERFACE_EVENT_SCREEN_READER = "org.a11y.atspi.Event.ScreenReader"
const DBUS_INTERFACE_HYPERLINK = "org.a11y.atspi.Hyperlink"
const DBUS_INTERFACE_HYPERTEXT = "org.a11y.atspi.Hypertext"
const DBUS_INTERFACE_IMAGE = "org.a11y.atspi.Image"
const DBUS_INTERFACE_REGISTRY = "org.a11y.atspi.Registry"
const DBUS_INTERFACE_SELECTION = "org.a11y.atspi.Selection"
const DBUS_INTERFACE_SOCKET = "org.a11y.atspi.Socket"
const DBUS_INTERFACE_TABLE = "org.a11y.atspi.Table"
const DBUS_INTERFACE_TABLE_CELL = "org.a11y.atspi.TableCell"
const DBUS_INTERFACE_TEXT = "org.a11y.atspi.Text"
const DBUS_INTERFACE_VALUE = "org.a11y.atspi.Value"
const DBUS_NAME_REGISTRY = "org.a11y.atspi.Registry"
const DBUS_PATH_DEC = "/org/a11y/atspi/registry/deviceeventcontroller"
const DBUS_PATH_NULL = "/org/a11y/atspi/null"
const DBUS_PATH_REGISTRY = "/org/a11y/atspi/registry"
const DBUS_PATH_ROOT = "/org/a11y/atspi/accessible/root"
const DBUS_PATH_SCREEN_READER = "/org/a11y/atspi/screenreader"

// EVENTTYPE_COUNT: one higher than the highest valid value of EventType.
const EVENTTYPE_COUNT = 4

// KEYEVENTTYPE_COUNT: one higher than the highest valid value of KeyEventType.
const KEYEVENTTYPE_COUNT = 2

// KEYSYNTHTYPE_COUNT: one higher than the highest valid value of KeySynthType.
const KEYSYNTHTYPE_COUNT = 5

// LOCALE_TYPE_COUNT: one higher than the highest valid value of LocaleType.
const LOCALE_TYPE_COUNT = 6
const MATCHTYPES_COUNT = 6

// MODIFIERTYPE_COUNT: one higher than the highest valid value of ModifierType.
const MODIFIERTYPE_COUNT = 8

// RELATIONTYPE_COUNT: one higher than the highest valid value of RelationType.
const RELATIONTYPE_COUNT = 24

// ROLE_COUNT: one higher than the highest valid value of Role.
const ROLE_COUNT = 131

// SCROLLTYPE_COUNT: one higher than the highest valid value of ScrollType.
const SCROLLTYPE_COUNT = 7

// SORTORDER_COUNT: one higher than the highest valid value of
// CollectionSortOrder.
const SORTORDER_COUNT = 8

// STATETYPE_COUNT: one higher than the highest valid value of StateType.
const STATETYPE_COUNT = 42

// TEXT_BOUNDARY_TYPE_COUNT: one higher than the highest valid value of
// TextBoundaryType.
const TEXT_BOUNDARY_TYPE_COUNT = 7

// TEXT_CLIP_TYPE_COUNT: one higher than the highest valid value of
// TextClipType.
const TEXT_CLIP_TYPE_COUNT = 4

// TREETRAVERSALTYPE_COUNT: one higher than the highest valid value of
// Collection_TreeTraversalType.
const TREETRAVERSALTYPE_COUNT = 4

// CollectionMatchType: enumeration used by MatchRule to specify how to
// interpret Accessible objects.
type CollectionMatchType C.gint

const (
	// CollectionMatchInvalid indicates an error condition or uninitialized
	// value.
	CollectionMatchInvalid CollectionMatchType = iota
	// CollectionMatchAll if all of the criteria are met.
	CollectionMatchAll
	// CollectionMatchAny if any of the criteria are met.
	CollectionMatchAny
	// CollectionMatchNone if none of the criteria are met.
	CollectionMatchNone
	// CollectionMatchEmpty: same as ATSPI_Collection_MATCH_ALL if the criteria
	// is non-empty; for empty criteria this rule requires returned value to
	// also have empty set.
	CollectionMatchEmpty
	// CollectionMatchLastDefined: used only to determine the end of the
	// enumeration.
	CollectionMatchLastDefined
)

func marshalCollectionMatchType(p uintptr) (interface{}, error) {
	return CollectionMatchType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for CollectionMatchType.
func (c CollectionMatchType) String() string {
	switch c {
	case CollectionMatchInvalid:
		return "Invalid"
	case CollectionMatchAll:
		return "All"
	case CollectionMatchAny:
		return "Any"
	case CollectionMatchNone:
		return "None"
	case CollectionMatchEmpty:
		return "Empty"
	case CollectionMatchLastDefined:
		return "LastDefined"
	default:
		return fmt.Sprintf("CollectionMatchType(%d)", c)
	}
}

// CollectionSortOrder: enumeration used by interface Collection to specify the
// way Accesible objects should be sorted.
type CollectionSortOrder C.gint

const (
	// CollectionSortOrderInvalid: invalid sort order.
	CollectionSortOrderInvalid CollectionSortOrder = iota
	// CollectionSortOrderCanonical: canonical sort order.
	CollectionSortOrderCanonical
	// CollectionSortOrderFlow: flow sort order.
	CollectionSortOrderFlow
	// CollectionSortOrderTab: tab sort order.
	CollectionSortOrderTab
	// CollectionSortOrderReverseCanonical: reverse canonical sort order.
	CollectionSortOrderReverseCanonical
	// CollectionSortOrderReverseFlow: reverse flow sort order.
	CollectionSortOrderReverseFlow
	// CollectionSortOrderReverseTab: reverse tab sort order.
	CollectionSortOrderReverseTab
	// CollectionSortOrderLastDefined: used only to determine the end of the
	// enumeration.
	CollectionSortOrderLastDefined
)

func marshalCollectionSortOrder(p uintptr) (interface{}, error) {
	return CollectionSortOrder(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for CollectionSortOrder.
func (c CollectionSortOrder) String() string {
	switch c {
	case CollectionSortOrderInvalid:
		return "Invalid"
	case CollectionSortOrderCanonical:
		return "Canonical"
	case CollectionSortOrderFlow:
		return "Flow"
	case CollectionSortOrderTab:
		return "Tab"
	case CollectionSortOrderReverseCanonical:
		return "ReverseCanonical"
	case CollectionSortOrderReverseFlow:
		return "ReverseFlow"
	case CollectionSortOrderReverseTab:
		return "ReverseTab"
	case CollectionSortOrderLastDefined:
		return "LastDefined"
	default:
		return fmt.Sprintf("CollectionSortOrder(%d)", c)
	}
}

// CollectionTreeTraversalType: enumeration used by interface Collection to
// specify restrictions on Accesible objects to be traversed.
type CollectionTreeTraversalType C.gint

const (
	// CollectionTreeRestrictChildren: restrict children tree traveral.
	CollectionTreeRestrictChildren CollectionTreeTraversalType = iota
	// CollectionTreeRestrictSibling: restrict sibling tree traversal.
	CollectionTreeRestrictSibling
	// CollectionTreeInorder: in-order tree traversal.
	CollectionTreeInorder
	// CollectionTreeLastDefined: used only to determine the end of the
	// enumeration.
	CollectionTreeLastDefined
)

func marshalCollectionTreeTraversalType(p uintptr) (interface{}, error) {
	return CollectionTreeTraversalType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for CollectionTreeTraversalType.
func (c CollectionTreeTraversalType) String() string {
	switch c {
	case CollectionTreeRestrictChildren:
		return "RestrictChildren"
	case CollectionTreeRestrictSibling:
		return "RestrictSibling"
	case CollectionTreeInorder:
		return "Inorder"
	case CollectionTreeLastDefined:
		return "LastDefined"
	default:
		return fmt.Sprintf("CollectionTreeTraversalType(%d)", c)
	}
}

// ComponentLayer of an Component instance indicates its relative stacking order
// with respect to the onscreen visual representation of the UI. ComponentLayer,
// in combination with Component bounds information, can be used to compute the
// visibility of all or part of a component. This is important in programmatic
// determination of region-of-interest for magnification, and in flat screen
// review models of the screen, as well as for other uses. Objects residing in
// two of the ComponentLayer categories support further z-ordering information,
// with respect to their peers in the same layer: namely, ATSPI_LAYER_WINDOW
// and ATSPI_LAYER_MDI. Relative stacking order for other objects within the
// same layer is not available; the recommended heuristic is first child paints
// first. In other words, assume that the first siblings in the child list are
// subject to being overpainted by later siblings if their bounds intersect.
// The order of layers, from bottom to top, is: ATSPI_LAYER_BACKGROUND,
// ATSPI_LAYER_WINDOW, ATSPI_LAYER_MDI, ATSPI_LAYER_CANVAS, ATSPI_LAYER_WIDGET,
// ATSPI_LAYER_POPUP, and ATSPI_LAYER_OVERLAY.
type ComponentLayer C.gint

const (
	// LayerInvalid indicates an error condition or uninitialized value.
	LayerInvalid ComponentLayer = iota
	// LayerBackground: bottom-most layer, over which everything else is
	// painted. The 'desktop background' is generally in this layer.
	LayerBackground
	// LayerCanvas: 'background' layer for most content renderers and UI
	// Component containers.
	LayerCanvas
	// LayerWidget: layer in which the majority of ordinary 'foreground' widgets
	// reside.
	LayerWidget
	// LayerMDI: special layer between ATSPI_LAYER_CANVAS and
	// ATSPI_LAYER_WIDGET, in which the 'pseudo windows' (e.g. the MDI frames)
	// reside. See #atspi_component_get_mdi_z_order.
	LayerMDI
	// LayerPopup: layer for popup window content, above ATSPI_LAYER_WIDGET.
	LayerPopup
	// LayerOverlay: topmost layer.
	LayerOverlay
	// LayerWindow: layer in which a toplevel window background usually resides.
	LayerWindow
	// LayerLastDefined: used only to determine the end of the enumeration.
	LayerLastDefined
)

func marshalComponentLayer(p uintptr) (interface{}, error) {
	return ComponentLayer(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for ComponentLayer.
func (c ComponentLayer) String() string {
	switch c {
	case LayerInvalid:
		return "Invalid"
	case LayerBackground:
		return "Background"
	case LayerCanvas:
		return "Canvas"
	case LayerWidget:
		return "Widget"
	case LayerMDI:
		return "MDI"
	case LayerPopup:
		return "Popup"
	case LayerOverlay:
		return "Overlay"
	case LayerWindow:
		return "Window"
	case LayerLastDefined:
		return "LastDefined"
	default:
		return fmt.Sprintf("ComponentLayer(%d)", c)
	}
}

// CoordType: enumeration used by Component, Image, and Text interfaces to
// specify whether coordinates are relative to the window or the screen.
type CoordType C.gint

const (
	// CoordTypeScreen specifies xy coordinates relative to the screen.
	CoordTypeScreen CoordType = iota
	// CoordTypeWindow specifies xy coordinates relative to the widget's
	// top-level window.
	CoordTypeWindow
	// CoordTypeParent specifies xy coordinates relative to the widget's
	// immediate parent.
	CoordTypeParent
)

func marshalCoordType(p uintptr) (interface{}, error) {
	return CoordType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for CoordType.
func (c CoordType) String() string {
	switch c {
	case CoordTypeScreen:
		return "Screen"
	case CoordTypeWindow:
		return "Window"
	case CoordTypeParent:
		return "Parent"
	default:
		return fmt.Sprintf("CoordType(%d)", c)
	}
}

// EventType: enumeration used to specify the event types of interest to an
// EventListener, or to identify the type of an event for which notification has
// been sent.
type EventType C.gint

const (
	// KeyPressedEvent indicates that a key on a keyboard device was pressed.
	KeyPressedEvent EventType = iota
	// KeyReleasedEvent indicates that a key on a keyboard device was released.
	KeyReleasedEvent
	// ButtonPressedEvent indicates that a button on a non-keyboard human
	// interface device (HID) was pressed.
	ButtonPressedEvent
	// ButtonReleasedEvent indicates that a button on a non-keyboard human
	// interface device (HID) was released.
	ButtonReleasedEvent
)

func marshalEventType(p uintptr) (interface{}, error) {
	return EventType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for EventType.
func (e EventType) String() string {
	switch e {
	case KeyPressedEvent:
		return "KeyPressedEvent"
	case KeyReleasedEvent:
		return "KeyReleasedEvent"
	case ButtonPressedEvent:
		return "ButtonPressedEvent"
	case ButtonReleasedEvent:
		return "ButtonReleasedEvent"
	default:
		return fmt.Sprintf("EventType(%d)", e)
	}
}

// KeyEventType: deprecated. Should not be used.
type KeyEventType C.gint

const (
	// KeyPressed: key press event.
	KeyPressed KeyEventType = iota
	// KeyReleased: key release event.
	KeyReleased
)

func marshalKeyEventType(p uintptr) (interface{}, error) {
	return KeyEventType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for KeyEventType.
func (k KeyEventType) String() string {
	switch k {
	case KeyPressed:
		return "Pressed"
	case KeyReleased:
		return "Released"
	default:
		return fmt.Sprintf("KeyEventType(%d)", k)
	}
}

// KeySynthType: enumeration used when synthesizing keyboard input via
// #atspi_generate_keyboard_event.
type KeySynthType C.gint

const (
	// KeyPress emulates the pressing of a hardware keyboard key.
	KeyPress KeySynthType = iota
	// KeyRelease emulates the release of a hardware keyboard key.
	KeyRelease
	// KeyPressrelease emulates the pressing and immediate releasing of a
	// hardware keyboard key.
	KeyPressrelease
	// KeySym: symbolic key event is generated, without specifying a hardware
	// key. Note: if the keysym is not present in the current keyboard map,
	// the DeviceEventController instance has a limited ability to generate
	// such keysyms on-the-fly. Reliability of GenerateKeyboardEvent calls using
	// out-of-keymap keysyms will vary from system to system, and on the number
	// of different out-of-keymap keysyms being generated in quick succession.
	// In practice this is rarely significant, since the keysyms of interest to
	// AT clients and keyboard emulators are usually part of the current keymap,
	// i.e., present on the system keyboard for the current locale (even if a
	// physical hardware keyboard is not connected).
	KeySym
	// KeyString: string is converted to its equivalent keyboard events and
	// emitted. If the string consists of complex characters or composed
	// characters which are not in the current keymap, string emission is
	// subject to the out-of-keymap limitations described for ATSPI_KEY_SYM. In
	// practice this limitation primarily effects Chinese and Japanese locales.
	KeyString
	// KeyLockmodifiers emulates locking a set of modifiers.
	KeyLockmodifiers
	// KeyUnlockmodifiers emulates unlocking a set of modifiers.
	KeyUnlockmodifiers
)

func marshalKeySynthType(p uintptr) (interface{}, error) {
	return KeySynthType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for KeySynthType.
func (k KeySynthType) String() string {
	switch k {
	case KeyPress:
		return "Press"
	case KeyRelease:
		return "Release"
	case KeyPressrelease:
		return "Pressrelease"
	case KeySym:
		return "Sym"
	case KeyString:
		return "String"
	case KeyLockmodifiers:
		return "Lockmodifiers"
	case KeyUnlockmodifiers:
		return "Unlockmodifiers"
	default:
		return fmt.Sprintf("KeySynthType(%d)", k)
	}
}

// Live: enumeration used to indicate a type of live region and how assertive
// it should be in terms of speaking notifications. Currently, this is only used
// for "announcement" events, but it may be used for additional purposes in the
// future.
type Live C.gint

const (
	// LiveNone: no live region.
	LiveNone Live = iota
	// LivePolite: this live region should be considered polite.
	LivePolite
	// LiveAssertive: this live region should be considered assertive.
	LiveAssertive
)

func marshalLive(p uintptr) (interface{}, error) {
	return Live(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for Live.
func (l Live) String() string {
	switch l {
	case LiveNone:
		return "None"
	case LivePolite:
		return "Polite"
	case LiveAssertive:
		return "Assertive"
	default:
		return fmt.Sprintf("Live(%d)", l)
	}
}

// LocaleType: used by interfaces Text and Document, this enumeration
// corresponds to the POSIX 'setlocale' enum values.
type LocaleType C.gint

const (
	// LocaleTypeMessages: for localizable natural-language messages.
	LocaleTypeMessages LocaleType = iota
	// LocaleTypeCollate: for regular expression matching and string collation.
	LocaleTypeCollate
	// LocaleTypeCtype: for regular expression matching, character
	// classification, conversion, case-sensitive comparison, and wide character
	// functions.
	LocaleTypeCtype
	// LocaleTypeMonetary: for monetary formatting.
	LocaleTypeMonetary
	// LocaleTypeNumeric: for number formatting (such as the decimal point and
	// the thousands separator).
	LocaleTypeNumeric
	// LocaleTypeTime: for time and date formatting.
	LocaleTypeTime
)

func marshalLocaleType(p uintptr) (interface{}, error) {
	return LocaleType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for LocaleType.
func (l LocaleType) String() string {
	switch l {
	case LocaleTypeMessages:
		return "Messages"
	case LocaleTypeCollate:
		return "Collate"
	case LocaleTypeCtype:
		return "Ctype"
	case LocaleTypeMonetary:
		return "Monetary"
	case LocaleTypeNumeric:
		return "Numeric"
	case LocaleTypeTime:
		return "Time"
	default:
		return fmt.Sprintf("LocaleType(%d)", l)
	}
}

// RelationType specifies a relationship between objects (possibly one-to-many
// or many-to-one) outside of the normal parent/child hierarchical relationship.
// It allows better semantic identification of how objects are associated with
// one another. For instance the ATSPI_RELATION_LABELLED_BY relationship may be
// used to identify labelling information that should accompany the accessible
// name property when presenting an object's content or identity to the end
// user. Similarly, ATSPI_RELATION_CONTROLLER_FOR can be used to further specify
// the context in which a valuator is useful, and/or the other UI components
// which are directly effected by user interactions with the valuator. Common
// examples include association of scrollbars with the viewport or panel which
// they control.
//
//	Enumeration used to specify the type of relation encapsulated in an Relation object.
type RelationType C.gint

const (
	// RelationNull: not a meaningful relationship; clients should not normally
	// encounter this RelationType value.
	RelationNull RelationType = iota
	// RelationLabelFor: object is a label for one or more other objects.
	RelationLabelFor
	// RelationLabelledBy: object is labelled by one or more other objects.
	RelationLabelledBy
	// RelationControllerFor: object is an interactive object which modifies
	// the state, onscreen location, or other attributes of one or more target
	// objects.
	RelationControllerFor
	// RelationControlledBy: object state, position, etc. is modified/controlled
	// by user interaction with one or more other objects. For instance a
	// viewport or scroll pane may be ATSPI_RELATION_CONTROLLED_BY scrollbars.
	RelationControlledBy
	// RelationMemberOf: object has a grouping relationship (e.g. 'same group
	// as') to one or more other objects.
	RelationMemberOf
	// RelationTooltipFor: object is a tooltip associated with another object.
	RelationTooltipFor
	// RelationNodeChildOf: object is a child of the target.
	RelationNodeChildOf
	// RelationNodeParentOf: object is a parent of the target.
	RelationNodeParentOf
	// RelationExtended: used to indicate that a relationship exists, but its
	// type is not specified in the enumeration.
	RelationExtended
	// RelationFlowsTo: object renders content which flows logically to another
	// object. For instance, text in a paragraph may flow to another object
	// which is not the 'next sibling' in the accessibility hierarchy.
	RelationFlowsTo
	// RelationFlowsFrom: reciprocal of ATSPI_RELATION_FLOWS_TO.
	RelationFlowsFrom
	// RelationSubwindowOf: object is visually and semantically considered a
	// subwindow of another object, even though it is not the object's child.
	// Useful when dealing with embedded applications and other cases where the
	// widget hierarchy does not map cleanly to the onscreen presentation.
	RelationSubwindowOf
	// RelationEmbeds: similar to ATSPI_RELATION_SUBWINDOW_OF, but specifically
	// used for cross-process embedding.
	RelationEmbeds
	// RelationEmbeddedBy: reciprocal of ATSPI_RELATION_EMBEDS. Used to denote
	// content rendered by embedded renderers that live in a separate process
	// space from the embedding context.
	RelationEmbeddedBy
	// RelationPopupFor denotes that the object is a transient window or frame
	// associated with another onscreen object. Similar to ATSPI_TOOLTIP_FOR,
	// but more general. Useful for windows which are technically toplevels but
	// which, for one or more reasons, do not explicitly cause their associated
	// window to lose 'window focus'. Creation of an ATSPI_ROLE_WINDOW
	// object with the ATSPI_RELATION_POPUP_FOR relation usually requires
	// some presentation action on the part of assistive technology clients,
	// even though the previous toplevel ATSPI_ROLE_FRAME object may still be
	// the active window.
	RelationPopupFor
	// RelationParentWindowOf: this is the reciprocal relation to
	// ATSPI_RELATION_POPUP_FOR.
	RelationParentWindowOf
	// RelationDescriptionFor: reciprocal of ATSPI_RELATION_DESCRIBED_BY.
	// Indicates that this object provides descriptive information about
	// the target object(s). See also ATSPI_RELATION_DETAILS_FOR and
	// ATSPI_RELATION_ERROR_FOR.
	RelationDescriptionFor
	// RelationDescribedBy: reciprocal of ATSPI_RELATION_DESCRIPTION_FOR.
	// Indicates that one or more target objects provide descriptive information
	// about this object. This relation type is most appropriate for information
	// that is not essential as its presentation may be user-configurable
	// and/or limited to an on-demand mechanism such as an assistive technology
	// command. For brief, essential information such as can be found in
	// a widget's on-screen label, use ATSPI_RELATION_LABELLED_BY. For an
	// on-screen error message, use ATSPI_RELATION_ERROR_MESSAGE. For lengthy
	// extended descriptive information contained in an on-screen object,
	// consider using ATSPI_RELATION_DETAILS as assistive technologies may
	// provide a means for the user to navigate to objects containing detailed
	// descriptions so that their content can be more closely reviewed.
	RelationDescribedBy
	// RelationDetails: reciprocal of ATSPI_RELATION_DETAILS_FOR.
	// Indicates that this object has a detailed or extended description,
	// the contents of which can be found in the target object(s). This relation
	// type is most appropriate for information that is sufficiently lengthy
	// as to make navigation to the container of that information desirable.
	// For less verbose information suitable for announcement only, see
	// ATSPI_RELATION_DESCRIBED_BY. If the detailed information describes an
	// error condition, ATSPI_RELATION_ERROR_FOR should be used instead. Since:
	// 2.26.
	RelationDetails
	// RelationDetailsFor: reciprocal of ATSPI_RELATION_DETAILS. Indicates
	// that this object provides a detailed or extended description about
	// the target object(s). See also ATSPI_RELATION_DESCRIPTION_FOR and
	// ATSPI_RELATION_ERROR_FOR. Since: 2.26.
	RelationDetailsFor
	// RelationErrorMessage: reciprocal of ATSPI_RELATION_ERROR_FOR. Indicates
	// that this object has one or more errors, the nature of which is described
	// in the contents of the target object(s). Objects that have this relation
	// type should also contain ATSPI_STATE_INVALID_ENTRY in their StateSet.
	// Since: 2.26.
	RelationErrorMessage
	// RelationErrorFor: reciprocal of ATSPI_RELATION_ERROR_MESSAGE. Indicates
	// that this object contains an error message describing an invalid
	// condition in the target object(s). Since: 2.26.
	RelationErrorFor
	// RelationLastDefined: do not use as a parameter value, used to determine
	// the size of the enumeration.
	RelationLastDefined
)

func marshalRelationType(p uintptr) (interface{}, error) {
	return RelationType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for RelationType.
func (r RelationType) String() string {
	switch r {
	case RelationNull:
		return "Null"
	case RelationLabelFor:
		return "LabelFor"
	case RelationLabelledBy:
		return "LabelledBy"
	case RelationControllerFor:
		return "ControllerFor"
	case RelationControlledBy:
		return "ControlledBy"
	case RelationMemberOf:
		return "MemberOf"
	case RelationTooltipFor:
		return "TooltipFor"
	case RelationNodeChildOf:
		return "NodeChildOf"
	case RelationNodeParentOf:
		return "NodeParentOf"
	case RelationExtended:
		return "Extended"
	case RelationFlowsTo:
		return "FlowsTo"
	case RelationFlowsFrom:
		return "FlowsFrom"
	case RelationSubwindowOf:
		return "SubwindowOf"
	case RelationEmbeds:
		return "Embeds"
	case RelationEmbeddedBy:
		return "EmbeddedBy"
	case RelationPopupFor:
		return "PopupFor"
	case RelationParentWindowOf:
		return "ParentWindowOf"
	case RelationDescriptionFor:
		return "DescriptionFor"
	case RelationDescribedBy:
		return "DescribedBy"
	case RelationDetails:
		return "Details"
	case RelationDetailsFor:
		return "DetailsFor"
	case RelationErrorMessage:
		return "ErrorMessage"
	case RelationErrorFor:
		return "ErrorFor"
	case RelationLastDefined:
		return "LastDefined"
	default:
		return fmt.Sprintf("RelationType(%d)", r)
	}
}

// Role: enumeration used by interface Accessible to specify the role of an
// Accessible object.
type Role C.gint

const (
	// RoleInvalid: role indicating an error condition, such as uninitialized
	// Role data.
	RoleInvalid Role = iota
	// RoleAcceleratorLabel: object is a label indicating the keyboard
	// accelerators for the parent.
	RoleAcceleratorLabel
	// RoleAlert: object is used to alert the user about something.
	RoleAlert
	// RoleAnimation: object contains a dynamic or moving image of some kind.
	RoleAnimation
	// RoleArrow: object is a 2d directional indicator.
	RoleArrow
	// RoleCalendar: object contains one or more dates, usually arranged into a
	// 2d list.
	RoleCalendar
	// RoleCanvas: object that can be drawn into and is used to trap events.
	RoleCanvas
	// RoleCheckBox: choice that can be checked or unchecked and provides a
	// separate indicator for the current state.
	RoleCheckBox
	// RoleCheckMenuItem: menu item that behaves like a check box. See
	// ATSPI_ROLE_CHECK_BOX.
	RoleCheckMenuItem
	// RoleColorChooser: specialized dialog that lets the user choose a color.
	RoleColorChooser
	// RoleColumnHeader: header for a column of data.
	RoleColumnHeader
	// RoleComboBox: list of choices the user can select from.
	RoleComboBox
	// RoleDateEditor: object which allows entry of a date.
	RoleDateEditor
	// RoleDesktopIcon: inconifed internal frame within a DESKTOP_FRAME.
	RoleDesktopIcon
	// RoleDesktopFrame: pane that supports internal frames and iconified
	// versions of those internal frames.
	RoleDesktopFrame
	// RoleDial: object that allows a value to be changed via rotating a visual
	// element, or which displays a value via such a rotating element.
	RoleDial
	// RoleDialog: top level window with title bar and a border.
	RoleDialog
	// RoleDirectoryPane: pane that allows the user to navigate through and
	// select the contents of a directory.
	RoleDirectoryPane
	// RoleDrawingArea: object used for drawing custom user interface elements.
	RoleDrawingArea
	// RoleFileChooser: specialized dialog that displays the files in the
	// directory and lets the user select a file, browse a different directory,
	// or specify a filename.
	RoleFileChooser
	// RoleFiller: object that fills up space in a user interface.
	RoleFiller
	// RoleFocusTraversable: don't use, reserved for future use.
	RoleFocusTraversable
	// RoleFontChooser allows selection of a display font.
	RoleFontChooser
	// RoleFrame: top level window with a title bar, border, menubar, etc.
	RoleFrame
	// RoleGlassPane: pane that is guaranteed to be painted on top of all panes
	// beneath it.
	RoleGlassPane
	// RoleHtmlContainer: document container for HTML, whose children represent
	// the document content.
	RoleHtmlContainer
	// RoleIcon: small fixed size picture, typically used to decorate
	// components.
	RoleIcon
	// RoleImage: image, typically static.
	RoleImage
	// RoleInternalFrame: frame-like object that is clipped by a desktop pane.
	RoleInternalFrame
	// RoleLabel: object used to present an icon or short string in an
	// interface.
	RoleLabel
	// RoleLayeredPane: specialized pane that allows its children to be drawn in
	// layers, providing a form of stacking order.
	RoleLayeredPane
	// RoleList: object that presents a list of objects to the user and allows
	// the user to select one or more of them.
	RoleList
	// RoleListItem: object that represents an element of a list.
	RoleListItem
	// RoleMenu: object usually found inside a menu bar that contains a list of
	// actions the user can choose from.
	RoleMenu
	// RoleMenuBar: object usually drawn at the top of the primary dialog box of
	// an application that contains a list of menus the user can choose from.
	RoleMenuBar
	// RoleMenuItem: object usually contained in a menu that presents an action
	// the user can choose.
	RoleMenuItem
	// RoleOptionPane: specialized pane whose primary use is inside a dialog.
	RoleOptionPane
	// RolePageTab: object that is a child of a page tab list.
	RolePageTab
	// RolePageTabList: object that presents a series of panels (or page tabs),
	// one at a time,through some mechanism provided by the object.
	RolePageTabList
	// RolePanel: generic container that is often used to group objects.
	RolePanel
	// RolePasswordText: text object uses for passwords, or other places where
	// the text content is not shown visibly to the user.
	RolePasswordText
	// RolePopupMenu: temporary window that is usually used to offer the user
	// a list of choices, and then hides when the user selects one of those
	// choices.
	RolePopupMenu
	// RoleProgressBar: object used to indicate how much of a task has been
	// completed.
	RoleProgressBar
	// RolePushButton: object the user can manipulate to tell the application to
	// do something.
	RolePushButton
	// RoleRadioButton: specialized check box that will cause other radio
	// buttons in the same group to become unchecked when this one is checked.
	RoleRadioButton
	// RoleRadioMenuItem: object is both a menu item and a "radio button" .
	// See ATSPI_ROLE_RADIO_BUTTON.
	RoleRadioMenuItem
	// RoleRootPane: specialized pane that has a glass pane and a layered pane
	// as its children.
	RoleRootPane
	// RoleRowHeader: header for a row of data.
	RoleRowHeader
	// RoleScrollBar: object usually used to allow a user to incrementally
	// view a large amount of data by moving the bounds of a viewport along a
	// one-dimensional axis.
	RoleScrollBar
	// RoleScrollPane: object that allows a user to incrementally view
	// a large amount of information. ATSPI_ROLE_SCROLL_PANE objects are
	// usually accompanied by ATSPI_ROLE_SCROLL_BAR controllers, on which the
	// ATSPI_RELATION_CONTROLLER_FOR and ATSPI_RELATION_CONTROLLED_BY reciprocal
	// relations are set. See #atspi_get_relation_set.
	RoleScrollPane
	// RoleSeparator: object usually contained in a menu to provide a visible
	// and logical separation of the contents in a menu.
	RoleSeparator
	// RoleSlider: object that allows the user to select from a bounded range.
	// Unlike ATSPI_ROLE_SCROLL_BAR, ATSPI_ROLE_SLIDER objects need not control
	// 'viewport'-like objects.
	RoleSlider
	// RoleSpinButton: object which allows one of a set of choices to be
	// selected, and which displays the current choice.
	RoleSpinButton
	// RoleSplitPane: specialized panel that presents two other panels at the
	// same time.
	RoleSplitPane
	// RoleStatusBar: object displays non-quantitative status information (c.f.
	// ATSPI_ROLE_PROGRESS_BAR).
	RoleStatusBar
	// RoleTable: object used to repesent information in terms of rows and
	// columns.
	RoleTable
	// RoleTableCell: 'cell' or discrete child within a Table. Note: Table cells
	// need not have ATSPI_ROLE_TABLE_CELL, other RoleType values are valid as
	// well.
	RoleTableCell
	// RoleTableColumnHeader: object which labels a particular column in an
	// Table.
	RoleTableColumnHeader
	// RoleTableRowHeader: object which labels a particular row in
	// a Table. Table rows and columns may also be labelled via the
	// ATSPI_RELATION_LABEL_FOR/ATSPI_RELATION_LABELLED_BY relationships.
	// See #atspi_get_relation_set.
	RoleTableRowHeader
	// RoleTearoffMenuItem: object allows menu to be removed from menubar and
	// shown in its own window.
	RoleTearoffMenuItem
	// RoleTerminal: object that emulates a terminal.
	RoleTerminal
	// RoleText: interactive widget that supports multiple lines of text and
	// optionally accepts user input, but whose purpose is not to solicit user
	// input. Thus ATSPI_ROLE_TEXT is appropriate for the text view in a plain
	// text editor but inappropriate for an input field in a dialog box or web
	// form. For widgets whose purpose is to solicit input from the user, see
	// ATSPI_ROLE_ENTRY and ATSPI_ROLE_PASSWORD_TEXT. For generic objects which
	// display a brief amount of textual information, see ATSPI_ROLE_STATIC.
	RoleText
	// RoleToggleButton: specialized push button that can be checked or
	// unchecked, but does not procide a separate indicator for the current
	// state.
	RoleToggleButton
	// RoleToolBar: bar or palette usually composed of push buttons or toggle
	// buttons.
	RoleToolBar
	// RoleToolTip: object that provides information about another object.
	RoleToolTip
	// RoleTree: object used to repsent hierarchical information to the user.
	RoleTree
	// RoleTreeTable: object that presents both tabular and hierarchical info to
	// the user.
	RoleTreeTable
	// RoleUnknown: object contains some Accessible information, but its role is
	// not known.
	RoleUnknown
	// RoleViewport: object usually used in a scroll pane, or to otherwise clip
	// a larger object or content renderer to a specific onscreen viewport.
	RoleViewport
	// RoleWindow: top level window with no title or border.
	RoleWindow
	// RoleExtended means that the role for this item is known, but not included
	// in the core enumeration. Deprecated since 2.24.
	RoleExtended
	// RoleHeader: object that serves as a document header.
	RoleHeader
	// RoleFooter: object that serves as a document footer.
	RoleFooter
	// RoleParagraph: object which is contains a single paragraph of text
	// content. See also ATSPI_ROLE_TEXT.
	RoleParagraph
	// RoleRuler: object which describes margins and tab stops, etc. for text
	// objects which it controls (should have ATSPI_RELATION_CONTROLLER_FOR
	// relation to such).
	RoleRuler
	// RoleApplication: object corresponding to the toplevel accessible of
	// an application, which may contain ATSPI_ROLE_FRAME objects or other
	// accessible objects. Children of objects with the SPI_ROLE_DESKTOP_FRAME
	// role are generally ATSPI_ROLE_APPLICATION objects.
	RoleApplication
	// RoleAutocomplete: object is a dialog or list containing items for
	// insertion into an entry widget, for instance a list of words for
	// completion of a text entry.
	RoleAutocomplete
	// RoleEditbar: object is an editable text object in a toolbar.
	RoleEditbar
	// RoleEmbedded: object is an embedded component container. This role is
	// a "grouping" hint that the contained objects share a context which is
	// different from the container in which this accessible is embedded.
	// In particular, it is used for some kinds of document embedding, and for
	// embedding of out-of-process component, "panel applets", etc.
	RoleEmbedded
	// RoleEntry: object is a component whose textual content may be entered
	// or modified by the user, provided ATSPI_STATE_EDITABLE is present.
	// A readonly ATSPI_ROLE_ENTRY object (i.e. where ATSPI_STATE_EDITABLE is
	// not present) implies a read-only 'text field' in a form, as opposed to a
	// title, label, or caption.
	RoleEntry
	// RoleChart: object is a graphical depiction of quantitative data.
	// It may contain multiple subelements whose attributes and/or description
	// may be queried to obtain both the quantitative data and information
	// about how the data is being presented. The ATSPI_LABELLED_BY relation is
	// particularly important in interpreting objects of this type, as is the
	// accessible description property. See ATSPI_ROLE_CAPTION.
	RoleChart
	// RoleCaption: object contains descriptive information, usually textual,
	// about another user interface element such as a table, chart, or image.
	RoleCaption
	// RoleDocumentFrame: object is a visual frame or container which
	// contains a view of document content. Document frames may occur within
	// another Document instance, in which case the second document may be
	// said to be embedded in the containing instance. HTML frames are often
	// ATSPI_ROLE_DOCUMENT_FRAME: Either this object, or a singleton descendant,
	// should implement the Document interface.
	RoleDocumentFrame
	// RoleHeading: object serves as a heading for content which follows it
	// in a document. The 'heading level' of the heading, if availabe, may be
	// obtained by querying the object's attributes.
	RoleHeading
	// RolePage: object is a containing instance which encapsulates a page
	// of information. ATSPI_ROLE_PAGE is used in documents and content which
	// support a paginated navigation model.
	RolePage
	// RoleSection: object is a containing instance of document content which
	// constitutes a particular 'logical' section of the document. The type of
	// content within a section, and the nature of the section division itself,
	// may be obtained by querying the object's attributes. Sections may be
	// nested.
	RoleSection
	// RoleRedundantObject: object is redundant with another object in the
	// hierarchy, and is exposed for purely technical reasons. Objects of this
	// role should be ignored by clients, if they are encountered at all.
	RoleRedundantObject
	// RoleForm: object is a containing instance of document content which has
	// within it components with which the user can interact in order to input
	// information; i.e. the object is a container for pushbuttons, comboboxes,
	// text input fields, and other 'GUI' components. ATSPI_ROLE_FORM should
	// not, in general, be used for toplevel GUI containers or dialogs,
	// but should be reserved for 'GUI' containers which occur within
	// document content, for instance within Web documents, presentations,
	// or text documents. Unlike other GUI containers and dialogs which occur
	// inside application instances, ATSPI_ROLE_FORM containers' components are
	// associated with the current document, rather than the current foreground
	// application or viewer instance.
	RoleForm
	// RoleLink: object is a hypertext anchor, i.e. a "link" in a hypertext
	// document. Such objects are distinct from 'inline' content which may also
	// use the Hypertext/Hyperlink interfacesto indicate the range/location
	// within a text object where an inline or embedded object lies.
	RoleLink
	// RoleInputMethodWindow: object is a window or similar viewport which is
	// used to allow composition or input of a 'complex character', in other
	// words it is an "input method window".
	RoleInputMethodWindow
	// RoleTableRow: row in a table.
	RoleTableRow
	// RoleTreeItem: object that represents an element of a tree.
	RoleTreeItem
	// RoleDocumentSpreadsheet: document frame which contains a spreadsheet.
	RoleDocumentSpreadsheet
	// RoleDocumentPresentation: document frame which contains a presentation or
	// slide content.
	RoleDocumentPresentation
	// RoleDocumentText: document frame which contains textual content, such as
	// found in a word processing application.
	RoleDocumentText
	// RoleDocumentWeb: document frame which contains HTML or other markup
	// suitable for display in a web browser.
	RoleDocumentWeb
	// RoleDocumentEmail: document frame which contains email content to be
	// displayed or composed either in plain text or HTML.
	RoleDocumentEmail
	// RoleComment: object found within a document and designed to present a
	// comment, note, or other annotation. In some cases, this object might not
	// be visible until activated.
	RoleComment
	// RoleListBox: non-collapsible list of choices the user can select from.
	RoleListBox
	// RoleGrouping: group of related widgets. This group typically has a label.
	RoleGrouping
	// RoleImageMap: image map object. Usually a graphic with multiple hotspots,
	// where each hotspot can be activated resulting in the loading of another
	// document or section of a document.
	RoleImageMap
	// RoleNotification: transitory object designed to present a message to the
	// user, typically at the desktop level rather than inside a particular
	// application.
	RoleNotification
	// RoleInfoBar: object designed to present a message to the user within an
	// existing window.
	RoleInfoBar
	// RoleLevelBar: bar that serves as a level indicator to, for instance,
	// show the strength of a password or the state of a battery. Since: 2.8.
	RoleLevelBar
	// RoleTitleBar: bar that serves as the title of a window or a dialog.
	// Since: 2.12.
	RoleTitleBar
	// RoleBlockQuote: object which contains a text section that is quoted from
	// another source. Since: 2.12.
	RoleBlockQuote
	// RoleAudio: object which represents an audio element. Since: 2.12.
	RoleAudio
	// RoleVideo: object which represents a video element. Since: 2.12.
	RoleVideo
	// RoleDefinition: definition of a term or concept. Since: 2.12.
	RoleDefinition
	// RoleArticle: section of a page that consists of a composition that forms
	// an independent part of a document, page, or site. Examples: A blog entry,
	// a news story, a forum post. Since: 2.12.
	RoleArticle
	// RoleLandmark: region of a web page intended as a navigational landmark.
	// This is designed to allow Assistive Technologies to provide quick
	// navigation among key regions within a document. Since: 2.12.
	RoleLandmark
	// RoleLog: text widget or container holding log content, such as chat
	// history and error logs. In this role there is a relationship between the
	// arrival of new items in the log and the reading order. The log contains
	// a meaningful sequence and new information is added only to the end of the
	// log, not at arbitrary points. Since: 2.12.
	RoleLog
	// RoleMarquee: container where non-essential information changes
	// frequently. Common usages of marquee include stock tickers and ad
	// banners. The primary difference between a marquee and a log is that logs
	// usually have a meaningful order or sequence of important content changes.
	// Since: 2.12.
	RoleMarquee
	// RoleMath: text widget or container that holds a mathematical expression.
	// Since: 2.12.
	RoleMath
	// RoleRating: widget whose purpose is to display a rating, such as the
	// number of stars associated with a song in a media player. Objects of this
	// role should also implement AtspiValue. Since: 2.12.
	RoleRating
	// RoleTimer: object containing a numerical counter which indicates an
	// amount of elapsed time from a start point, or the time remaining until an
	// end point. Since: 2.12.
	RoleTimer
	// RoleStatic: generic non-container object whose purpose is to display
	// a brief amount of information to the user and whose role is known by
	// the implementor but lacks semantic value for the user. Examples in
	// which ATSPI_ROLE_STATIC is appropriate include the message displayed
	// in a message box and an image used as an alternative means to display
	// text. ATSPI_ROLE_STATIC should not be applied to widgets which are
	// traditionally interactive, objects which display a significant amount
	// of content, or any object which has an accessible relation pointing
	// to another object. The displayed information, as a general rule,
	// should be exposed through the accessible name of the object. For labels
	// which describe another widget, see ATSPI_ROLE_LABEL. For text views,
	// see ATSPI_ROLE_TEXT. For generic containers, see ATSPI_ROLE_PANEL.
	// For objects whose role is not known by the implementor, see
	// ATSPI_ROLE_UNKNOWN. Since: 2.16.
	RoleStatic
	// RoleMathFraction: object that represents a mathematical fraction. Since:
	// 2.16.
	RoleMathFraction
	// RoleMathRoot: object that represents a mathematical expression displayed
	// with a radical. Since: 2.16.
	RoleMathRoot
	// RoleSubscript: object that contains text that is displayed as a
	// subscript. Since: 2.16.
	RoleSubscript
	// RoleSuperscript: object that contains text that is displayed as a
	// superscript. Since: 2.16.
	RoleSuperscript
	// RoleDescriptionList: object that represents a list of term-value groups.
	// A term-value group represents an individual description and consist of
	// one or more names (ATSPI_ROLE_DESCRIPTION_TERM) followed by one or more
	// values (ATSPI_ROLE_DESCRIPTION_VALUE). For each list, there should not be
	// more than one group with the same term name. Since: 2.26.
	RoleDescriptionList
	// RoleDescriptionTerm: object that represents a term or phrase with a
	// corresponding definition. Since: 2.26.
	RoleDescriptionTerm
	// RoleDescriptionValue: object that represents the description, definition,
	// or value of a term. Since: 2.26.
	RoleDescriptionValue
	// RoleFootnote: object that contains the text of a footnote. Since: 2.26.
	RoleFootnote
	// RoleContentDeletion: content previously deleted or proposed to be
	// deleted, e.g. in revision history or a content view providing suggestions
	// from reviewers. Since: 2.34.
	RoleContentDeletion
	// RoleContentInsertion: content previously inserted or proposed to
	// be inserted, e.g. in revision history or a content view providing
	// suggestions from reviewers. Since: 2.34.
	RoleContentInsertion
	// RoleMark: run of content that is marked or highlighted, such as for
	// reference purposes, or to call it out as having a special purpose. If the
	// marked content has an associated section in the document elaborating on
	// the reason for the mark, then ATSPI_RELATION_DETAILS should be used on
	// the mark to point to that associated section. In addition, the reciprocal
	// relation ATSPI_RELATION_DETAILS_FOR should be used on the associated
	// content section to point back to the mark. Since: 2.36.
	RoleMark
	// RoleSuggestion: container for content that is called out as a proposed
	// change from the current version of the document, such as by a reviewer
	// of the content. An object with this role should include children with
	// ATSPI_ROLE_CONTENT_DELETION and/or ATSPI_ROLE_CONTENT_INSERTION, in any
	// order, to indicate what the actual change is. Since: 2.36.
	RoleSuggestion
	// RolePushButtonMenu: specialized push button to open a menu. Since 2.46.
	RolePushButtonMenu
	// RoleLastDefined: not a valid role, used for finding end of enumeration.
	RoleLastDefined
)

func marshalRole(p uintptr) (interface{}, error) {
	return Role(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for Role.
func (r Role) String() string {
	switch r {
	case RoleInvalid:
		return "Invalid"
	case RoleAcceleratorLabel:
		return "AcceleratorLabel"
	case RoleAlert:
		return "Alert"
	case RoleAnimation:
		return "Animation"
	case RoleArrow:
		return "Arrow"
	case RoleCalendar:
		return "Calendar"
	case RoleCanvas:
		return "Canvas"
	case RoleCheckBox:
		return "CheckBox"
	case RoleCheckMenuItem:
		return "CheckMenuItem"
	case RoleColorChooser:
		return "ColorChooser"
	case RoleColumnHeader:
		return "ColumnHeader"
	case RoleComboBox:
		return "ComboBox"
	case RoleDateEditor:
		return "DateEditor"
	case RoleDesktopIcon:
		return "DesktopIcon"
	case RoleDesktopFrame:
		return "DesktopFrame"
	case RoleDial:
		return "Dial"
	case RoleDialog:
		return "Dialog"
	case RoleDirectoryPane:
		return "DirectoryPane"
	case RoleDrawingArea:
		return "DrawingArea"
	case RoleFileChooser:
		return "FileChooser"
	case RoleFiller:
		return "Filler"
	case RoleFocusTraversable:
		return "FocusTraversable"
	case RoleFontChooser:
		return "FontChooser"
	case RoleFrame:
		return "Frame"
	case RoleGlassPane:
		return "GlassPane"
	case RoleHtmlContainer:
		return "HtmlContainer"
	case RoleIcon:
		return "Icon"
	case RoleImage:
		return "Image"
	case RoleInternalFrame:
		return "InternalFrame"
	case RoleLabel:
		return "Label"
	case RoleLayeredPane:
		return "LayeredPane"
	case RoleList:
		return "List"
	case RoleListItem:
		return "ListItem"
	case RoleMenu:
		return "Menu"
	case RoleMenuBar:
		return "MenuBar"
	case RoleMenuItem:
		return "MenuItem"
	case RoleOptionPane:
		return "OptionPane"
	case RolePageTab:
		return "PageTab"
	case RolePageTabList:
		return "PageTabList"
	case RolePanel:
		return "Panel"
	case RolePasswordText:
		return "PasswordText"
	case RolePopupMenu:
		return "PopupMenu"
	case RoleProgressBar:
		return "ProgressBar"
	case RolePushButton:
		return "PushButton"
	case RoleRadioButton:
		return "RadioButton"
	case RoleRadioMenuItem:
		return "RadioMenuItem"
	case RoleRootPane:
		return "RootPane"
	case RoleRowHeader:
		return "RowHeader"
	case RoleScrollBar:
		return "ScrollBar"
	case RoleScrollPane:
		return "ScrollPane"
	case RoleSeparator:
		return "Separator"
	case RoleSlider:
		return "Slider"
	case RoleSpinButton:
		return "SpinButton"
	case RoleSplitPane:
		return "SplitPane"
	case RoleStatusBar:
		return "StatusBar"
	case RoleTable:
		return "Table"
	case RoleTableCell:
		return "TableCell"
	case RoleTableColumnHeader:
		return "TableColumnHeader"
	case RoleTableRowHeader:
		return "TableRowHeader"
	case RoleTearoffMenuItem:
		return "TearoffMenuItem"
	case RoleTerminal:
		return "Terminal"
	case RoleText:
		return "Text"
	case RoleToggleButton:
		return "ToggleButton"
	case RoleToolBar:
		return "ToolBar"
	case RoleToolTip:
		return "ToolTip"
	case RoleTree:
		return "Tree"
	case RoleTreeTable:
		return "TreeTable"
	case RoleUnknown:
		return "Unknown"
	case RoleViewport:
		return "Viewport"
	case RoleWindow:
		return "Window"
	case RoleExtended:
		return "Extended"
	case RoleHeader:
		return "Header"
	case RoleFooter:
		return "Footer"
	case RoleParagraph:
		return "Paragraph"
	case RoleRuler:
		return "Ruler"
	case RoleApplication:
		return "Application"
	case RoleAutocomplete:
		return "Autocomplete"
	case RoleEditbar:
		return "Editbar"
	case RoleEmbedded:
		return "Embedded"
	case RoleEntry:
		return "Entry"
	case RoleChart:
		return "Chart"
	case RoleCaption:
		return "Caption"
	case RoleDocumentFrame:
		return "DocumentFrame"
	case RoleHeading:
		return "Heading"
	case RolePage:
		return "Page"
	case RoleSection:
		return "Section"
	case RoleRedundantObject:
		return "RedundantObject"
	case RoleForm:
		return "Form"
	case RoleLink:
		return "Link"
	case RoleInputMethodWindow:
		return "InputMethodWindow"
	case RoleTableRow:
		return "TableRow"
	case RoleTreeItem:
		return "TreeItem"
	case RoleDocumentSpreadsheet:
		return "DocumentSpreadsheet"
	case RoleDocumentPresentation:
		return "DocumentPresentation"
	case RoleDocumentText:
		return "DocumentText"
	case RoleDocumentWeb:
		return "DocumentWeb"
	case RoleDocumentEmail:
		return "DocumentEmail"
	case RoleComment:
		return "Comment"
	case RoleListBox:
		return "ListBox"
	case RoleGrouping:
		return "Grouping"
	case RoleImageMap:
		return "ImageMap"
	case RoleNotification:
		return "Notification"
	case RoleInfoBar:
		return "InfoBar"
	case RoleLevelBar:
		return "LevelBar"
	case RoleTitleBar:
		return "TitleBar"
	case RoleBlockQuote:
		return "BlockQuote"
	case RoleAudio:
		return "Audio"
	case RoleVideo:
		return "Video"
	case RoleDefinition:
		return "Definition"
	case RoleArticle:
		return "Article"
	case RoleLandmark:
		return "Landmark"
	case RoleLog:
		return "Log"
	case RoleMarquee:
		return "Marquee"
	case RoleMath:
		return "Math"
	case RoleRating:
		return "Rating"
	case RoleTimer:
		return "Timer"
	case RoleStatic:
		return "Static"
	case RoleMathFraction:
		return "MathFraction"
	case RoleMathRoot:
		return "MathRoot"
	case RoleSubscript:
		return "Subscript"
	case RoleSuperscript:
		return "Superscript"
	case RoleDescriptionList:
		return "DescriptionList"
	case RoleDescriptionTerm:
		return "DescriptionTerm"
	case RoleDescriptionValue:
		return "DescriptionValue"
	case RoleFootnote:
		return "Footnote"
	case RoleContentDeletion:
		return "ContentDeletion"
	case RoleContentInsertion:
		return "ContentInsertion"
	case RoleMark:
		return "Mark"
	case RoleSuggestion:
		return "Suggestion"
	case RolePushButtonMenu:
		return "PushButtonMenu"
	case RoleLastDefined:
		return "LastDefined"
	default:
		return fmt.Sprintf("Role(%d)", r)
	}
}

// ScrollType: enumeration used by interface Accessible to specify where an
// Accessible object should be placed on the screen when using scroll_to.
type ScrollType C.gint

const (
	// ScrollTopLeft: scroll the object to the top left corner of the window.
	ScrollTopLeft ScrollType = iota
	// ScrollBottomRight: scroll the object to the bottom right corner of the
	// window.
	ScrollBottomRight
	// ScrollTopEdge: scroll the object to the top edge of the window.
	ScrollTopEdge
	// ScrollBottomEdge: scroll the object to the bottom edge of the window.
	ScrollBottomEdge
	// ScrollLeftEdge: scroll the object to the left edge of the window.
	ScrollLeftEdge
	// ScrollRightEdge: scroll the object to the right edge of the window.
	ScrollRightEdge
	// ScrollAnywhere: scroll the object to application-dependent position on
	// the window.
	ScrollAnywhere
)

func marshalScrollType(p uintptr) (interface{}, error) {
	return ScrollType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for ScrollType.
func (s ScrollType) String() string {
	switch s {
	case ScrollTopLeft:
		return "TopLeft"
	case ScrollBottomRight:
		return "BottomRight"
	case ScrollTopEdge:
		return "TopEdge"
	case ScrollBottomEdge:
		return "BottomEdge"
	case ScrollLeftEdge:
		return "LeftEdge"
	case ScrollRightEdge:
		return "RightEdge"
	case ScrollAnywhere:
		return "Anywhere"
	default:
		return fmt.Sprintf("ScrollType(%d)", s)
	}
}

// StateType: enumeration used by various interfaces indicating every possible
// state an Accesible object can assume.
type StateType C.gint

const (
	// StateInvalid indicates an invalid state - probably an error condition.
	StateInvalid StateType = iota
	// StateActive indicates a window is currently the active window,
	// or an object is the active subelement within a container or table.
	// ATSPI_STATE_ACTIVE should not be used for objects which have
	// SPI_STATE_FOCUSABLE or SPI_STATE_SELECTABLE: Those objects should
	// use ATSPI_STATE_FOCUSED and ATSPI_STATE_SELECTED respectively.
	// ATSPI_STATE_ACTIVE is a means to indicate that an object which is not
	// focusable and not selectable is the currently-active item within its
	// parent container.
	StateActive
	// StateArmed indicates that the object is armed.
	StateArmed
	// StateBusy indicates the current object is busy, i.e. onscreen
	// representation is in the process of changing, or the object is
	// temporarily unavailable for interaction due to activity already in
	// progress.
	StateBusy
	// StateChecked indicates this object is currently checked.
	StateChecked
	// StateCollapsed indicates this object is collapsed.
	StateCollapsed
	// StateDefunct indicates that this object no longer has a valid backing
	// widget (for instance, if its peer object has been destroyed).
	StateDefunct
	// StateEditable indicates the user can change the contents of this object.
	StateEditable
	// StateEnabled indicates that this object is enabled, i.e. that it
	// currently reflects some application state. Objects that are "greyed out"
	// may lack this state, and may lack the ATSPI_STATE_SENSITIVE if direct
	// user interaction cannot cause them to acquire ATSPI_STATE_ENABLED.
	// See ATSPI_STATE_SENSITIVE.
	StateEnabled
	// StateExpandable indicates this object allows progressive disclosure of
	// its children.
	StateExpandable
	// StateExpanded indicates this object is expanded.
	StateExpanded
	// StateFocusable indicates this object can accept keyboard focus, which
	// means all events resulting from typing on the keyboard will normally be
	// passed to it when it has focus.
	StateFocusable
	// StateFocused indicates this object currently has the keyboard focus.
	StateFocused
	// StateHasTooltip indicates that the object has an associated tooltip.
	StateHasTooltip
	// StateHorizontal indicates the orientation of this object is horizontal.
	StateHorizontal
	// StateIconified indicates this object is minimized and is represented only
	// by an icon.
	StateIconified
	// StateModal indicates something must be done with this object before the
	// user can interact with an object in a different window.
	StateModal
	// StateMultiLine indicates this (text) object can contain multiple lines of
	// text.
	StateMultiLine
	// StateMultiselectable indicates this object allows more than one of its
	// children to be selected at the same time, or in the case of text objects,
	// that the object supports non-contiguous text selections.
	StateMultiselectable
	// StateOpaque indicates this object paints every pixel within its
	// rectangular region. It also indicates an alpha value of unity, if it
	// supports alpha blending.
	StateOpaque
	// StatePressed indicates this object is currently pressed.
	StatePressed
	// StateResizable indicates the size of this object's size is not fixed.
	StateResizable
	// StateSelectable indicates this object is the child of an object that
	// allows its children to be selected and that this child is one of those
	// children that can be selected.
	StateSelectable
	// StateSelected indicates this object is the child of an object that allows
	// its children to be selected and that this child is one of those children
	// that has been selected.
	StateSelected
	// StateSensitive indicates this object is sensitive, e.g.
	// to user interaction. ATSPI_STATE_SENSITIVE usually accompanies.
	// ATSPI_STATE_ENABLED for user-actionable controls, but may be found in
	// the absence of ATSPI_STATE_ENABLED if the current visible state of the
	// control is "disconnected" from the application state. In such cases,
	// direct user interaction can often result in the object gaining
	// ATSPI_STATE_SENSITIVE, for instance if a user makes an explicit
	// selection using an object whose current state is ambiguous or undefined.
	// See ATSPI_STATE_ENABLED, ATSPI_STATE_INDETERMINATE.
	StateSensitive
	// StateShowing indicates this object, the object's parent, the object's
	// parent's parent, and so on, are all 'shown' to the end-user, i.e. subject
	// to "exposure" if blocking or obscuring objects do not interpose between
	// this object and the top of the window stack.
	StateShowing
	// StateSingleLine indicates this (text) object can contain only a single
	// line of text.
	StateSingleLine
	// StateStale indicates that the information returned for this object may no
	// longer be synchronized with the application state. This can occur if the
	// object has ATSPI_STATE_TRANSIENT, and can also occur towards the end of
	// the object peer's lifecycle.
	StateStale
	// StateTransient indicates this object is transient.
	StateTransient
	// StateVertical indicates the orientation of this object is vertical;
	// for example this state may appear on such objects as scrollbars, text
	// objects (with vertical text flow), separators, etc.
	StateVertical
	// StateVisible indicates this object is visible, e.g. has been explicitly
	// marked for exposure to the user. ATSPI_STATE_VISIBLE is no guarantee
	// that the object is actually unobscured on the screen, only that it
	// is 'potentially' visible, barring obstruction, being scrolled or
	// clipped out of the field of view, or having an ancestor container
	// that has not yet made visible. A widget is potentially onscreen if it
	// has both ATSPI_STATE_VISIBLE and ATSPI_STATE_SHOWING. The absence of
	// ATSPI_STATE_VISIBLE and ATSPI_STATE_SHOWING is semantically equivalent to
	// saying that an object is 'hidden'.
	StateVisible
	// StateManagesDescendants indicates that "active-descendant-changed" event
	// is sent when children become 'active' (i.e. are selected or navigated to
	// onscreen). Used to prevent need to enumerate all children in very large
	// containers, like tables. The presence of ATSPI_STATE_MANAGES_DESCENDANTS
	// is an indication to the client that the children should not, and need
	// not, be enumerated by the client. Objects implementing this state are
	// expected to provide relevant state notifications to listening clients,
	// for instance notifications of visibility changes and activation of their
	// contained child objects, without the client having previously requested
	// references to those children.
	StateManagesDescendants
	// StateIndeterminate indicates that a check box or other boolean indicator
	// is in a state other than checked or not checked. This usually means that
	// the boolean value reflected or controlled by the object does not apply
	// consistently to the entire current context. For example, a checkbox for
	// the "Bold" attribute of text may have ATSPI_STATE_INDETERMINATE if the
	// currently selected text contains a mixture of weight attributes. In many
	// cases interacting with a ATSPI_STATE_INDETERMINATE object will cause the
	// context's corresponding boolean attribute to be homogenized, whereupon
	// the object will lose ATSPI_STATE_INDETERMINATE and a corresponding
	// state-changed event will be fired.
	StateIndeterminate
	// StateRequired indicates that user interaction with this object is
	// 'required' from the user, for instance before completing the processing
	// of a form.
	StateRequired
	// StateTruncated indicates that an object's onscreen content is truncated,
	// e.g. a text value in a spreadsheet cell.
	StateTruncated
	// StateAnimated indicates this object's visual representation is dynamic,
	// not static. This state may be applied to an object during an animated
	// 'effect' and be removed from the object once its visual representation
	// becomes static. Some applications, notably content viewers, may not be
	// able to detect all kinds of animated content. Therefore the absence of
	// this state should not be taken as definitive evidence that the object's
	// visual representation is static; this state is advisory.
	StateAnimated
	// StateInvalidEntry: this object has indicated an error condition due to
	// failure of input validation. For instance, a form control may acquire
	// this state in response to invalid or malformed user input.
	StateInvalidEntry
	// StateSupportsAutocompletion: this state indicates that the object in
	// question implements some form of typeahead or pre-selection behavior
	// whereby entering the first character of one or more sub-elements causes
	// those elements to scroll into view or become selected. Subsequent
	// character input may narrow the selection further as long as one or
	// more sub-elements match the string. This state is normally only useful
	// and encountered on objects that implement Selection. In some cases the
	// typeahead behavior may result in full or partial completion of the
	// data in the input field, in which case these input events may trigger
	// text-changed events from the source.
	StateSupportsAutocompletion
	// StateSelectableText: this state indicates that the object in question
	// supports text selection. It should only be exposed on objects which
	// implement the Text interface, in order to distinguish this state from
	// ATSPI_STATE_SELECTABLE, which infers that the object in question is a
	// selectable child of an object which implements Selection. While similar,
	// text selection and subelement selection are distinct operations.
	StateSelectableText
	// StateIsDefault: this state indicates that the object in question is
	// the 'default' interaction object in a dialog, i.e. the one that gets
	// activated if the user presses "Enter" when the dialog is initially
	// posted.
	StateIsDefault
	// StateVisited: this state indicates that the object (typically a
	// hyperlink) has already been activated or invoked, with the result that
	// some backing data has been downloaded or rendered.
	StateVisited
	// StateCheckable indicates this object has the potential to be checked,
	// such as a checkbox or toggle-able table cell. Since: 2.12.
	StateCheckable
	// StateHasPopup indicates that the object has a popup context menu
	// or sub-level menu which may or may not be showing. This means that
	// activation renders conditional content. Note that ordinary tooltips are
	// not considered popups in this context. Since: 2.12.
	StateHasPopup
	// StateReadOnly indicates that an object which is ENABLED and SENSITIVE has
	// a value which can be read, but not modified, by the user. Since: 2.16.
	StateReadOnly
	// StateLastDefined: this value of the enumeration should not be used as a
	// parameter, it indicates the number of items in the StateType enumeration.
	StateLastDefined
)

func marshalStateType(p uintptr) (interface{}, error) {
	return StateType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for StateType.
func (s StateType) String() string {
	switch s {
	case StateInvalid:
		return "Invalid"
	case StateActive:
		return "Active"
	case StateArmed:
		return "Armed"
	case StateBusy:
		return "Busy"
	case StateChecked:
		return "Checked"
	case StateCollapsed:
		return "Collapsed"
	case StateDefunct:
		return "Defunct"
	case StateEditable:
		return "Editable"
	case StateEnabled:
		return "Enabled"
	case StateExpandable:
		return "Expandable"
	case StateExpanded:
		return "Expanded"
	case StateFocusable:
		return "Focusable"
	case StateFocused:
		return "Focused"
	case StateHasTooltip:
		return "HasTooltip"
	case StateHorizontal:
		return "Horizontal"
	case StateIconified:
		return "Iconified"
	case StateModal:
		return "Modal"
	case StateMultiLine:
		return "MultiLine"
	case StateMultiselectable:
		return "Multiselectable"
	case StateOpaque:
		return "Opaque"
	case StatePressed:
		return "Pressed"
	case StateResizable:
		return "Resizable"
	case StateSelectable:
		return "Selectable"
	case StateSelected:
		return "Selected"
	case StateSensitive:
		return "Sensitive"
	case StateShowing:
		return "Showing"
	case StateSingleLine:
		return "SingleLine"
	case StateStale:
		return "Stale"
	case StateTransient:
		return "Transient"
	case StateVertical:
		return "Vertical"
	case StateVisible:
		return "Visible"
	case StateManagesDescendants:
		return "ManagesDescendants"
	case StateIndeterminate:
		return "Indeterminate"
	case StateRequired:
		return "Required"
	case StateTruncated:
		return "Truncated"
	case StateAnimated:
		return "Animated"
	case StateInvalidEntry:
		return "InvalidEntry"
	case StateSupportsAutocompletion:
		return "SupportsAutocompletion"
	case StateSelectableText:
		return "SelectableText"
	case StateIsDefault:
		return "IsDefault"
	case StateVisited:
		return "Visited"
	case StateCheckable:
		return "Checkable"
	case StateHasPopup:
		return "HasPopup"
	case StateReadOnly:
		return "ReadOnly"
	case StateLastDefined:
		return "LastDefined"
	default:
		return fmt.Sprintf("StateType(%d)", s)
	}
}

// TextBoundaryType specifies the boundary conditions determining
// a run of text as returned from #atspi_text_get_text_at_offset,
// #atspi_text_get_text_after_offset, and #atspi_text_get_text_before_offset.
//
// This enumerationis deprecated since 2.9.90 and should not be used. Use
// AtspiTextGranularity with #atspi_text_get_string_at_offset instead.
type TextBoundaryType C.gint

const (
	// TextBoundaryChar instance is bounded by this character only. Start and
	// end offsets differ by one, by definition, for this value.
	TextBoundaryChar TextBoundaryType = iota
	// TextBoundaryWordStart: boundary condition is start of a word; i.e.
	// range is from start of one word to the start of another word.
	TextBoundaryWordStart
	// TextBoundaryWordEnd: boundary condition is the end of a word; i.e.
	// range is from the end of one word to the end of another. Some locales may
	// not distinguish between words and characters or glyphs. In particular,
	// those locales which use wholly or partially ideographic character sets.
	// In these cases, characters may be returned in lieu of multi-character
	// substrings.
	TextBoundaryWordEnd
	// TextBoundarySentenceStart: boundary condition is start of a sentence,
	// as determined by the application. Some locales or character sets may
	// not include explicit sentence delimiters, so this boundary type can not
	// always be honored. Some locales will return lines of text instead of
	// grammatical sentences.
	TextBoundarySentenceStart
	// TextBoundarySentenceEnd: boundary condition is end of a sentence,
	// as determined by the application, including the sentence-delimiting
	// character, for instance '.' Some locales or character sets may not
	// include explicit sentence delimiters, so this boundary type can not
	// always be honored. Some locales will return lines of text instead of
	// grammatical sentences.
	TextBoundarySentenceEnd
	// TextBoundaryLineStart: boundary condition is the start of a line; i.e.
	// range is from start of one line to the start of another. This generally
	// means that an end-of-line character will appear at the end of the range.
	TextBoundaryLineStart
	// TextBoundaryLineEnd: boundary condition is the end of a line; i.e. range
	// is from start of one line to the start of another. This generally means
	// that an end-of-line character will be the first character of the range.
	TextBoundaryLineEnd
)

func marshalTextBoundaryType(p uintptr) (interface{}, error) {
	return TextBoundaryType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for TextBoundaryType.
func (t TextBoundaryType) String() string {
	switch t {
	case TextBoundaryChar:
		return "Char"
	case TextBoundaryWordStart:
		return "WordStart"
	case TextBoundaryWordEnd:
		return "WordEnd"
	case TextBoundarySentenceStart:
		return "SentenceStart"
	case TextBoundarySentenceEnd:
		return "SentenceEnd"
	case TextBoundaryLineStart:
		return "LineStart"
	case TextBoundaryLineEnd:
		return "LineEnd"
	default:
		return fmt.Sprintf("TextBoundaryType(%d)", t)
	}
}

// TextClipType: enumeration used by interface Text to indicate how to treat
// characters intersecting bounding boxes.
type TextClipType C.gint

const (
	// TextClipNone: no characters/glyphs are omitted.
	TextClipNone TextClipType = iota
	// TextClipMin characters/glyphs clipped by the minimum coordinate are
	// omitted.
	TextClipMin
	// TextClipMax characters/glyphs which intersect the maximum coordinate are
	// omitted.
	TextClipMax
	// TextClipBoth: only glyphs falling entirely within the region bounded by
	// min and max are retained.
	TextClipBoth
)

func marshalTextClipType(p uintptr) (interface{}, error) {
	return TextClipType(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for TextClipType.
func (t TextClipType) String() string {
	switch t {
	case TextClipNone:
		return "None"
	case TextClipMin:
		return "Min"
	case TextClipMax:
		return "Max"
	case TextClipBoth:
		return "Both"
	default:
		return fmt.Sprintf("TextClipType(%d)", t)
	}
}

// TextGranularity: text granularity types used for specifying the granularity
// of the region of text we are interested in.
type TextGranularity C.gint

const (
	// TextGranularityChar: granularity is defined by the boundaries between
	// characters (including non-printing characters).
	TextGranularityChar TextGranularity = iota
	// TextGranularityWord: granularity is defined by the boundaries of a word,
	// starting at the beginning of the current word and finishing at the
	// beginning of the following one, if present.
	TextGranularityWord
	// TextGranularitySentence: granularity is defined by the boundaries of a
	// sentence, starting at the beginning of the current sentence and finishing
	// at the beginning of the following one, if present.
	TextGranularitySentence
	// TextGranularityLine: granularity is defined by the boundaries of a line,
	// starting at the beginning of the current line and finishing at the
	// beginning of the following one, if present.
	TextGranularityLine
	// TextGranularityParagraph: granularity is defined by the boundaries of
	// a paragraph, starting at the beginning of the current paragraph and
	// finishing at the beginning of the following one, if present.
	TextGranularityParagraph
)

func marshalTextGranularity(p uintptr) (interface{}, error) {
	return TextGranularity(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for TextGranularity.
func (t TextGranularity) String() string {
	switch t {
	case TextGranularityChar:
		return "Char"
	case TextGranularityWord:
		return "Word"
	case TextGranularitySentence:
		return "Sentence"
	case TextGranularityLine:
		return "Line"
	case TextGranularityParagraph:
		return "Paragraph"
	default:
		return fmt.Sprintf("TextGranularity(%d)", t)
	}
}
