// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeRelation = coreglib.Type(C.atspi_relation_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeRelation, F: marshalRelation},
	})
}

// RelationOverrides contains methods that are overridable.
type RelationOverrides struct {
}

func defaultRelationOverrides(v *Relation) RelationOverrides {
	return RelationOverrides{}
}

// Relation: interface via which non-hierarchical relationships are indicated.
//
// An interface via which non-hierarchical relationships are indicated.
// An instance of this interface represents a "one-to-many" correspondence.
type Relation struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Relation)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*Relation, *RelationClass, RelationOverrides](
		GTypeRelation,
		initRelationClass,
		wrapRelation,
		defaultRelationOverrides,
	)
}

func initRelationClass(gclass unsafe.Pointer, overrides RelationOverrides, classInitFunc func(*RelationClass)) {
	if classInitFunc != nil {
		class := (*RelationClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapRelation(obj *coreglib.Object) *Relation {
	return &Relation{
		Object: obj,
	}
}

func marshalRelation(p uintptr) (interface{}, error) {
	return wrapRelation(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NTargets gets the number of objects which this relationship has as its target
// objects (the subject is the Accessible from which this Relation originated).
//
// The function returns the following values:
//
//   - gint indicating how many target objects which the originating Accessible
//     object has the Relation relationship with.
func (obj *Relation) NTargets() int {
	var _arg0 *C.AtspiRelation // out
	var _cret C.gint           // in

	_arg0 = (*C.AtspiRelation)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_relation_get_n_targets(_arg0)
	runtime.KeepAlive(obj)

	var _gint int // out

	_gint = int(_cret)

	return _gint
}

// RelationType gets the type of relationship represented by an Relation.
//
// The function returns the following values:
//
//   - relationType indicating the type of relation encapsulated in this
//     Relation object.
func (obj *Relation) RelationType() RelationType {
	var _arg0 *C.AtspiRelation    // out
	var _cret C.AtspiRelationType // in

	_arg0 = (*C.AtspiRelation)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_relation_get_relation_type(_arg0)
	runtime.KeepAlive(obj)

	var _relationType RelationType // out

	_relationType = RelationType(_cret)

	return _relationType
}

// Target gets the i-th target of a specified Relation relationship.
//
// The function takes the following parameters:
//
//   - i: (zero-index) #gint indicating which (of possibly several) target is
//     requested.
//
// The function returns the following values:
//
//   - accessible which is the i-th object with which the originating Accessible
//     has relationship specified in the Relation object.
func (obj *Relation) Target(i int) *Accessible {
	var _arg0 *C.AtspiRelation   // out
	var _arg1 C.gint             // out
	var _cret *C.AtspiAccessible // in

	_arg0 = (*C.AtspiRelation)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(i)

	_cret = C.atspi_relation_get_target(_arg0, _arg1)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(i)

	var _accessible *Accessible // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _accessible
}

// RelationClass: instance of this type is always passed by reference.
type RelationClass struct {
	*relationClass
}

// relationClass is the struct that's finalized.
type relationClass struct {
	native *C.AtspiRelationClass
}
