// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeDeviceLegacy = coreglib.Type(C.atspi_device_legacy_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeDeviceLegacy, F: marshalDeviceLegacy},
	})
}

// DeviceLegacyOverrides contains methods that are overridable.
type DeviceLegacyOverrides struct {
}

func defaultDeviceLegacyOverrides(v *DeviceLegacy) DeviceLegacyOverrides {
	return DeviceLegacyOverrides{}
}

type DeviceLegacy struct {
	_ [0]func() // equal guard
	Device
}

var (
	_ coreglib.Objector = (*DeviceLegacy)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*DeviceLegacy, *DeviceLegacyClass, DeviceLegacyOverrides](
		GTypeDeviceLegacy,
		initDeviceLegacyClass,
		wrapDeviceLegacy,
		defaultDeviceLegacyOverrides,
	)
}

func initDeviceLegacyClass(gclass unsafe.Pointer, overrides DeviceLegacyOverrides, classInitFunc func(*DeviceLegacyClass)) {
	if classInitFunc != nil {
		class := (*DeviceLegacyClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapDeviceLegacy(obj *coreglib.Object) *DeviceLegacy {
	return &DeviceLegacy{
		Device: Device{
			Object: obj,
		},
	}
}

func marshalDeviceLegacy(p uintptr) (interface{}, error) {
	return wrapDeviceLegacy(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewDeviceLegacy creates a new DeviceLegacy.
//
// The function returns the following values:
//
//   - deviceLegacy: pointer to a newly-created DeviceLegacy.
func NewDeviceLegacy() *DeviceLegacy {
	var _cret *C.AtspiDeviceLegacy // in

	_cret = C.atspi_device_legacy_new()

	var _deviceLegacy *DeviceLegacy // out

	_deviceLegacy = wrapDeviceLegacy(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _deviceLegacy
}

// DeviceLegacyClass: instance of this type is always passed by reference.
type DeviceLegacyClass struct {
	*deviceLegacyClass
}

// deviceLegacyClass is the struct that's finalized.
type deviceLegacyClass struct {
	native *C.AtspiDeviceLegacyClass
}

func (d *DeviceLegacyClass) ParentClass() *DeviceClass {
	valptr := &d.native.parent_class
	var _v *DeviceClass // out
	_v = (*DeviceClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
