// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeValue = coreglib.Type(C.atspi_value_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeValue, F: marshalValue},
	})
}

// Value: interface supporting a one-dimensional scalar to be modified, or which
// reflects its value.
//
// An interface supporting a one-dimensional scalar to be modified, or which
// reflects its value. If STATE_EDITABLE is not present, the value is treated as
// "read only".
//
// Value wraps an interface. This means the user can get the
// underlying type by calling Cast().
type Value struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Value)(nil)
)

// Valueer describes Value's interface methods.
type Valueer interface {
	coreglib.Objector

	// CurrentValue gets the current value for an Value.
	CurrentValue() (float64, error)
	// MaximumValue gets the maximum allowed value for an Value.
	MaximumValue() (float64, error)
	// MinimumIncrement gets the minimum increment by which an Value can be
	// adjusted.
	MinimumIncrement() (float64, error)
	// MinimumValue gets the minimum allowed value for an Value.
	MinimumValue() (float64, error)
	// Text gets the human readable text alternative associated with the value.
	Text() (string, error)
	// SetCurrentValue sets the current value of an Value.
	SetCurrentValue(newValue float64) error
}

var _ Valueer = (*Value)(nil)

func wrapValue(obj *coreglib.Object) *Value {
	return &Value{
		Object: obj,
	}
}

func marshalValue(p uintptr) (interface{}, error) {
	return wrapValue(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// CurrentValue gets the current value for an Value.
//
// The function returns the following values:
//
//   - gdouble: current value for this object.
func (obj *Value) CurrentValue() (float64, error) {
	var _arg0 *C.AtspiValue // out
	var _cret C.gdouble     // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiValue)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_value_get_current_value(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gdouble float64 // out
	var _goerr error     // out

	_gdouble = float64(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gdouble, _goerr
}

// MaximumValue gets the maximum allowed value for an Value.
//
// The function returns the following values:
//
//   - gdouble: maximum allowed value for this object.
func (obj *Value) MaximumValue() (float64, error) {
	var _arg0 *C.AtspiValue // out
	var _cret C.gdouble     // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiValue)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_value_get_maximum_value(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gdouble float64 // out
	var _goerr error     // out

	_gdouble = float64(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gdouble, _goerr
}

// MinimumIncrement gets the minimum increment by which an Value can be
// adjusted.
//
// The function returns the following values:
//
//   - gdouble: minimum increment by which the value may be changed, or zero if
//     the minimum increment cannot be determined.
func (obj *Value) MinimumIncrement() (float64, error) {
	var _arg0 *C.AtspiValue // out
	var _cret C.gdouble     // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiValue)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_value_get_minimum_increment(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gdouble float64 // out
	var _goerr error     // out

	_gdouble = float64(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gdouble, _goerr
}

// MinimumValue gets the minimum allowed value for an Value.
//
// The function returns the following values:
//
//   - gdouble: minimum allowed value for this object.
func (obj *Value) MinimumValue() (float64, error) {
	var _arg0 *C.AtspiValue // out
	var _cret C.gdouble     // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiValue)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_value_get_minimum_value(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gdouble float64 // out
	var _goerr error     // out

	_gdouble = float64(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gdouble, _goerr
}

// Text gets the human readable text alternative associated with the value.
// text is a newly created string, that must be freed by the caller. Can be NULL
// if no descriptor is available.
func (obj *Value) Text() (string, error) {
	var _arg0 *C.AtspiValue // out
	var _cret *C.gchar      // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiValue)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_value_get_text(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// SetCurrentValue sets the current value of an Value.
//
// The function takes the following parameters:
//
//   - newValue value which is the desired new value of the object.
func (obj *Value) SetCurrentValue(newValue float64) error {
	var _arg0 *C.AtspiValue // out
	var _arg1 C.gdouble     // out
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiValue)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gdouble(newValue)

	C.atspi_value_set_current_value(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(newValue)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}
