// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeDeviceX11 = coreglib.Type(C.atspi_device_x11_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeDeviceX11, F: marshalDeviceX11},
	})
}

// DeviceX11Overrides contains methods that are overridable.
type DeviceX11Overrides struct {
}

func defaultDeviceX11Overrides(v *DeviceX11) DeviceX11Overrides {
	return DeviceX11Overrides{}
}

type DeviceX11 struct {
	_ [0]func() // equal guard
	Device
}

var (
	_ coreglib.Objector = (*DeviceX11)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*DeviceX11, *DeviceX11Class, DeviceX11Overrides](
		GTypeDeviceX11,
		initDeviceX11Class,
		wrapDeviceX11,
		defaultDeviceX11Overrides,
	)
}

func initDeviceX11Class(gclass unsafe.Pointer, overrides DeviceX11Overrides, classInitFunc func(*DeviceX11Class)) {
	if classInitFunc != nil {
		class := (*DeviceX11Class)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapDeviceX11(obj *coreglib.Object) *DeviceX11 {
	return &DeviceX11{
		Device: Device{
			Object: obj,
		},
	}
}

func marshalDeviceX11(p uintptr) (interface{}, error) {
	return wrapDeviceX11(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewDeviceX11 creates a new DeviceX11.
//
// The function returns the following values:
//
//   - deviceX11: pointer to a newly-created DeviceX11.
func NewDeviceX11() *DeviceX11 {
	var _cret *C.AtspiDeviceX11 // in

	_cret = C.atspi_device_x11_new()

	var _deviceX11 *DeviceX11 // out

	_deviceX11 = wrapDeviceX11(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _deviceX11
}

// DeviceX11Class: instance of this type is always passed by reference.
type DeviceX11Class struct {
	*deviceX11Class
}

// deviceX11Class is the struct that's finalized.
type deviceX11Class struct {
	native *C.AtspiDeviceX11Class
}

func (d *DeviceX11Class) ParentClass() *DeviceClass {
	valptr := &d.native.parent_class
	var _v *DeviceClass // out
	_v = (*DeviceClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
