// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
import "C"

//export _gotk4_atspi2_AccessibleClass_mode_changed
func _gotk4_atspi2_AccessibleClass_mode_changed(arg0 *C.AtspiAccessible, arg1 C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[AccessibleOverrides](instance0)
	if overrides.ModeChanged == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected AccessibleOverrides.ModeChanged, got none")
	}

	var _enabled bool // out

	if arg1 != 0 {
		_enabled = true
	}

	overrides.ModeChanged(_enabled)
}

//export _gotk4_atspi2_AccessibleClass_region_changed
func _gotk4_atspi2_AccessibleClass_region_changed(arg0 *C.AtspiAccessible, arg1 C.gint, arg2 C.gint) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[AccessibleOverrides](instance0)
	if overrides.RegionChanged == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected AccessibleOverrides.RegionChanged, got none")
	}

	var _currentOffset int // out
	var _lastOffset int    // out

	_currentOffset = int(arg1)
	_lastOffset = int(arg2)

	overrides.RegionChanged(_currentOffset, _lastOffset)
}

//export _gotk4_atspi2_DeviceListenerClass_device_event
func _gotk4_atspi2_DeviceListenerClass_device_event(arg0 *C.AtspiDeviceListener, arg1 *C.AtspiDeviceEvent) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[DeviceListenerOverrides](instance0)
	if overrides.DeviceEvent == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected DeviceListenerOverrides.DeviceEvent, got none")
	}

	var _event *DeviceEvent // out

	_event = (*DeviceEvent)(gextras.NewStructNative(unsafe.Pointer(arg1)))

	ok := overrides.DeviceEvent(_event)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}
