// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
import "C"

//export _gotk4_atspi2_DeviceListenerCB
func _gotk4_atspi2_DeviceListenerCB(arg1 *C.AtspiDeviceEvent, arg2 *C.void) (cret C.gboolean) {
	var fn DeviceListenerCB
	{
		v := gbox.Get(uintptr(arg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(DeviceListenerCB)
	}

	var _stroke *DeviceEvent // out

	_stroke = (*DeviceEvent)(gextras.NewStructNative(unsafe.Pointer(arg1)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_stroke)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)

	ok := fn(_stroke)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}
