// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	"github.com/diamondburned/gotk4/pkg/glib/v2"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
import "C"

// RoleGetLocalizedName gets the localized description string describing the
// Role role.
//
// The function takes the following parameters:
//
//   - role object to query.
//
// The function returns the following values:
//
//   - utf8: localized string describing the AtspiRole.
func RoleGetLocalizedName(role Role) string {
	var _arg1 C.AtspiRole // out
	var _cret *C.gchar    // in

	_arg1 = C.AtspiRole(role)

	_cret = C.atspi_role_get_localized_name(_arg1)
	runtime.KeepAlive(role)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))

	return _utf8
}

// RoleGetName gets a localizable string that indicates the name of an Role.
//
// The function takes the following parameters:
//
//   - role object to query.
//
// The function returns the following values:
//
//   - utf8: localizable string name for an Role enumerated type.
func RoleGetName(role Role) string {
	var _arg1 C.AtspiRole // out
	var _cret *C.gchar    // in

	_arg1 = C.AtspiRole(role)

	_cret = C.atspi_role_get_name(_arg1)
	runtime.KeepAlive(role)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))

	return _utf8
}

// Exit disconnects from Registry instances and releases any floating resources.
// Call only once at exit.
//
// The function returns the following values:
//
//   - gint: 0 if there were no leaks, otherwise other integer values.
func Exit() int {
	var _cret C.int // in

	_cret = C.atspi_exit()

	var _gint int // out

	_gint = int(_cret)

	return _gint
}

// Init connects to the accessibility registry and initializes the SPI.
//
// The function returns the following values:
//
//   - gint: 0 on success, 1 if already initialized, or an integer error code.
func Init() int {
	var _cret C.int // in

	_cret = C.atspi_init()

	var _gint int // out

	_gint = int(_cret)

	return _gint
}

// IsInitialized indicates whether AT-SPI has been initialized.
//
// The function returns the following values:
//
//   - ok: True if initialized; False otherwise.
func IsInitialized() bool {
	var _cret C.gboolean // in

	_cret = C.atspi_is_initialized()

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// SetMainContext sets the main loop context that AT-SPI should assume is
// in use when setting an idle callback. This function should be called by
// application-side implementors (ie, at-spi2-atk) when it is desirable to
// re-enter the main loop.
//
// The function takes the following parameters:
//
//   - cnx to use.
func SetMainContext(cnx *glib.MainContext) {
	var _arg1 *C.GMainContext // out

	_arg1 = (*C.GMainContext)(gextras.StructNative(unsafe.Pointer(cnx)))

	C.atspi_set_main_context(_arg1)
	runtime.KeepAlive(cnx)
}

// SetTimeout: set the timeout used for method calls. If this is not set
// explicitly, a default of 800 ms is used. Note that at-spi2-registryd
// currently uses a timeout of 3 seconds when sending a keyboard event
// notification. This means that, if an AT makes a call in response to the
// keyboard notification and the application being called does not respond
// before the timeout is reached, at-spi2-registryd will time out on the
// keyboard event notification and pass the key onto the application (ie, reply
// to indicate that the key was not consumed), so this may make it undesirable
// to set a timeout larger than 3 seconds.
//
// By default, the normal timeout is set to 800 ms, and the application startup
// timeout is set to 15 seconds.
//
// The function takes the following parameters:
//
//   - val: timeout value, in milliseconds, or -1 to disable the timeout.
//   - startupTime: amount of time, in milliseconds, to allow to pass before
//     enforcing timeouts on an application. Can be used to prevent timeout
//     exceptions if an application is likely to block for an extended period of
//     time on initialization. -1 can be passed to disable this behavior.
func SetTimeout(val, startupTime int) {
	var _arg1 C.gint // out
	var _arg2 C.gint // out

	_arg1 = C.gint(val)
	_arg2 = C.gint(startupTime)

	C.atspi_set_timeout(_arg1, _arg2)
	runtime.KeepAlive(val)
	runtime.KeepAlive(startupTime)
}

// EventMain starts/enters the main event loop for the AT-SPI services.
//
// NOTE: This method does not return control; it is exited via a call to
// #atspi_event_quit from within an event handler.
func EventMain() {
	C.atspi_event_main()
}

// EventQuit quits the last main event loop for the AT-SPI services, See:
// #atspi_event_main.
func EventQuit() {
	C.atspi_event_quit()
}
