// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeTable = coreglib.Type(C.atspi_table_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeTable, F: marshalTable},
	})
}

// Table: interface used by containers whose data is arranged in a tabular form.
//
// An interface used by containers whose contained data is arranged in a tabular
// (i.e. row-column) form. Tables may resemble a two-dimensional grid, as in a
// spreadsheet, or may feature objects which span multiple rows and/or columns,
// but whose bounds are aligned on a row/column matrix. Objects within tables
// are children of the table object, and they may be referenced either via a
// child index or via a row/column pair. Table 'cells' may implement other
// interfaces, such as Text, Action, Image, and Component, and should do so as
// appropriate to their onscreen presentation and/or behavior.
//
// Table wraps an interface. This means the user can get the
// underlying type by calling Cast().
type Table struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Table)(nil)
)

// Tabler describes Table's interface methods.
type Tabler interface {
	coreglib.Objector

	// AddColumnSelection selects the specified column, adding it to the current
	// column selection.
	AddColumnSelection(column int) error
	// AddRowSelection selects the specified row, adding it to the current row
	// selection.
	AddRowSelection(row int) error
	// AccessibleAt gets the table cell at the specified row and column indices.
	AccessibleAt(row, column int) (*Accessible, error)
	// Caption gets an accessible representation of the caption for an Table.
	Caption() (*Accessible, error)
	// ColumnAtIndex gets the table column index occupied by the child at a
	// particular 1-D child index.
	ColumnAtIndex(index int) (int, error)
	// ColumnDescription gets a text description of a particular table column.
	ColumnDescription(column int) (string, error)
	// ColumnExtentAt gets the number of columns spanned by the table cell
	// at the specific row and column (some tables can have cells which span
	// multiple rows and/or columns).
	ColumnExtentAt(row, column int) (int, error)
	// ColumnHeader gets the header associated with a table column, if
	// available.
	ColumnHeader(column int) (*Accessible, error)
	// IndexAt gets the 1-D child index corresponding to the specified 2-D row
	// and column indices.
	IndexAt(row, column int) (int, error)
	// NColumns gets the number of columns in an Table, exclusive of any columns
	// that are programmatically hidden, but inclusive of columns that may be
	// outside of the current scrolling window or viewport.
	NColumns() (int, error)
	// NRows gets the number of rows in an Table, exclusive of any rows that are
	// programmatically hidden, but inclusive of rows that may be outside of the
	// current scrolling window or viewport.
	NRows() (int, error)
	// NSelectedColumns queries a table to find out how many columns are
	// currently selected.
	NSelectedColumns() (int, error)
	// NSelectedRows: query a table to find out how many rows are currently
	// selected.
	NSelectedRows() (int, error)
	// RowAtIndex gets the table row index occupied by the child at a particular
	// 1-D child index.
	RowAtIndex(index int) (int, error)
	// RowColumnExtentsAtIndex: given a child index, determines the row and
	// column indices and extents, and whether the cell is currently selected.
	RowColumnExtentsAtIndex(index int) (row, col, rowExtents, colExtents int, isSelected bool, goerr error)
	// RowDescription gets a text description of a particular table row.
	RowDescription(row int) (string, error)
	// RowExtentAt gets the number of rows spanned by the table cell at the
	// specific row and column.
	RowExtentAt(row, column int) (int, error)
	// RowHeader gets the header associated with a table row, if available.
	RowHeader(row int) (*Accessible, error)
	// SelectedColumns queries a table for a list of indices of columns which
	// are currently selected.
	SelectedColumns() ([]int, error)
	// SelectedRows queries a table for a list of indices of rows which are
	// currently selected.
	SelectedRows() ([]int, error)
	// Summary gets an accessible object which summarizes the contents of an
	// Table.
	Summary() (*Accessible, error)
	// IsColumnSelected determines whether specified table column is selected.
	IsColumnSelected(column int) error
	// IsRowSelected determines whether a table row is selected.
	IsRowSelected(row int) error
	// IsSelected determines whether the cell at a specific row and column is
	// selected.
	IsSelected(row, column int) error
	// RemoveColumnSelection de-selects the specified column, removing it from
	// the current column selection.
	RemoveColumnSelection(column int) error
	// RemoveRowSelection de-selects the specified row, removing it from the
	// current row selection.
	RemoveRowSelection(row int) error
}

var _ Tabler = (*Table)(nil)

func wrapTable(obj *coreglib.Object) *Table {
	return &Table{
		Object: obj,
	}
}

func marshalTable(p uintptr) (interface{}, error) {
	return wrapTable(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// AddColumnSelection selects the specified column, adding it to the current
// column selection. Not all tables support column selection.
//
// The function takes the following parameters:
//
//   - column: zero-indexed column number of the column being selected.
func (obj *Table) AddColumnSelection(column int) error {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(column)

	C.atspi_table_add_column_selection(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(column)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// AddRowSelection selects the specified row, adding it to the current row
// selection. Not all tables support row selection.
//
// The function takes the following parameters:
//
//   - row: zero-indexed row number of the row being selected.
func (obj *Table) AddRowSelection(row int) error {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(row)

	C.atspi_table_add_row_selection(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(row)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// AccessibleAt gets the table cell at the specified row and column indices.
// To get the accessible object at a particular (x, y) screen coordinate,
// use #atspi_component_get_accessible_at_point.
//
// The function takes the following parameters:
//
//   - row: specified table row, zero-indexed.
//   - column: specified table column, zero-indexed.
//
// The function returns the following values:
//
//   - accessible object representing the specified table cell.
func (obj *Table) AccessibleAt(row, column int) (*Accessible, error) {
	var _arg0 *C.AtspiTable      // out
	var _arg1 C.gint             // out
	var _arg2 C.gint             // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(row)
	_arg2 = C.gint(column)

	_cret = C.atspi_table_get_accessible_at(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(row)
	runtime.KeepAlive(column)

	var _accessible *Accessible // out
	var _goerr error            // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// Caption gets an accessible representation of the caption for an Table.
//
// The function returns the following values:
//
//   - accessible object that serves as the table's caption.
func (obj *Table) Caption() (*Accessible, error) {
	var _arg0 *C.AtspiTable      // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_get_caption(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _accessible *Accessible // out
	var _goerr error            // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// ColumnAtIndex gets the table column index occupied by the child at a
// particular 1-D child index.
//
// see #atspi_table_get_index_at, #atspi_table_get_row_at_index.
//
// The function takes the following parameters:
//
//   - index: specified child index, zero-indexed.
//
// The function returns the following values:
//
//   - gint indicating the first column spanned by the child of a table,
//     at the specified 1-D (zero-offset) index.
func (obj *Table) ColumnAtIndex(index int) (int, error) {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _cret C.gint        // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(index)

	_cret = C.atspi_table_get_column_at_index(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(index)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// ColumnDescription gets a text description of a particular table column. This
// differs from #atspi_table_get_column_header, which returns an #Accessible.
//
// The function takes the following parameters:
//
//   - column: specified table column, zero-indexed.
//
// The function returns the following values:
//
//   - utf8: UTF-8 string describing the specified table column, if available.
func (obj *Table) ColumnDescription(column int) (string, error) {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _cret *C.gchar      // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(column)

	_cret = C.atspi_table_get_column_description(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(column)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// ColumnExtentAt gets the number of columns spanned by the table cell at the
// specific row and column (some tables can have cells which span multiple rows
// and/or columns). The returned values are meaningful only if the Table has
// both STATE_VISIBLE and STATE_SHOWING.
//
// The function takes the following parameters:
//
//   - row: specified table row, zero-indexed.
//   - column: specified table column, zero-indexed.
//
// The function returns the following values:
//
//   - gint indicating the number of columns spanned by the specified cell.
func (obj *Table) ColumnExtentAt(row, column int) (int, error) {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _arg2 C.gint        // out
	var _cret C.gint        // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(row)
	_arg2 = C.gint(column)

	_cret = C.atspi_table_get_column_extent_at(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(row)
	runtime.KeepAlive(column)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// ColumnHeader gets the header associated with a table column, if available.
// This differs from #atspi_table_get_column_description, which returns a
// string.
//
// The function takes the following parameters:
//
//   - column: specified table column, zero-indexed.
//
// The function returns the following values:
//
//   - accessible representation of the specified table column, if available.
func (obj *Table) ColumnHeader(column int) (*Accessible, error) {
	var _arg0 *C.AtspiTable      // out
	var _arg1 C.gint             // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(column)

	_cret = C.atspi_table_get_column_header(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(column)

	var _accessible *Accessible // out
	var _goerr error            // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// IndexAt gets the 1-D child index corresponding to the specified 2-D row and
// column indices. To get the accessible object at a particular (x, y) screen
// coordinate, use #atspi_component_get_accessible_at_point.
//
// see #atspi_table_get_row_at_index, #atspi_table_get_column_at_index.
//
// The function takes the following parameters:
//
//   - row: specified table row, zero-indexed.
//   - column: specified table column, zero-indexed.
//
// The function returns the following values:
//
//   - gint which serves as the index of a specified cell in the table, in a
//     form usable by #atspi_get_child_at_index.
func (obj *Table) IndexAt(row, column int) (int, error) {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _arg2 C.gint        // out
	var _cret C.gint        // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(row)
	_arg2 = C.gint(column)

	_cret = C.atspi_table_get_index_at(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(row)
	runtime.KeepAlive(column)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// NColumns gets the number of columns in an Table, exclusive of any columns
// that are programmatically hidden, but inclusive of columns that may be
// outside of the current scrolling window or viewport.
//
// The function returns the following values:
//
//   - gint indicating the number of columns in the table.
func (obj *Table) NColumns() (int, error) {
	var _arg0 *C.AtspiTable // out
	var _cret C.gint        // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_get_n_columns(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// NRows gets the number of rows in an Table, exclusive of any rows that are
// programmatically hidden, but inclusive of rows that may be outside of the
// current scrolling window or viewport.
//
// The function returns the following values:
//
//   - gint indicating the number of rows in the table.
func (obj *Table) NRows() (int, error) {
	var _arg0 *C.AtspiTable // out
	var _cret C.gint        // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_get_n_rows(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// NSelectedColumns queries a table to find out how many columns are currently
// selected. Not all tables support column selection.
//
// The function returns the following values:
//
//   - gint indicating the number of columns currently selected.
func (obj *Table) NSelectedColumns() (int, error) {
	var _arg0 *C.AtspiTable // out
	var _cret C.gint        // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_get_n_selected_columns(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// NSelectedRows: query a table to find out how many rows are currently
// selected. Not all tables support row selection.
//
// The function returns the following values:
//
//   - gint indicating the number of rows currently selected.
func (obj *Table) NSelectedRows() (int, error) {
	var _arg0 *C.AtspiTable // out
	var _cret C.gint        // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_get_n_selected_rows(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// RowAtIndex gets the table row index occupied by the child at a particular 1-D
// child index.
//
// see #atspi_table_get_index_at, #atspi_table_get_column_at_index.
//
// The function takes the following parameters:
//
//   - index: specified child index, zero-indexed.
//
// The function returns the following values:
//
//   - gint indicating the first row spanned by the child of a table, at the
//     specified 1-D (zero-offset) index.
func (obj *Table) RowAtIndex(index int) (int, error) {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _cret C.gint        // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(index)

	_cret = C.atspi_table_get_row_at_index(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(index)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// RowColumnExtentsAtIndex: given a child index, determines the row and column
// indices and extents, and whether the cell is currently selected. If the child
// at index is not a cell (for instance, if it is a summary, caption, etc.),
// LSE is returned. The returned values are meaningful only if the Table has
// both STATE_VISIBLE and STATE_SHOWING.
//
// Example: If the Table child at index '6' extends across columns 5 and 6 of
// row 2 of an Table instance, and is currently selected, then
//
// retval = atspi_table_get_row_column_extents_at_index (table, 6, row, col,
// row_extents, col_extents, is_selected);
//
// will return UE, and after the call row, col, row_extents, col_extents,
// and is_selected will contain 2, 5, 1, 2, and UE, respectively.
//
// The function takes the following parameters:
//
//   - index of the Table child whose row/column extents are requested.
//
// The function returns the following values:
//
//   - row: back-filled with the first table row associated with the cell with
//     child index.
//   - col: back-filled with the first table column associated with the cell
//     with child index.
//   - rowExtents: back-filled with the number of table rows across which child
//     i extends.
//   - colExtents: back-filled with the number of table columns across which
//     child i extends.
//   - isSelected: boolean which is back-filled with UE if the child at index i
//     corresponds to a selected table cell, LSE otherwise.
func (obj *Table) RowColumnExtentsAtIndex(index int) (row, col, rowExtents, colExtents int, isSelected bool, goerr error) {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _arg2 C.gint        // in
	var _arg3 C.gint        // in
	var _arg4 C.gint        // in
	var _arg5 C.gint        // in
	var _arg6 C.gboolean    // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(index)

	C.atspi_table_get_row_column_extents_at_index(_arg0, _arg1, &_arg2, &_arg3, &_arg4, &_arg5, &_arg6, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(index)

	var _row int         // out
	var _col int         // out
	var _rowExtents int  // out
	var _colExtents int  // out
	var _isSelected bool // out
	var _goerr error     // out

	_row = int(_arg2)
	_col = int(_arg3)
	_rowExtents = int(_arg4)
	_colExtents = int(_arg5)
	if _arg6 != 0 {
		_isSelected = true
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _row, _col, _rowExtents, _colExtents, _isSelected, _goerr
}

// RowDescription gets a text description of a particular table row. This
// differs from #atspi_table_get_row_header, which returns an Accessible.
//
// The function takes the following parameters:
//
//   - row: specified table row, zero-indexed.
//
// The function returns the following values:
//
//   - utf8: UTF-8 string describing the specified table row, if available.
func (obj *Table) RowDescription(row int) (string, error) {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _cret *C.gchar      // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(row)

	_cret = C.atspi_table_get_row_description(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(row)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// RowExtentAt gets the number of rows spanned by the table cell at the specific
// row and column. (some tables can have cells which span multiple rows and/or
// columns). The returned values are meaningful only if the Table has both
// STATE_VISIBLE and STATE_SHOWING.
//
// The function takes the following parameters:
//
//   - row: specified table row, zero-indexed.
//   - column: specified table column, zero-indexed.
//
// The function returns the following values:
//
//   - gint indicating the number of rows spanned by the specified cell.
func (obj *Table) RowExtentAt(row, column int) (int, error) {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _arg2 C.gint        // out
	var _cret C.gint        // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(row)
	_arg2 = C.gint(column)

	_cret = C.atspi_table_get_row_extent_at(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(row)
	runtime.KeepAlive(column)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// RowHeader gets the header associated with a table row, if available. This
// differs from #atspi_table_get_row_description, which returns a string.
//
// The function takes the following parameters:
//
//   - row: specified table row, zero-indexed.
//
// The function returns the following values:
//
//   - accessible representation of the specified table row, if available.
func (obj *Table) RowHeader(row int) (*Accessible, error) {
	var _arg0 *C.AtspiTable      // out
	var _arg1 C.gint             // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(row)

	_cret = C.atspi_table_get_row_header(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(row)

	var _accessible *Accessible // out
	var _goerr error            // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// SelectedColumns queries a table for a list of indices of columns which are
// currently selected.
//
// The function returns the following values:
//
//   - gints: array of #gint values, specifying which columns are currently
//     selected.
func (obj *Table) SelectedColumns() ([]int, error) {
	var _arg0 *C.AtspiTable // out
	var _cret *C.GArray     // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_get_selected_columns(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gints []int // out
	var _goerr error // out

	{
		var len uintptr
		p := C.g_array_steal(&_cret, (*C.gsize)(&len))
		src := unsafe.Slice((*C.GArray)(p), len)
		_gints = make([]int, len)
		for i := 0; i < len; i++ {
			_gints[i] = int(src[i])
		}
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gints, _goerr
}

// SelectedRows queries a table for a list of indices of rows which are
// currently selected.
//
// The function returns the following values:
//
//   - gints: array of #gint values, specifying which rows are currently
//     selected.
func (obj *Table) SelectedRows() ([]int, error) {
	var _arg0 *C.AtspiTable // out
	var _cret *C.GArray     // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_get_selected_rows(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gints []int // out
	var _goerr error // out

	{
		var len uintptr
		p := C.g_array_steal(&_cret, (*C.gsize)(&len))
		src := unsafe.Slice((*C.GArray)(p), len)
		_gints = make([]int, len)
		for i := 0; i < len; i++ {
			_gints[i] = int(src[i])
		}
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gints, _goerr
}

// Summary gets an accessible object which summarizes the contents of an Table.
//
// The function returns the following values:
//
//   - accessible object that serves as the table's summary (often a reduced
//     Table).
func (obj *Table) Summary() (*Accessible, error) {
	var _arg0 *C.AtspiTable      // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_table_get_summary(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _accessible *Accessible // out
	var _goerr error            // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// IsColumnSelected determines whether specified table column is selected.
// Not all tables support column selection.
//
// The function takes the following parameters:
//
//   - column: zero-indexed column number of the column being queried.
func (obj *Table) IsColumnSelected(column int) error {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(column)

	C.atspi_table_is_column_selected(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(column)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// IsRowSelected determines whether a table row is selected. Not all tables
// support row selection.
//
// The function takes the following parameters:
//
//   - row: zero-indexed row number of the row being queried.
func (obj *Table) IsRowSelected(row int) error {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(row)

	C.atspi_table_is_row_selected(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(row)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// IsSelected determines whether the cell at a specific row and column is
// selected.
//
// The function takes the following parameters:
//
//   - row: zero-indexed row of the cell being queried.
//   - column: zero-indexed column of the cell being queried.
func (obj *Table) IsSelected(row, column int) error {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _arg2 C.gint        // out
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(row)
	_arg2 = C.gint(column)

	C.atspi_table_is_selected(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(row)
	runtime.KeepAlive(column)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// RemoveColumnSelection de-selects the specified column, removing it from the
// current column selection. Not all tables support column selection.
//
// The function takes the following parameters:
//
//   - column: zero-indexed column number of the column being de-selected.
func (obj *Table) RemoveColumnSelection(column int) error {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(column)

	C.atspi_table_remove_column_selection(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(column)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// RemoveRowSelection de-selects the specified row, removing it from the current
// row selection. Not all tables support row selection.
//
// The function takes the following parameters:
//
//   - row: zero-indexed number of the row being de-selected.
func (obj *Table) RemoveRowSelection(row int) error {
	var _arg0 *C.AtspiTable // out
	var _arg1 C.gint        // out
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiTable)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(row)

	C.atspi_table_remove_row_selection(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(row)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}
