// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeSelection = coreglib.Type(C.atspi_selection_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeSelection, F: marshalSelection},
	})
}

// Selection: interface which indicates that an object exposes a 'selection'
// model, allowing the selection of one or more of its children.
//
// An interface which indicates that an object exposes a 'selection' model,
// allowing the selection of one or more of its children. Read-only
// Selection instances are possible, in which case the interface is used to
// programmatically determine the selected-ness of its children.
//
// Selection wraps an interface. This means the user can get the
// underlying type by calling Cast().
type Selection struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Selection)(nil)
)

// Selectioner describes Selection's interface methods.
type Selectioner interface {
	coreglib.Objector

	// ClearSelection clears the current selection, removing all selected
	// children from the specified Selection implementor's selection list.
	ClearSelection() error
	// DeselectChild deselects a specific child of an Selection.
	DeselectChild(childIndex int) error
	// DeselectSelectedChild removes a child from the selected children list of
	// an Selection.
	DeselectSelectedChild(selectedChildIndex int) error
	// NSelectedChildren gets the number of children of an Selection implementor
	// which are currently selected.
	NSelectedChildren() (int, error)
	// SelectedChild gets the i-th selected Accessible child of an Selection.
	SelectedChild(selectedChildIndex int) (*Accessible, error)
	// IsChildSelected determines whether a particular child of an Selection
	// implementor is currently selected.
	IsChildSelected(childIndex int) error
	// SelectAll attempts to select all of the children of an Selection
	// implementor.
	SelectAll() error
	// SelectChild adds a child to the selected children list of an Selection.
	SelectChild(childIndex int) error
}

var _ Selectioner = (*Selection)(nil)

func wrapSelection(obj *coreglib.Object) *Selection {
	return &Selection{
		Object: obj,
	}
}

func marshalSelection(p uintptr) (interface{}, error) {
	return wrapSelection(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// ClearSelection clears the current selection, removing all selected children
// from the specified Selection implementor's selection list.
func (obj *Selection) ClearSelection() error {
	var _arg0 *C.AtspiSelection // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiSelection)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	C.atspi_selection_clear_selection(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// DeselectChild deselects a specific child of an Selection. Note that
// child_index is the index of the child in the parent container.
//
// See #atspi_selection_deselect_selected_child.
//
// The function takes the following parameters:
//
//   - childIndex indicating which of the children of the Accessible is to be
//     de-selected.
func (obj *Selection) DeselectChild(childIndex int) error {
	var _arg0 *C.AtspiSelection // out
	var _arg1 C.gint            // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiSelection)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(childIndex)

	C.atspi_selection_deselect_child(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(childIndex)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// DeselectSelectedChild removes a child from the selected children list of an
// Selection. Note that child_index is the index in the selected-children list,
// not the index in the parent container. selectedChildIndex in this method,
// and child_index in #atspi_selection_select_child are asymmetric.
//
// The function takes the following parameters:
//
//   - selectedChildIndex indicating which of the selected children of the
//     #Accessible is to be selected.
func (obj *Selection) DeselectSelectedChild(selectedChildIndex int) error {
	var _arg0 *C.AtspiSelection // out
	var _arg1 C.gint            // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiSelection)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(selectedChildIndex)

	C.atspi_selection_deselect_selected_child(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(selectedChildIndex)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// NSelectedChildren gets the number of children of an Selection implementor
// which are currently selected.
//
// The function returns the following values:
//
//   - gint indicating the number of #Accessible children of the Selection
//     implementor which are currently selected.
func (obj *Selection) NSelectedChildren() (int, error) {
	var _arg0 *C.AtspiSelection // out
	var _cret C.gint            // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiSelection)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_selection_get_n_selected_children(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// SelectedChild gets the i-th selected Accessible child of an
// Selection. Note that selected_child_index refers to the index
// in the list of 'selected' children and generally differs from
// that used in #atspi_accessible_get_child_at_index or returned by
// #atspi_accessible_get_index_in_parent. selected_child_index must lie between
// 0 and #atspi_selection_get_n_selected_children - 1, inclusive.
//
// The function takes the following parameters:
//
//   - selectedChildIndex indicating which of the selected children is
//     specified.
//
// The function returns the following values:
//
//   - accessible: pointer to a selected Accessible child object, specified by
//     selected_child_index.
func (obj *Selection) SelectedChild(selectedChildIndex int) (*Accessible, error) {
	var _arg0 *C.AtspiSelection  // out
	var _arg1 C.gint             // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiSelection)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(selectedChildIndex)

	_cret = C.atspi_selection_get_selected_child(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(selectedChildIndex)

	var _accessible *Accessible // out
	var _goerr error            // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// IsChildSelected determines whether a particular child of an Selection
// implementor is currently selected. Note that child_index is the index into
// the standard Accessible container's list of children.
//
// The function takes the following parameters:
//
//   - childIndex: index into the Selection's list of children.
func (obj *Selection) IsChildSelected(childIndex int) error {
	var _arg0 *C.AtspiSelection // out
	var _arg1 C.gint            // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiSelection)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(childIndex)

	C.atspi_selection_is_child_selected(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(childIndex)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// SelectAll attempts to select all of the children of an Selection implementor.
// Not all Selection implementors support this operation.
func (obj *Selection) SelectAll() error {
	var _arg0 *C.AtspiSelection // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiSelection)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	C.atspi_selection_select_all(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// SelectChild adds a child to the selected children list of an Selection. For
// Selection implementors that only allow single selections, this may replace
// the (single) current selection.
//
// The function takes the following parameters:
//
//   - childIndex indicating which child of the #Accessible is to be selected.
func (obj *Selection) SelectChild(childIndex int) error {
	var _arg0 *C.AtspiSelection // out
	var _arg1 C.gint            // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiSelection)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(childIndex)

	C.atspi_selection_select_child(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(childIndex)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}
