// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeAtspiObject = coreglib.Type(C.atspi_object_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeAtspiObject, F: marshalAtspiObject},
	})
}

// AtspiObjectOverrides contains methods that are overridable.
type AtspiObjectOverrides struct {
}

func defaultAtspiObjectOverrides(v *AtspiObject) AtspiObjectOverrides {
	return AtspiObjectOverrides{}
}

type AtspiObject struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*AtspiObject)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*AtspiObject, *ObjectClass, AtspiObjectOverrides](
		GTypeAtspiObject,
		initObjectClass,
		wrapObject,
		defaultAtspiObjectOverrides,
	)
}

func initObjectClass(gclass unsafe.Pointer, overrides AtspiObjectOverrides, classInitFunc func(*ObjectClass)) {
	if classInitFunc != nil {
		class := (*ObjectClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapObject(obj *coreglib.Object) *AtspiObject {
	return &AtspiObject{
		Object: obj,
	}
}

func marshalAtspiObject(p uintptr) (interface{}, error) {
	return wrapObject(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// ObjectClass: instance of this type is always passed by reference.
type ObjectClass struct {
	*objectClass
}

// objectClass is the struct that's finalized.
type objectClass struct {
	native *C.AtspiObjectClass
}
