// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"fmt"
	"strings"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeKeyListenerSyncType = coreglib.Type(C.atspi_key_listener_sync_type_get_type())
	GTypeDeviceEvent         = coreglib.Type(C.atspi_device_event_get_type())
	GTypeEvent               = coreglib.Type(C.atspi_event_get_type())
	GTypeKeyDefinition       = coreglib.Type(C.atspi_key_definition_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeKeyListenerSyncType, F: marshalKeyListenerSyncType},
		coreglib.TypeMarshaler{T: GTypeDeviceEvent, F: marshalDeviceEvent},
		coreglib.TypeMarshaler{T: GTypeEvent, F: marshalEvent},
		coreglib.TypeMarshaler{T: GTypeKeyDefinition, F: marshalKeyDefinition},
	})
}

type ControllerEventMask = uint

type DeviceEventMask = uint

type KeyEventMask = uint

type KeyMaskType = uint

// KeyListenerSyncType specifies the type of a key listener event. The values
// above can and should be bitwise-'OR'-ed together, observing the compatibility
// limitations specified in the description of each value. For instance,
// SPI_KEYLISTENER_ALL_WINDOWS | SPI_KEYLISTENER_CANCONSUME is a commonly used
// combination which gives the AT complete control over the delivery of matching
// events. However, such filters should be used sparingly as they may have a
// negative impact on system performance.
type KeyListenerSyncType C.guint

const (
	// KeylistenerNosync events may be delivered asynchronously, which means in
	// some cases they may already have been delivered to the application before
	// the AT client receives the notification.
	KeylistenerNosync KeyListenerSyncType = 0b0
	// KeylistenerSynchronous events are delivered synchronously, before the
	// currently focused application sees them.
	KeylistenerSynchronous KeyListenerSyncType = 0b1
	// KeylistenerCanconsume events may be consumed by the AT client.
	// Presumes and requires SPI_KEYLISTENER_SYNCHRONOUS, incompatible with
	// SPI_KEYLISTENER_NOSYNC.
	KeylistenerCanconsume KeyListenerSyncType = 0b10
	// KeylistenerAllWindows events are received not from the application
	// toolkit layer, but from the device driver or windowing system subsystem;
	// such notifications are 'global' in the sense that they are not broken or
	// defeated by applications that participate poorly in the accessibility
	// APIs, or not at all; however because of the intrusive nature of
	// such snooping, it can have side-effects on certain older platforms.
	// If unconditional event notifications, even when inaccessible or "broken"
	// applications have focus, are not required, it may be best to avoid this
	// enum value/flag.
	KeylistenerAllWindows KeyListenerSyncType = 0b100
)

func marshalKeyListenerSyncType(p uintptr) (interface{}, error) {
	return KeyListenerSyncType(coreglib.ValueFromNative(unsafe.Pointer(p)).Flags()), nil
}

// String returns the names in string for KeyListenerSyncType.
func (k KeyListenerSyncType) String() string {
	if k == 0 {
		return "KeyListenerSyncType(0)"
	}

	var builder strings.Builder
	builder.Grow(84)

	for k != 0 {
		next := k & (k - 1)
		bit := k - next

		switch bit {
		case KeylistenerNosync:
			builder.WriteString("Nosync|")
		case KeylistenerSynchronous:
			builder.WriteString("Synchronous|")
		case KeylistenerCanconsume:
			builder.WriteString("Canconsume|")
		case KeylistenerAllWindows:
			builder.WriteString("AllWindows|")
		default:
			builder.WriteString(fmt.Sprintf("KeyListenerSyncType(0b%b)|", bit))
		}

		k = next
	}

	return strings.TrimSuffix(builder.String(), "|")
}

// Has returns true if k contains other.
func (k KeyListenerSyncType) Has(other KeyListenerSyncType) bool {
	return (k & other) == other
}

// DeviceEvent: instance of this type is always passed by reference.
type DeviceEvent struct {
	*deviceEvent
}

// deviceEvent is the struct that's finalized.
type deviceEvent struct {
	native *C.AtspiDeviceEvent
}

func marshalDeviceEvent(p uintptr) (interface{}, error) {
	b := coreglib.ValueFromNative(unsafe.Pointer(p)).Boxed()
	return &DeviceEvent{&deviceEvent{(*C.AtspiDeviceEvent)(b)}}, nil
}

func (d *DeviceEvent) Type() EventType {
	valptr := &d.native._type
	var _v EventType // out
	_v = EventType(*valptr)
	return _v
}

func (d *DeviceEvent) ID() uint {
	valptr := &d.native.id
	var _v uint // out
	_v = uint(*valptr)
	return _v
}

func (d *DeviceEvent) HwCode() uint16 {
	valptr := &d.native.hw_code
	var _v uint16 // out
	_v = uint16(*valptr)
	return _v
}

func (d *DeviceEvent) Modifiers() uint16 {
	valptr := &d.native.modifiers
	var _v uint16 // out
	_v = uint16(*valptr)
	return _v
}

func (d *DeviceEvent) Timestamp() uint {
	valptr := &d.native.timestamp
	var _v uint // out
	_v = uint(*valptr)
	return _v
}

func (d *DeviceEvent) EventString() string {
	valptr := &d.native.event_string
	var _v string // out
	_v = C.GoString((*C.gchar)(unsafe.Pointer(*valptr)))
	return _v
}

func (d *DeviceEvent) IsText() bool {
	valptr := &d.native.is_text
	var _v bool // out
	if *valptr != 0 {
		_v = true
	}
	return _v
}

func (d *DeviceEvent) SetID(id uint) {
	valptr := &d.native.id
	*valptr = C.guint(id)
}

func (d *DeviceEvent) SetHwCode(hwCode uint16) {
	valptr := &d.native.hw_code
	*valptr = C.gushort(hwCode)
}

func (d *DeviceEvent) SetModifiers(modifiers uint16) {
	valptr := &d.native.modifiers
	*valptr = C.gushort(modifiers)
}

func (d *DeviceEvent) SetTimestamp(timestamp uint) {
	valptr := &d.native.timestamp
	*valptr = C.guint(timestamp)
}

func (d *DeviceEvent) SetIsText(isText bool) {
	valptr := &d.native.is_text
	if isText {
		*valptr = C.TRUE
	}
}

// Event: instance of this type is always passed by reference.
type Event struct {
	*event
}

// event is the struct that's finalized.
type event struct {
	native *C.AtspiEvent
}

func marshalEvent(p uintptr) (interface{}, error) {
	b := coreglib.ValueFromNative(unsafe.Pointer(p)).Boxed()
	return &Event{&event{(*C.AtspiEvent)(b)}}, nil
}

func (e *Event) Type() string {
	valptr := &e.native._type
	var _v string // out
	_v = C.GoString((*C.gchar)(unsafe.Pointer(*valptr)))
	return _v
}

func (e *Event) Source() *Accessible {
	valptr := &e.native.source
	var _v *Accessible // out
	_v = wrapAccessible(coreglib.Take(unsafe.Pointer(*valptr)))
	return _v
}

func (e *Event) Detail1() int {
	valptr := &e.native.detail1
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (e *Event) Detail2() int {
	valptr := &e.native.detail2
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (e *Event) Sender() *Accessible {
	valptr := &e.native.sender
	var _v *Accessible // out
	_v = wrapAccessible(coreglib.Take(unsafe.Pointer(*valptr)))
	return _v
}

func (e *Event) SetDetail1(detail1 int) {
	valptr := &e.native.detail1
	*valptr = C.gint(detail1)
}

func (e *Event) SetDetail2(detail2 int) {
	valptr := &e.native.detail2
	*valptr = C.gint(detail2)
}

// EventListenerMode: instance of this type is always passed by reference.
type EventListenerMode struct {
	*eventListenerMode
}

// eventListenerMode is the struct that's finalized.
type eventListenerMode struct {
	native *C.AtspiEventListenerMode
}

// NewEventListenerMode creates a new EventListenerMode instance from the given
// fields. Beware that this function allocates on the Go heap; be careful
// when using it!
func NewEventListenerMode(synchronous, preemptive, global bool) EventListenerMode {
	var f0 C.gboolean // out
	if synchronous {
		f0 = C.TRUE
	}
	var f1 C.gboolean // out
	if preemptive {
		f1 = C.TRUE
	}
	var f2 C.gboolean // out
	if global {
		f2 = C.TRUE
	}

	v := C.AtspiEventListenerMode{
		synchronous: f0,
		preemptive:  f1,
		global:      f2,
	}

	return *(*EventListenerMode)(gextras.NewStructNative(unsafe.Pointer(&v)))
}

func (e *EventListenerMode) Synchronous() bool {
	valptr := &e.native.synchronous
	var _v bool // out
	if *valptr != 0 {
		_v = true
	}
	return _v
}

func (e *EventListenerMode) Preemptive() bool {
	valptr := &e.native.preemptive
	var _v bool // out
	if *valptr != 0 {
		_v = true
	}
	return _v
}

func (e *EventListenerMode) Global() bool {
	valptr := &e.native.global
	var _v bool // out
	if *valptr != 0 {
		_v = true
	}
	return _v
}

func (e *EventListenerMode) SetSynchronous(synchronous bool) {
	valptr := &e.native.synchronous
	if synchronous {
		*valptr = C.TRUE
	}
}

func (e *EventListenerMode) SetPreemptive(preemptive bool) {
	valptr := &e.native.preemptive
	if preemptive {
		*valptr = C.TRUE
	}
}

func (e *EventListenerMode) SetGlobal(global bool) {
	valptr := &e.native.global
	if global {
		*valptr = C.TRUE
	}
}

// KeyDefinition: instance of this type is always passed by reference.
type KeyDefinition struct {
	*keyDefinition
}

// keyDefinition is the struct that's finalized.
type keyDefinition struct {
	native *C.AtspiKeyDefinition
}

func marshalKeyDefinition(p uintptr) (interface{}, error) {
	b := coreglib.ValueFromNative(unsafe.Pointer(p)).Boxed()
	return &KeyDefinition{&keyDefinition{(*C.AtspiKeyDefinition)(b)}}, nil
}

func (k *KeyDefinition) Keycode() int {
	valptr := &k.native.keycode
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (k *KeyDefinition) Keysym() int {
	valptr := &k.native.keysym
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (k *KeyDefinition) Keystring() string {
	valptr := &k.native.keystring
	var _v string // out
	_v = C.GoString((*C.gchar)(unsafe.Pointer(*valptr)))
	return _v
}

func (k *KeyDefinition) Modifiers() uint {
	valptr := &k.native.modifiers
	var _v uint // out
	_v = uint(*valptr)
	return _v
}

func (k *KeyDefinition) SetKeycode(keycode int) {
	valptr := &k.native.keycode
	*valptr = C.gint(keycode)
}

func (k *KeyDefinition) SetKeysym(keysym int) {
	valptr := &k.native.keysym
	*valptr = C.gint(keysym)
}

func (k *KeyDefinition) SetModifiers(modifiers uint) {
	valptr := &k.native.modifiers
	*valptr = C.guint(modifiers)
}

// KeySet: structure containing identifying information about a set of keycode
// or keysyms.
//
// An instance of this type is always passed by reference.
type KeySet struct {
	*keySet
}

// keySet is the struct that's finalized.
type keySet struct {
	native *C.AtspiKeySet
}
