// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
// extern void _gotk4_atspi2_Accessible_ConnectRegionChanged(gpointer, gint, gint, guintptr);
// extern void _gotk4_atspi2_Accessible_ConnectModeChanged(gpointer, gint, gchar*, guintptr);
// extern void _gotk4_atspi2_AccessibleClass_region_changed(AtspiAccessible*, gint, gint);
// extern void _gotk4_atspi2_AccessibleClass_mode_changed(AtspiAccessible*, gboolean);
// void _gotk4_atspi2_Accessible_virtual_mode_changed(void* fnptr, AtspiAccessible* arg0, gboolean arg1) {
//   ((void (*)(AtspiAccessible*, gboolean))(fnptr))(arg0, arg1);
// };
// void _gotk4_atspi2_Accessible_virtual_region_changed(void* fnptr, AtspiAccessible* arg0, gint arg1, gint arg2) {
//   ((void (*)(AtspiAccessible*, gint, gint))(fnptr))(arg0, arg1, arg2);
// };
import "C"

// GType values.
var (
	GTypeAccessible = coreglib.Type(C.atspi_accessible_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeAccessible, F: marshalAccessible},
	})
}

// AccessibleOverrides contains methods that are overridable.
type AccessibleOverrides struct {
	ModeChanged func(enabled bool)
	// The function takes the following parameters:
	//
	//   - currentOffset
	//   - lastOffset
	RegionChanged func(currentOffset, lastOffset int)
}

func defaultAccessibleOverrides(v *Accessible) AccessibleOverrides {
	return AccessibleOverrides{
		ModeChanged:   v.modeChanged,
		RegionChanged: v.regionChanged,
	}
}

// Accessible: base interface which is implemented by all accessible objects.
//
// All objects support interfaces for querying their contained 'children' and
// position in the accessible-object hierarchy, whether or not they actually
// have children.
type Accessible struct {
	_ [0]func() // equal guard
	AtspiObject

	*coreglib.Object
	Action
	Collection
	Component
	Document
	EditableText
	Hypertext
	Image
	Selection
	Table
	TableCell
	Text
	Value
}

var (
	_ coreglib.Objector = (*Accessible)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*Accessible, *AccessibleClass, AccessibleOverrides](
		GTypeAccessible,
		initAccessibleClass,
		wrapAccessible,
		defaultAccessibleOverrides,
	)
}

func initAccessibleClass(gclass unsafe.Pointer, overrides AccessibleOverrides, classInitFunc func(*AccessibleClass)) {
	pclass := (*C.AtspiAccessibleClass)(unsafe.Pointer(C.g_type_check_class_cast((*C.GTypeClass)(gclass), C.GType(GTypeAccessible))))

	if overrides.ModeChanged != nil {
		pclass.mode_changed = (*[0]byte)(C._gotk4_atspi2_AccessibleClass_mode_changed)
	}

	if overrides.RegionChanged != nil {
		pclass.region_changed = (*[0]byte)(C._gotk4_atspi2_AccessibleClass_region_changed)
	}

	if classInitFunc != nil {
		class := (*AccessibleClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapAccessible(obj *coreglib.Object) *Accessible {
	return &Accessible{
		AtspiObject: AtspiObject{
			Object: obj,
		},
		Object: obj,
		Action: Action{
			Object: obj,
		},
		Collection: Collection{
			Object: obj,
		},
		Component: Component{
			Object: obj,
		},
		Document: Document{
			Object: obj,
		},
		EditableText: EditableText{
			Object: obj,
		},
		Hypertext: Hypertext{
			Object: obj,
		},
		Image: Image{
			Object: obj,
		},
		Selection: Selection{
			Object: obj,
		},
		Table: Table{
			Object: obj,
		},
		TableCell: TableCell{
			Object: obj,
		},
		Text: Text{
			Object: obj,
		},
		Value: Value{
			Object: obj,
		},
	}
}

func marshalAccessible(p uintptr) (interface{}, error) {
	return wrapAccessible(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// ConnectModeChanged: signal "mode-changed" is emitted by a screen reader
// to indicate that its mode has changed. This signal supports the following
// details: focus-tracking flat-review mouse-review say-all caret-tracking.
func (obj *Accessible) ConnectModeChanged(f func(arg1 int, why string)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(obj, "mode-changed", false, unsafe.Pointer(C._gotk4_atspi2_Accessible_ConnectModeChanged), f)
}

// ConnectRegionChanged: signal "region-changed" is emitted by a screen reader
// to indicate that it is now reading or tracking a new object, or, a new piece
// of text within an object. This allows a magnifier to gain the information
// needed to highlight the object that the screen reader is reading.
func (obj *Accessible) ConnectRegionChanged(f func(arg1, arg2 int)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(obj, "region-changed", false, unsafe.Pointer(C._gotk4_atspi2_Accessible_ConnectRegionChanged), f)
}

// ClearCache clears the cached information for the given accessible and all of
// its descendants.
func (obj *Accessible) ClearCache() {
	var _arg0 *C.AtspiAccessible // out

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	C.atspi_accessible_clear_cache(_arg0)
	runtime.KeepAlive(obj)
}

// ClearCacheSingle clears the cached information only for the given accessible.
func (obj *Accessible) ClearCacheSingle() {
	var _arg0 *C.AtspiAccessible // out

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	C.atspi_accessible_clear_cache_single(_arg0)
	runtime.KeepAlive(obj)
}

// AccessibleID gets the accessible id of the accessible. This is not meant to
// be presented to the user, but to be an id which is stable over application
// development. Typically, this is the gtkbuilder id.
//
// The function returns the following values:
//
//   - utf8: character string representing the accessible id of the Accessible
//     object or NULL on exception.
func (obj *Accessible) AccessibleID() (string, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.gchar           // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_accessible_id(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// GetAction gets the Action interface for an Accessible.
//
// Deprecated: Use atspi_accessible_get_action_iface instead.
//
// The function returns the following values:
//
//   - action: pointer to an Action interface instance, or NULL if obj does not
//     implement Action.
func (obj *Accessible) GetAction() *Action {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiAction     // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_action(_arg0)
	runtime.KeepAlive(obj)

	var _action *Action // out

	_action = wrapAction(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _action
}

// ActionIface gets the Action interface for an Accessible.
//
// The function returns the following values:
//
//   - action: pointer to an Action interface instance, or NULL if obj does not
//     implement Action.
func (obj *Accessible) ActionIface() *Action {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiAction     // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_action_iface(_arg0)
	runtime.KeepAlive(obj)

	var _action *Action // out

	_action = wrapAction(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _action
}

// Application gets the containing Application for an object.
//
// The function returns the following values:
//
//   - accessible: containing Application instance for this object.
func (obj *Accessible) Application() (*Accessible, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_application(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _accessible *Accessible // out
	var _goerr error            // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// AtspiVersion gets the AT-SPI IPC specification version supported by the
// application pointed to by the Accessible object. Only works on application
// root objects.
//
// The function returns the following values:
//
//   - utf8: UTF-8 string indicating the AT-SPI version for the Accessible
//     object or NULL on exception.
func (obj *Accessible) AtspiVersion() (string, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.gchar           // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_atspi_version(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// Attributes gets the Set representing any assigned name-value pair
// attributes or annotations for this object. For typographic, textual,
// or textually-semantic attributes, see atspi_text_get_attributes instead.
//
// The function returns the following values:
//
//   - hashTable name-value-pair attributes assigned to this object.
func (obj *Accessible) Attributes() (map[string]string, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.GHashTable      // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_attributes(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _hashTable map[string]string // out
	var _goerr error                 // out

	_hashTable = make(map[string]string, gextras.HashTableSize(unsafe.Pointer(_cret)))
	gextras.MoveHashTable(unsafe.Pointer(_cret), true, func(k, v unsafe.Pointer) {
		ksrc := *(**C.gchar)(k)
		vsrc := *(**C.gchar)(v)
		var kdst string // out
		var vdst string // out
		kdst = C.GoString((*C.gchar)(unsafe.Pointer(ksrc)))
		defer C.free(unsafe.Pointer(ksrc))
		vdst = C.GoString((*C.gchar)(unsafe.Pointer(vsrc)))
		defer C.free(unsafe.Pointer(vsrc))
		_hashTable[kdst] = vdst
	})
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _hashTable, _goerr
}

// ChildAtIndex gets the Accessible child of an Accessible object at a given
// index.
//
// The function takes the following parameters:
//
//   - childIndex indicating which child is specified.
//
// The function returns the following values:
//
//   - accessible: pointer to the Accessible child object at index child_index
//     or NULL on exception.
func (obj *Accessible) ChildAtIndex(childIndex int) (*Accessible, error) {
	var _arg0 *C.AtspiAccessible // out
	var _arg1 C.gint             // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(childIndex)

	_cret = C.atspi_accessible_get_child_at_index(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(childIndex)

	var _accessible *Accessible // out
	var _goerr error            // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// ChildCount gets the number of children contained by an Accessible object.
//
// The function returns the following values:
//
//   - gint indicating the number of Accessible children contained by an
//     Accessible object or -1 on exception.
func (obj *Accessible) ChildCount() (int, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret C.gint             // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_child_count(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// GetCollection gets the Collection interface for an Accessible.
//
// Deprecated: Use atspi_accessible_get_collection_iface instead.
//
// The function returns the following values:
//
//   - collection: pointer to an Collection interface instance, or NULL if obj
//     does not implement Collection.
func (obj *Accessible) GetCollection() *Collection {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiCollection // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_collection(_arg0)
	runtime.KeepAlive(obj)

	var _collection *Collection // out

	_collection = wrapCollection(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _collection
}

// CollectionIface gets the Collection interface for an Accessible.
//
// The function returns the following values:
//
//   - collection: pointer to an Collection interface instance, or NULL if obj
//     does not implement Collection.
func (obj *Accessible) CollectionIface() *Collection {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiCollection // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_collection_iface(_arg0)
	runtime.KeepAlive(obj)

	var _collection *Collection // out

	_collection = wrapCollection(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _collection
}

// GetComponent gets the Component interface for an Accessible.
//
// Deprecated: Use atspi_accessible_get_component_iface instead.
//
// The function returns the following values:
//
//   - component: pointer to an Component interface instance, or NULL if obj
//     does not implement Component.
func (obj *Accessible) GetComponent() *Component {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiComponent  // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_component(_arg0)
	runtime.KeepAlive(obj)

	var _component *Component // out

	_component = wrapComponent(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _component
}

// ComponentIface gets the Component interface for an Accessible.
//
// The function returns the following values:
//
//   - component: pointer to an Component interface instance, or NULL if obj
//     does not implement Component.
func (obj *Accessible) ComponentIface() *Component {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiComponent  // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_component_iface(_arg0)
	runtime.KeepAlive(obj)

	var _component *Component // out

	_component = wrapComponent(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _component
}

// Description gets the description of an Accessible object.
//
// The function returns the following values:
//
//   - utf8: UTF-8 string describing the Accessible object or NULL on exception.
func (obj *Accessible) Description() (string, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.gchar           // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_description(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// GetDocument gets the Document interface for an Accessible.
//
// Deprecated: Use atspi_accessible_get_document_iface instead.
//
// The function returns the following values:
//
//   - document: pointer to an Document interface instance, or NULL if obj does
//     not implement Document.
func (obj *Accessible) GetDocument() *Document {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiDocument   // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_document(_arg0)
	runtime.KeepAlive(obj)

	var _document *Document // out

	_document = wrapDocument(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _document
}

// DocumentIface gets the Document interface for an Accessible.
//
// The function returns the following values:
//
//   - document: pointer to an Document interface instance, or NULL if obj does
//     not implement Document.
func (obj *Accessible) DocumentIface() *Document {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiDocument   // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_document_iface(_arg0)
	runtime.KeepAlive(obj)

	var _document *Document // out

	_document = wrapDocument(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _document
}

// GetEditableText gets the EditableText interface for an Accessible.
//
// Deprecated: Use atspi_accessible_get_editable_text_iface instead.
//
// The function returns the following values:
//
//   - editableText: pointer to an EditableText interface instance, or NULL if
//     obj does not implement EditableText.
func (obj *Accessible) GetEditableText() *EditableText {
	var _arg0 *C.AtspiAccessible   // out
	var _cret *C.AtspiEditableText // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_editable_text(_arg0)
	runtime.KeepAlive(obj)

	var _editableText *EditableText // out

	_editableText = wrapEditableText(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _editableText
}

// EditableTextIface gets the EditableText interface for an Accessible.
//
// The function returns the following values:
//
//   - editableText: pointer to an EditableText interface instance, or NULL if
//     obj does not implement EditableText.
func (obj *Accessible) EditableTextIface() *EditableText {
	var _arg0 *C.AtspiAccessible   // out
	var _cret *C.AtspiEditableText // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_editable_text_iface(_arg0)
	runtime.KeepAlive(obj)

	var _editableText *EditableText // out

	_editableText = wrapEditableText(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _editableText
}

// HelpText gets the help text associated with the accessible, if set. When this
// is present, it provides information that a screen reader can relay to the
// user to explain how to interact with the object.
//
// The function returns the following values:
//
//   - utf8: character string representing the help text for the Accessible
//     object or NULL on exception.
func (obj *Accessible) HelpText() (string, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.gchar           // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_help_text(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// Hyperlink gets the Hyperlink interface for an Accessible.
//
// The function returns the following values:
//
//   - hyperlink object associated with the given Accessible, or NULL if not
//     supported.
func (obj *Accessible) Hyperlink() *Hyperlink {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiHyperlink  // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_hyperlink(_arg0)
	runtime.KeepAlive(obj)

	var _hyperlink *Hyperlink // out

	_hyperlink = wrapHyperlink(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _hyperlink
}

// GetHypertext gets the Hypertext interface for an Accessible.
//
// Deprecated: Use atspi_accessible_get_hypertext_iface instead.
//
// The function returns the following values:
//
//   - hypertext: pointer to an Hypertext interface instance, or NULL if obj
//     does not implement Hypertext.
func (obj *Accessible) GetHypertext() *Hypertext {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiHypertext  // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_hypertext(_arg0)
	runtime.KeepAlive(obj)

	var _hypertext *Hypertext // out

	_hypertext = wrapHypertext(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _hypertext
}

// HypertextIface gets the Hypertext interface for an Accessible.
//
// The function returns the following values:
//
//   - hypertext: pointer to an Hypertext interface instance, or NULL if obj
//     does not implement Hypertext.
func (obj *Accessible) HypertextIface() *Hypertext {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiHypertext  // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_hypertext_iface(_arg0)
	runtime.KeepAlive(obj)

	var _hypertext *Hypertext // out

	_hypertext = wrapHypertext(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _hypertext
}

// ID gets the application id for a Accessible object. Only works on application
// root objects.
//
// The function returns the following values:
//
//   - gint: positive #gint indicating the id for the Accessible object or -1 on
//     exception.
func (obj *Accessible) ID() (int, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret C.gint             // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_id(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// GetImage gets the Image interface for an Accessible.
//
// Deprecated: Use atspi_accessible_get_image_iface instead.
//
// The function returns the following values:
//
//   - image: pointer to an Image interface instance, or NULL if obj does not
//     implement Image.
func (obj *Accessible) GetImage() *Image {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiImage      // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_image(_arg0)
	runtime.KeepAlive(obj)

	var _image *Image // out

	_image = wrapImage(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _image
}

// ImageIface gets the Image interface for an Accessible.
//
// The function returns the following values:
//
//   - image: pointer to an Image interface instance, or NULL if obj does not
//     implement Image.
func (obj *Accessible) ImageIface() *Image {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiImage      // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_image_iface(_arg0)
	runtime.KeepAlive(obj)

	var _image *Image // out

	_image = wrapImage(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _image
}

// IndexInParent gets the index of an Accessible object within its parent's
// Accessible children list.
//
// The function returns the following values:
//
//   - gint indicating the index of the Accessible object in its parent,
//     or -1 if obj has no containing parent or on exception.
func (obj *Accessible) IndexInParent() (int, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret C.gint             // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_index_in_parent(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// LocalizedRoleName gets a UTF-8 string corresponding to the name of the role
// played by an object, translated to the current locale. This method will
// return useful values for roles that fall outside the enumeration used in
// atspi_accessible_getRole ().
//
// The function returns the following values:
//
//   - utf8: localized, UTF-8 string specifying the type of UI role played by an
//     Accessible object.
func (obj *Accessible) LocalizedRoleName() (string, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.gchar           // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_localized_role_name(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// Name gets the name of an Accessible object.
//
// The function returns the following values:
//
//   - utf8: UTF-8 string indicating the name of the Accessible object or NULL
//     on exception.
func (obj *Accessible) Name() (string, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.gchar           // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_name(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

func (accessible *Accessible) ObjectLocale() (string, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.gchar           // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(accessible).Native()))

	_cret = C.atspi_accessible_get_object_locale(_arg0, &_cerr)
	runtime.KeepAlive(accessible)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// Parent gets an Accessible object's parent container.
//
// The function returns the following values:
//
//   - accessible (optional): pointer to the Accessible object which contains
//     the given Accessible instance, or NULL if the obj has no parent
//     container.
func (obj *Accessible) Parent() (*Accessible, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_parent(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _accessible *Accessible // out
	var _goerr error            // out

	if _cret != nil {
		_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// ProcessID returns the process id associated with the given accessible. Mainly
// added for debugging; it is a shortcut to explicitly querying the accessible's
// app->bus_name and then calling GetConnectionUnixProcessID.
//
// The function returns the following values:
//
//   - guint process ID or undetermined value if error is set.
func (accessible *Accessible) ProcessID() (uint, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret C.guint            // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(accessible).Native()))

	_cret = C.atspi_accessible_get_process_id(_arg0, &_cerr)
	runtime.KeepAlive(accessible)

	var _guint uint  // out
	var _goerr error // out

	_guint = uint(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _guint, _goerr
}

// RelationSet gets the set of Relation objects which describes this Accessible
// object's relationships with other Accessible objects.
//
// The function returns the following values:
//
//   - relations of Relation pointers or NULL on exception.
func (obj *Accessible) RelationSet() ([]*Relation, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.GArray          // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_relation_set(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _relations []*Relation // out
	var _goerr error           // out

	{
		var len uintptr
		p := C.g_array_steal(&_cret, (*C.gsize)(&len))
		src := unsafe.Slice((*C.GArray)(p), len)
		_relations = make([]*Relation, len)
		for i := 0; i < len; i++ {
			_relations[i] = wrapRelation(coreglib.AssumeOwnership(unsafe.Pointer(&src[i])))
		}
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _relations, _goerr
}

// Role gets the UI role played by an Accessible object. This role's name can be
// obtained via atspi_accessible_get_role_name ().
//
// The function returns the following values:
//
//   - role of an Accessible object.
func (obj *Accessible) Role() (Role, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret C.AtspiRole        // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_role(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _role Role   // out
	var _goerr error // out

	_role = Role(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _role, _goerr
}

// RoleName gets a UTF-8 string corresponding to the name of the role played by
// an object. This method will return useful values for roles that fall outside
// the enumeration used in atspi_accessible_get_role ().
//
// The function returns the following values:
//
//   - utf8: UTF-8 string specifying the type of UI role played by an Accessible
//     object.
func (obj *Accessible) RoleName() (string, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.gchar           // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_role_name(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// GetSelection gets the Selection interface for an Accessible.
//
// Deprecated: Use atspi_accessible_get_selection_iface instead.
//
// The function returns the following values:
//
//   - selection: pointer to an Selection interface instance, or NULL if obj
//     does not implement Selection.
func (obj *Accessible) GetSelection() *Selection {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiSelection  // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_selection(_arg0)
	runtime.KeepAlive(obj)

	var _selection *Selection // out

	_selection = wrapSelection(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _selection
}

// SelectionIface gets the Selection interface for an Accessible.
//
// The function returns the following values:
//
//   - selection: pointer to an Selection interface instance, or NULL if obj
//     does not implement Selection.
func (obj *Accessible) SelectionIface() *Selection {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiSelection  // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_selection_iface(_arg0)
	runtime.KeepAlive(obj)

	var _selection *Selection // out

	_selection = wrapSelection(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _selection
}

// StateSet gets the states currently held by an object.
//
// The function returns the following values:
//
//   - stateSet: pointer to an StateSet representing an object's current state
//     set.
func (obj *Accessible) StateSet() *StateSet {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiStateSet   // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_state_set(_arg0)
	runtime.KeepAlive(obj)

	var _stateSet *StateSet // out

	_stateSet = wrapStateSet(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _stateSet
}

// GetTable gets the Table interface for an Accessible.
//
// Deprecated: Use atspi_accessible_get_table_iface instead.
//
// The function returns the following values:
//
//   - table: pointer to an Table interface instance, or NULL if obj does not
//     implement Table.
func (obj *Accessible) GetTable() *Table {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiTable      // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_table(_arg0)
	runtime.KeepAlive(obj)

	var _table *Table // out

	_table = wrapTable(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _table
}

// GetTableCell gets the TableCell interface for an Accessible.
//
// The function returns the following values:
//
//   - tableCell: pointer to an TableCell interface instance, or NULL if obj
//     does not implement Table.
func (obj *Accessible) GetTableCell() *TableCell {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiTableCell  // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_table_cell(_arg0)
	runtime.KeepAlive(obj)

	var _tableCell *TableCell // out

	_tableCell = wrapTableCell(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _tableCell
}

// TableIface gets the Table interface for an Accessible.
//
// The function returns the following values:
//
//   - table: pointer to an Table interface instance, or NULL if obj does not
//     implement Table.
func (obj *Accessible) TableIface() *Table {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiTable      // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_table_iface(_arg0)
	runtime.KeepAlive(obj)

	var _table *Table // out

	_table = wrapTable(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _table
}

// GetText gets the Table interface for an Accessible.
//
// Deprecated: Use atspi_accessible_get_text_iface instead.
//
// The function returns the following values:
//
//   - text: pointer to an Text interface instance, or NULL if obj does not
//     implement Text.
func (obj *Accessible) GetText() *Text {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiText       // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_text(_arg0)
	runtime.KeepAlive(obj)

	var _text *Text // out

	_text = wrapText(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _text
}

// TextIface gets the Table interface for an Accessible.
//
// The function returns the following values:
//
//   - text: pointer to an Text interface instance, or NULL if obj does not
//     implement Text.
func (obj *Accessible) TextIface() *Text {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiText       // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_text_iface(_arg0)
	runtime.KeepAlive(obj)

	var _text *Text // out

	_text = wrapText(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _text
}

// ToolkitName gets the toolkit name for an Accessible object. Only works on
// application root objects.
//
// The function returns the following values:
//
//   - utf8: UTF-8 string indicating the toolkit name for the Accessible object
//     or NULL on exception.
func (obj *Accessible) ToolkitName() (string, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.gchar           // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_toolkit_name(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// ToolkitVersion gets the toolkit version for an Accessible object. Only works
// on application root objects.
//
// The function returns the following values:
//
//   - utf8: UTF-8 string indicating the toolkit version for the Accessible
//     object or NULL on exception.
func (obj *Accessible) ToolkitVersion() (string, error) {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.gchar           // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_toolkit_version(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// GetValue gets the Table interface for an Accessible.
//
// Deprecated: Use atspi_accessible_get_value_iface instead.
//
// The function returns the following values:
//
//   - value: pointer to an Value interface instance, or NULL if obj does not
//     implement Value.
func (obj *Accessible) GetValue() *Value {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiValue      // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_value(_arg0)
	runtime.KeepAlive(obj)

	var _value *Value // out

	_value = wrapValue(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _value
}

// ValueIface gets the Table interface for an Accessible.
//
// The function returns the following values:
//
//   - value: pointer to an Value interface instance, or NULL if obj does not
//     implement Value.
func (obj *Accessible) ValueIface() *Value {
	var _arg0 *C.AtspiAccessible // out
	var _cret *C.AtspiValue      // in

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_accessible_get_value_iface(_arg0)
	runtime.KeepAlive(obj)

	var _value *Value // out

	_value = wrapValue(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _value
}

// SetCacheMask sets the type of data to cache for accessibles. If this is
// not set for an application or is reset to ATSPI_CACHE_UNDEFINED, then the
// desktop's cache flag will be used. If the desktop's cache flag is also
// undefined, then all possible data will be cached. This function is intended
// to work around bugs in toolkits where the proper events are not raised / to
// aid in testing for such bugs.
//
// The function takes the following parameters:
//
//   - mask specifying a bit mask of the types of data to cache.
func (accessible *Accessible) SetCacheMask(mask Cache) {
	var _arg0 *C.AtspiAccessible // out
	var _arg1 C.AtspiCache       // out

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(accessible).Native()))
	_arg1 = C.AtspiCache(mask)

	C.atspi_accessible_set_cache_mask(_arg0, _arg1)
	runtime.KeepAlive(accessible)
	runtime.KeepAlive(mask)
}

func (accessible *Accessible) modeChanged(enabled bool) {
	gclass := (*C.AtspiAccessibleClass)(coreglib.PeekParentClass(accessible))
	fnarg := gclass.mode_changed

	var _arg0 *C.AtspiAccessible // out
	var _arg1 C.gboolean         // out

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(accessible).Native()))
	if enabled {
		_arg1 = C.TRUE
	}

	C._gotk4_atspi2_Accessible_virtual_mode_changed(unsafe.Pointer(fnarg), _arg0, _arg1)
	runtime.KeepAlive(accessible)
	runtime.KeepAlive(enabled)
}

// The function takes the following parameters:
//
//   - currentOffset
//   - lastOffset
func (accessible *Accessible) regionChanged(currentOffset, lastOffset int) {
	gclass := (*C.AtspiAccessibleClass)(coreglib.PeekParentClass(accessible))
	fnarg := gclass.region_changed

	var _arg0 *C.AtspiAccessible // out
	var _arg1 C.gint             // out
	var _arg2 C.gint             // out

	_arg0 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(accessible).Native()))
	_arg1 = C.gint(currentOffset)
	_arg2 = C.gint(lastOffset)

	C._gotk4_atspi2_Accessible_virtual_region_changed(unsafe.Pointer(fnarg), _arg0, _arg1, _arg2)
	runtime.KeepAlive(accessible)
	runtime.KeepAlive(currentOffset)
	runtime.KeepAlive(lastOffset)
}

// AccessibleClass: instance of this type is always passed by reference.
type AccessibleClass struct {
	*accessibleClass
}

// accessibleClass is the struct that's finalized.
type accessibleClass struct {
	native *C.AtspiAccessibleClass
}

func (a *AccessibleClass) ParentClass() *ObjectClass {
	valptr := &a.native.parent_class
	var _v *ObjectClass // out
	_v = (*ObjectClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
