// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"unsafe"

	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
import "C"

//export _gotk4_atspi2_Accessible_ConnectModeChanged
func _gotk4_atspi2_Accessible_ConnectModeChanged(arg0 C.gpointer, arg1 C.gint, arg2 *C.gchar, arg3 C.guintptr) {
	var f func(arg1 int, why string)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg3))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(arg1 int, why string))
	}

	var _arg1 int   // out
	var _why string // out

	_arg1 = int(arg1)
	_why = C.GoString((*C.gchar)(unsafe.Pointer(arg2)))

	f(_arg1, _why)
}

//export _gotk4_atspi2_Accessible_ConnectRegionChanged
func _gotk4_atspi2_Accessible_ConnectRegionChanged(arg0 C.gpointer, arg1 C.gint, arg2 C.gint, arg3 C.guintptr) {
	var f func(arg1, arg2 int)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg3))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(arg1, arg2 int))
	}

	var _arg1 int // out
	var _arg2 int // out

	_arg1 = int(arg1)
	_arg2 = int(arg2)

	f(_arg1, _arg2)
}
