// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"unsafe"

	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
import "C"

// TextSelection: this structure represents a single text selection within a
// document. This selection is defined by two points in the content, where
// each one is defined by an AtkObject supporting the AtkText interface and a
// character offset relative to it.
//
// The end object must appear after the start object in the accessibility tree,
// i.e. the end object must be reachable from the start object by navigating
// forward (next, first child etc).
//
// This struct also contains a start_is_active boolean, to communicate if the
// start of the selection is the active point or not.
//
// The active point corresponds to the user's focus or point of interest.
// The user moves the active point to expand or collapse the range. The anchor
// point is the other point of the range and typically remains constant. In
// most cases, anchor is the start of the range and active is the end. However,
// when selecting backwards (e.g. pressing shift+left arrow in a text field),
// the start of the range is the active point, as the user moves this to
// manipulate the selection.
//
// An instance of this type is always passed by reference.
type TextSelection struct {
	*textSelection
}

// textSelection is the struct that's finalized.
type textSelection struct {
	native *C.AtspiTextSelection
}

// StartObject: atspiAccessible containing the start of the selection.
func (t *TextSelection) StartObject() *Accessible {
	valptr := &t.native.start_object
	var _v *Accessible // out
	_v = wrapAccessible(coreglib.Take(unsafe.Pointer(*valptr)))
	return _v
}

// StartOffset: text offset of the beginning of the selection within
// start_object.
func (t *TextSelection) StartOffset() int {
	valptr := &t.native.start_offset
	var _v int // out
	_v = int(*valptr)
	return _v
}

// EndObject: atspiAccessible containing the end of the selection.
func (t *TextSelection) EndObject() *Accessible {
	valptr := &t.native.end_object
	var _v *Accessible // out
	_v = wrapAccessible(coreglib.Take(unsafe.Pointer(*valptr)))
	return _v
}

// EndOffset: text offset of the end of the selection within end_object.
func (t *TextSelection) EndOffset() int {
	valptr := &t.native.end_offset
	var _v int // out
	_v = int(*valptr)
	return _v
}

// StartIsActive: gboolean indicating whether the start of the selection is the
// active point.
func (t *TextSelection) StartIsActive() bool {
	valptr := &t.native.start_is_active
	var _v bool // out
	if *valptr != 0 {
		_v = true
	}
	return _v
}

// StartOffset: text offset of the beginning of the selection within
// start_object.
func (t *TextSelection) SetStartOffset(startOffset int) {
	valptr := &t.native.start_offset
	*valptr = C.gint(startOffset)
}

// EndOffset: text offset of the end of the selection within end_object.
func (t *TextSelection) SetEndOffset(endOffset int) {
	valptr := &t.native.end_offset
	*valptr = C.gint(endOffset)
}

// StartIsActive: gboolean indicating whether the start of the selection is the
// active point.
func (t *TextSelection) SetStartIsActive(startIsActive bool) {
	valptr := &t.native.start_is_active
	if startIsActive {
		*valptr = C.TRUE
	}
}
