// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
import "C"

//export _gotk4_atspi2_AccessibleClass_mode_changed
func _gotk4_atspi2_AccessibleClass_mode_changed(arg0 *C.AtspiAccessible, arg1 C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[AccessibleOverrides](instance0)
	if overrides.ModeChanged == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected AccessibleOverrides.ModeChanged, got none")
	}

	var _enabled bool // out

	if arg1 != 0 {
		_enabled = true
	}

	overrides.ModeChanged(_enabled)
}

//export _gotk4_atspi2_AccessibleClass_region_changed
func _gotk4_atspi2_AccessibleClass_region_changed(arg0 *C.AtspiAccessible, arg1 C.gint, arg2 C.gint) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[AccessibleOverrides](instance0)
	if overrides.RegionChanged == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected AccessibleOverrides.RegionChanged, got none")
	}

	var _currentOffset int // out
	var _lastOffset int    // out

	_currentOffset = int(arg1)
	_lastOffset = int(arg2)

	overrides.RegionChanged(_currentOffset, _lastOffset)
}

//export _gotk4_atspi2_DeviceClass_add_key_grab
func _gotk4_atspi2_DeviceClass_add_key_grab(arg0 *C.AtspiDevice, arg1 *C.AtspiKeyDefinition) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[DeviceOverrides](instance0)
	if overrides.AddKeyGrab == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected DeviceOverrides.AddKeyGrab, got none")
	}

	var _kd *KeyDefinition // out

	_kd = (*KeyDefinition)(gextras.NewStructNative(unsafe.Pointer(arg1)))

	ok := overrides.AddKeyGrab(_kd)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_atspi2_DeviceClass_generate_mouse_event
func _gotk4_atspi2_DeviceClass_generate_mouse_event(arg0 *C.AtspiDevice, arg1 *C.AtspiAccessible, arg2 C.gint, arg3 C.gint, arg4 *C.gchar, _cerr **C.GError) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[DeviceOverrides](instance0)
	if overrides.GenerateMouseEvent == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected DeviceOverrides.GenerateMouseEvent, got none")
	}

	var _obj *Accessible // out
	var _x int           // out
	var _y int           // out
	var _name string     // out

	_obj = wrapAccessible(coreglib.Take(unsafe.Pointer(arg1)))
	_x = int(arg2)
	_y = int(arg3)
	_name = C.GoString((*C.gchar)(unsafe.Pointer(arg4)))

	_goerr := overrides.GenerateMouseEvent(_obj, _x, _y, _name)

	var _ error

	if _goerr != nil && _cerr != nil {
		*_cerr = (*C.GError)(gerror.New(_goerr))
	}
}

//export _gotk4_atspi2_DeviceClass_get_locked_modifiers
func _gotk4_atspi2_DeviceClass_get_locked_modifiers(arg0 *C.AtspiDevice) (cret C.guint) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[DeviceOverrides](instance0)
	if overrides.LockedModifiers == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected DeviceOverrides.LockedModifiers, got none")
	}

	guint := overrides.LockedModifiers()

	var _ uint

	cret = C.guint(guint)

	return cret
}

//export _gotk4_atspi2_DeviceClass_get_modifier
func _gotk4_atspi2_DeviceClass_get_modifier(arg0 *C.AtspiDevice, arg1 C.gint) (cret C.guint) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[DeviceOverrides](instance0)
	if overrides.Modifier == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected DeviceOverrides.Modifier, got none")
	}

	var _keycode int // out

	_keycode = int(arg1)

	guint := overrides.Modifier(_keycode)

	var _ uint

	cret = C.guint(guint)

	return cret
}

//export _gotk4_atspi2_DeviceClass_grab_keyboard
func _gotk4_atspi2_DeviceClass_grab_keyboard(arg0 *C.AtspiDevice) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[DeviceOverrides](instance0)
	if overrides.GrabKeyboard == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected DeviceOverrides.GrabKeyboard, got none")
	}

	ok := overrides.GrabKeyboard()

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_atspi2_DeviceClass_map_modifier
func _gotk4_atspi2_DeviceClass_map_modifier(arg0 *C.AtspiDevice, arg1 C.gint) (cret C.guint) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[DeviceOverrides](instance0)
	if overrides.MapModifier == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected DeviceOverrides.MapModifier, got none")
	}

	var _keycode int // out

	_keycode = int(arg1)

	guint := overrides.MapModifier(_keycode)

	var _ uint

	cret = C.guint(guint)

	return cret
}

//export _gotk4_atspi2_DeviceClass_remove_key_grab
func _gotk4_atspi2_DeviceClass_remove_key_grab(arg0 *C.AtspiDevice, arg1 C.guint) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[DeviceOverrides](instance0)
	if overrides.RemoveKeyGrab == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected DeviceOverrides.RemoveKeyGrab, got none")
	}

	var _id uint // out

	_id = uint(arg1)

	overrides.RemoveKeyGrab(_id)
}

//export _gotk4_atspi2_DeviceClass_ungrab_keyboard
func _gotk4_atspi2_DeviceClass_ungrab_keyboard(arg0 *C.AtspiDevice) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[DeviceOverrides](instance0)
	if overrides.UngrabKeyboard == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected DeviceOverrides.UngrabKeyboard, got none")
	}

	overrides.UngrabKeyboard()
}

//export _gotk4_atspi2_DeviceClass_unmap_modifier
func _gotk4_atspi2_DeviceClass_unmap_modifier(arg0 *C.AtspiDevice, arg1 C.gint) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[DeviceOverrides](instance0)
	if overrides.UnmapModifier == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected DeviceOverrides.UnmapModifier, got none")
	}

	var _keycode int // out

	_keycode = int(arg1)

	overrides.UnmapModifier(_keycode)
}

//export _gotk4_atspi2_DeviceListenerClass_device_event
func _gotk4_atspi2_DeviceListenerClass_device_event(arg0 *C.AtspiDeviceListener, arg1 *C.AtspiDeviceEvent) (cret C.gboolean) {
	instance0 := coreglib.Take(unsafe.Pointer(arg0))
	overrides := coreglib.OverridesFromObj[DeviceListenerOverrides](instance0)
	if overrides.DeviceEvent == nil {
		panic("gotk4: " + instance0.TypeFromInstance().String() + ": expected DeviceListenerOverrides.DeviceEvent, got none")
	}

	var _event *DeviceEvent // out

	_event = (*DeviceEvent)(gextras.NewStructNative(unsafe.Pointer(arg1)))

	ok := overrides.DeviceEvent(_event)

	var _ bool

	if ok {
		cret = C.TRUE
	}

	return cret
}
