// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
import "C"

type GenerateMouseEventCB func()

// DeregisterKeystrokeListener removes a keystroke event listener from the
// registry's listener queue, ceasing notification of events with modifiers
// matching modmask.
//
// The function takes the following parameters:
//
//   - listener: pointer to the DeviceListener for which keystroke events are
//     requested.
//   - keySet (optional): pointer to the KeyDefinition array indicating which
//     keystroke events are requested, or NULL to indicate that all keycodes and
//     keyvals for the specified modifier set are to be included.
//   - modmask: key modifier mask for which this listener is to be
//     'deregistered' (of type KeyMaskType).
//   - eventTypes mask indicating which types of key events were requested
//     (ATSPI_KEY_PRESSED, etc.).
func DeregisterKeystrokeListener(listener *DeviceListener, keySet []KeyDefinition, modmask KeyMaskType, eventTypes KeyEventMask) error {
	var _arg1 *C.AtspiDeviceListener // out
	var _arg2 *C.GArray              // out
	var _arg3 C.AtspiKeyMaskType     // out
	var _arg4 C.AtspiKeyEventMask    // out
	var _cerr *C.GError              // in

	_arg1 = (*C.AtspiDeviceListener)(unsafe.Pointer(coreglib.InternObject(listener).Native()))
	_arg2 = C.g_array_sized_new(false, false, C.guint(C.sizeof_GArray), C.guint(len(keySet)))
	_arg2 = C.g_array_set_size(_arg2, C.guint(len(keySet)))
	defer C.g_array_unref(_arg2)
	{
		out := unsafe.Slice(_arg2.data, len(keySet))
		for i := range keySet {
			out[i] = *(*C.GArray)(gextras.StructNative(unsafe.Pointer((&keySet[i]))))
		}
	}
	_arg3 = C.AtspiKeyMaskType(modmask)
	_arg4 = C.AtspiKeyEventMask(eventTypes)

	C.atspi_deregister_keystroke_listener(_arg1, _arg2, _arg3, _arg4, &_cerr)
	runtime.KeepAlive(listener)
	runtime.KeepAlive(keySet)
	runtime.KeepAlive(modmask)
	runtime.KeepAlive(eventTypes)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// GenerateKeyboardEvent synthesizes a keyboard event (as if a hardware keyboard
// event occurred in the current UI context).
//
// The function takes the following parameters:
//
//   - keyval indicating the keycode or keysym or modifier mask of the key event
//     being synthesized.
//   - keystring (optional): (optional) UTF-8 string which, if synth_type is
//     ATSPI_KEY_STRING, indicates a 'composed' keyboard input string being
//     synthesized; this type of keyboard event synthesis does not emulate
//     hardware keypresses but injects the string as though a composing input
//     method (such as XIM) were used.
//   - synthType flag indicating whether keyval is to be interpreted as a keysym
//     rather than a keycode (ATSPI_KEY_SYM) or a string (ATSPI_KEY_STRING) or
//     a modifier mask (ATSPI_KEY_LOCKMODIFIERS and ATSPI_KEY_UNLOCKMODIFIERS),
//     or whether to synthesize ATSPI_KEY_PRESS, ATSPI_KEY_RELEASE, or both
//     (ATSPI_KEY_PRESSRELEASE).
func GenerateKeyboardEvent(keyval int32, keystring string, synthType KeySynthType) error {
	var _arg1 C.glong             // out
	var _arg2 *C.gchar            // out
	var _arg3 C.AtspiKeySynthType // out
	var _cerr *C.GError           // in

	_arg1 = C.glong(keyval)
	if keystring != "" {
		_arg2 = (*C.gchar)(unsafe.Pointer(C.CString(keystring)))
		defer C.free(unsafe.Pointer(_arg2))
	}
	_arg3 = C.AtspiKeySynthType(synthType)

	C.atspi_generate_keyboard_event(_arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(keyval)
	runtime.KeepAlive(keystring)
	runtime.KeepAlive(synthType)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// GenerateMouseEvent synthesizes a mouse event at a specific screen coordinate.
// Most AT clients should use the Action interface when tempted to generate
// mouse events, rather than this method. Event names: b1p = button 1 press;
// b2r = button 2 release; b3c = button 3 click; b2d = button 2 double-click;
// abs = absolute motion; rel = relative motion.
//
// The function takes the following parameters:
//
//   - x indicating the screen x coordinate of the mouse event.
//   - y indicating the screen y coordinate of the mouse event.
//   - name: string indicating which mouse event to be synthesized (e.g. "b1p",
//     "b1c", "b2r", "rel", "abs").
func GenerateMouseEvent(x, y int32, name string) error {
	var _arg1 C.glong   // out
	var _arg2 C.glong   // out
	var _arg3 *C.gchar  // out
	var _cerr *C.GError // in

	_arg1 = C.glong(x)
	_arg2 = C.glong(y)
	_arg3 = (*C.gchar)(unsafe.Pointer(C.CString(name)))
	defer C.free(unsafe.Pointer(_arg3))

	C.atspi_generate_mouse_event(_arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)
	runtime.KeepAlive(name)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// GetDesktop gets the virtual desktop indicated by index i. NOTE: currently
// multiple virtual desktops are not implemented; as a consequence, any i value
// different from 0 will not return a virtual desktop - instead it will return
// NULL.
//
// The function takes the following parameters:
//
//   - i indicating which of the accessible desktops is to be returned.
//
// The function returns the following values:
//
//   - accessible: pointer to the i-th virtual desktop's Accessible
//     representation.
func GetDesktop(i int) *Accessible {
	var _arg1 C.gint             // out
	var _cret *C.AtspiAccessible // in

	_arg1 = C.gint(i)

	_cret = C.atspi_get_desktop(_arg1)
	runtime.KeepAlive(i)

	var _accessible *Accessible // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _accessible
}

// GetDesktopCount gets the number of virtual desktops. NOTE: multiple virtual
// desktops are not implemented yet; as a consequence, this function always
// returns 1.
//
// The function returns the following values:
//
//   - gint indicating the number of active virtual desktops.
func GetDesktopCount() int {
	var _cret C.gint // in

	_cret = C.atspi_get_desktop_count()

	var _gint int // out

	_gint = int(_cret)

	return _gint
}

// GetDesktopList gets the list of virtual desktops. On return, list will point
// to a newly-created, NULL terminated array of virtual desktop pointers. It
// is the responsibility of the caller to free this array when it is no longer
// needed. NOTE: currently multiple virtual desktops are not implemented; this
// implementation always returns a #Garray with a single Accessible desktop.
//
// The function returns the following values:
//
//   - accessibles: #GArray of desktops.
func GetDesktopList() []*Accessible {
	var _cret *C.GArray // in

	_cret = C.atspi_get_desktop_list()

	var _accessibles []*Accessible // out

	{
		var len uintptr
		p := C.g_array_steal(&_cret, (*C.gsize)(&len))
		src := unsafe.Slice((*C.GArray)(p), len)
		_accessibles = make([]*Accessible, len)
		for i := 0; i < len; i++ {
			_accessibles[i] = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(&src[i])))
		}
	}

	return _accessibles
}

// RegisterKeystrokeListener registers a listener for keystroke events,
// either pre-emptively for all windows (ATSPI_KEYLISTENER_ALL_WINDOWS),
// non-preemptively (ATSPI_KEYLISTENER_NOSYNC), or pre-emptively at the toolkit
// level (ATSPI_KEYLISTENER_CANCONSUME). If ALL_WINDOWS or CANCONSUME are used,
// the event is consumed upon receipt if one of listener's callbacks returns
// TRUE (other sync_type values may be available in the future).
//
// The function takes the following parameters:
//
//   - listener: pointer to the DeviceListener for which keystroke events are
//     requested.
//   - keySet (optional): pointer to the KeyDefinition array indicating which
//     keystroke events are requested, or NULL to indicate that all keycodes and
//     keyvals for the specified modifier set are to be included.
//   - modmask mask indicating which key event modifiers must be set in
//     combination with keys, events will only be reported for key events
//     for which all modifiers in modmask are set. If you wish to listen
//     for events with multiple modifier combinations, you must call
//     #atspi_register_keystroke_listener once for each combination.
//   - eventTypes mask indicating which types of key events are requested
//     (ATSPI_KEY_PRESSED etc.).
//   - syncType parameter indicating the behavior of the notification/listener
//     transaction.
func RegisterKeystrokeListener(listener *DeviceListener, keySet []KeyDefinition, modmask KeyMaskType, eventTypes KeyEventMask, syncType KeyListenerSyncType) error {
	var _arg1 *C.AtspiDeviceListener     // out
	var _arg2 *C.GArray                  // out
	var _arg3 C.AtspiKeyMaskType         // out
	var _arg4 C.AtspiKeyEventMask        // out
	var _arg5 C.AtspiKeyListenerSyncType // out
	var _cerr *C.GError                  // in

	_arg1 = (*C.AtspiDeviceListener)(unsafe.Pointer(coreglib.InternObject(listener).Native()))
	_arg2 = C.g_array_sized_new(false, false, C.guint(C.sizeof_GArray), C.guint(len(keySet)))
	_arg2 = C.g_array_set_size(_arg2, C.guint(len(keySet)))
	defer C.g_array_unref(_arg2)
	{
		out := unsafe.Slice(_arg2.data, len(keySet))
		for i := range keySet {
			out[i] = *(*C.GArray)(gextras.StructNative(unsafe.Pointer((&keySet[i]))))
		}
	}
	_arg3 = C.AtspiKeyMaskType(modmask)
	_arg4 = C.AtspiKeyEventMask(eventTypes)
	_arg5 = C.AtspiKeyListenerSyncType(syncType)

	C.atspi_register_keystroke_listener(_arg1, _arg2, _arg3, _arg4, _arg5, &_cerr)
	runtime.KeepAlive(listener)
	runtime.KeepAlive(keySet)
	runtime.KeepAlive(modmask)
	runtime.KeepAlive(eventTypes)
	runtime.KeepAlive(syncType)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// SetReferenceWindow: deprecated. This function no longer does anything and
// should not be used.
//
// The function takes the following parameters:
//
//   - accessible corresponding to the window to select. should be a top-level
//     window with a role of ATSPI_ROLE_APPLICATION.
func SetReferenceWindow(accessible *Accessible) {
	var _arg1 *C.AtspiAccessible // out

	_arg1 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(accessible).Native()))

	C.atspi_set_reference_window(_arg1)
	runtime.KeepAlive(accessible)
}
