// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeHyperlink = coreglib.Type(C.atspi_hyperlink_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeHyperlink, F: marshalHyperlink},
	})
}

// HyperlinkOverrides contains methods that are overridable.
type HyperlinkOverrides struct {
}

func defaultHyperlinkOverrides(v *Hyperlink) HyperlinkOverrides {
	return HyperlinkOverrides{}
}

// Hyperlink instances of atspi-hyperlink are the means by which end users and
// clients interact with linked content.
//
//	Instances of atspi-hyperlink are returned by
//
// atspi-hypertext objects, and are the means by which end users and clients
// interact with linked, and in some cases embedded, content. These instances
// may have multiple "anchors", where an anchor corresponds to a reference to a
// particular resource with a corresponding resource identified (URI).
type Hyperlink struct {
	_ [0]func() // equal guard
	AtspiObject
}

var (
	_ coreglib.Objector = (*Hyperlink)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*Hyperlink, *HyperlinkClass, HyperlinkOverrides](
		GTypeHyperlink,
		initHyperlinkClass,
		wrapHyperlink,
		defaultHyperlinkOverrides,
	)
}

func initHyperlinkClass(gclass unsafe.Pointer, overrides HyperlinkOverrides, classInitFunc func(*HyperlinkClass)) {
	if classInitFunc != nil {
		class := (*HyperlinkClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapHyperlink(obj *coreglib.Object) *Hyperlink {
	return &Hyperlink{
		AtspiObject: AtspiObject{
			Object: obj,
		},
	}
}

func marshalHyperlink(p uintptr) (interface{}, error) {
	return wrapHyperlink(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// EndIndex gets the ending character offset of the text range associated with
// an Hyperlink, in its originating Hypertext.
func (obj *Hyperlink) EndIndex() (int, error) {
	var _arg0 *C.AtspiHyperlink // out
	var _cret C.gint            // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiHyperlink)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_hyperlink_get_end_index(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// IndexRange gets the starting and ending character offsets of the text range
// associated with an Hyperlink, in its originating Hypertext.
func (obj *Hyperlink) IndexRange() (*Range, error) {
	var _arg0 *C.AtspiHyperlink // out
	var _cret *C.AtspiRange     // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiHyperlink)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_hyperlink_get_index_range(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var __range *Range // out
	var _goerr error   // out

	__range = (*Range)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(__range)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return __range, _goerr
}

// NAnchors gets the total number of anchors which an Hyperlink implementor has.
// Though typical hyperlinks have only one anchor, client-side image maps and
// other hypertext objects may potentially activate or refer to multiple URIs.
// For each anchor there is a corresponding URI and object.
//
// see: #atspi_hyperlink_get_uri and #atspi_hyperlink_get_object.
//
// The function returns the following values:
//
//   - gint indicating the number of anchors in this hyperlink.
func (obj *Hyperlink) NAnchors() (int, error) {
	var _arg0 *C.AtspiHyperlink // out
	var _cret C.gint            // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiHyperlink)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_hyperlink_get_n_anchors(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// Object gets the object associated with a particular hyperlink anchor,
// as an Accessible.
//
// The function takes the following parameters:
//
//   - i: (zero-index) #gint indicating which hyperlink anchor to query.
//
// The function returns the following values:
//
//   - accessible that represents the object associated with the ith anchor of
//     the specified Hyperlink.
func (obj *Hyperlink) Object(i int) (*Accessible, error) {
	var _arg0 *C.AtspiHyperlink  // out
	var _arg1 C.gint             // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiHyperlink)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(i)

	_cret = C.atspi_hyperlink_get_object(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(i)

	var _accessible *Accessible // out
	var _goerr error            // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// StartIndex gets the starting character offset of the text range associated
// with an Hyperlink, in its originating Hypertext.
func (obj *Hyperlink) StartIndex() (int, error) {
	var _arg0 *C.AtspiHyperlink // out
	var _cret C.gint            // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiHyperlink)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_hyperlink_get_start_index(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// URI gets the URI associated with a particular hyperlink anchor.
//
// The function takes the following parameters:
//
//   - i: (zero-index) integer indicating which hyperlink anchor to query.
//
// The function returns the following values:
//
//   - utf8: UTF-8 string giving the URI of the ith hyperlink anchor.
func (obj *Hyperlink) URI(i int) (string, error) {
	var _arg0 *C.AtspiHyperlink // out
	var _arg1 C.int             // out
	var _cret *C.gchar          // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiHyperlink)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.int(i)

	_cret = C.atspi_hyperlink_get_uri(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(i)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// IsValid tells whether an Hyperlink object is still valid with respect to its
// originating hypertext object.
func (obj *Hyperlink) IsValid() error {
	var _arg0 *C.AtspiHyperlink // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiHyperlink)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	C.atspi_hyperlink_is_valid(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// HyperlinkClass: instance of this type is always passed by reference.
type HyperlinkClass struct {
	*hyperlinkClass
}

// hyperlinkClass is the struct that's finalized.
type hyperlinkClass struct {
	native *C.AtspiHyperlinkClass
}

func (h *HyperlinkClass) ParentClass() *ObjectClass {
	valptr := &h.native.parent_class
	var _v *ObjectClass // out
	_v = (*ObjectClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
