// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeHypertext = coreglib.Type(C.atspi_hypertext_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeHypertext, F: marshalHypertext},
	})
}

// Hypertext: interface used for objects which implement linking between
// multiple resource locations.
//
// An interface used for objects which implement linking between multiple
// resource or content locations, or multiple 'markers' within a single
// document. A hypertext instance is associated with one or more hyperlinks
// which are associated with particular offsets within the hypertext's content.
//
// Hypertext wraps an interface. This means the user can get the
// underlying type by calling Cast().
type Hypertext struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Hypertext)(nil)
)

// Hypertexter describes Hypertext's interface methods.
type Hypertexter interface {
	coreglib.Objector

	// Link gets the Hyperlink object at a specified index.
	Link(linkIndex int) (*Hyperlink, error)
	// LinkIndex gets the index of the Hyperlink object at a specified character
	// offset.
	LinkIndex(characterOffset int) (int, error)
	// NLinks gets the total number of Hyperlink objects that an Hypertext
	// implementor has.
	NLinks() (int, error)
}

var _ Hypertexter = (*Hypertext)(nil)

func wrapHypertext(obj *coreglib.Object) *Hypertext {
	return &Hypertext{
		Object: obj,
	}
}

func marshalHypertext(p uintptr) (interface{}, error) {
	return wrapHypertext(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// Link gets the Hyperlink object at a specified index.
//
// The function takes the following parameters:
//
//   - linkIndex: (zero-index) #gint indicating which hyperlink to query.
//
// The function returns the following values:
//
//   - hyperlink (optional) object specified by link_index.
func (obj *Hypertext) Link(linkIndex int) (*Hyperlink, error) {
	var _arg0 *C.AtspiHypertext // out
	var _arg1 C.gint            // out
	var _cret *C.AtspiHyperlink // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiHypertext)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(linkIndex)

	_cret = C.atspi_hypertext_get_link(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(linkIndex)

	var _hyperlink *Hyperlink // out
	var _goerr error          // out

	if _cret != nil {
		_hyperlink = wrapHyperlink(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _hyperlink, _goerr
}

// LinkIndex gets the index of the Hyperlink object at a specified character
// offset.
//
// The function takes the following parameters:
//
//   - characterOffset specifying the character offset to query.
//
// The function returns the following values:
//
//   - gint: linkIndex of the Hyperlink active at character offset
//     character_offset, or -1 if there is no hyperlink at the specified
//     character offset.
func (obj *Hypertext) LinkIndex(characterOffset int) (int, error) {
	var _arg0 *C.AtspiHypertext // out
	var _arg1 C.gint            // out
	var _cret C.gint            // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiHypertext)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(characterOffset)

	_cret = C.atspi_hypertext_get_link_index(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(characterOffset)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// NLinks gets the total number of Hyperlink objects that an Hypertext
// implementor has.
//
// The function returns the following values:
//
//   - gint indicating the number of Hyperlink objects of the Hypertext
//     implementor, or -1 if the number cannot be determined (for example,
//     if the Hypertext object is so large that it is not all currently in the
//     memory cache).
func (obj *Hypertext) NLinks() (int, error) {
	var _arg0 *C.AtspiHypertext // out
	var _cret C.gint            // in
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiHypertext)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_hypertext_get_n_links(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}
