// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
// extern void _gotk4_atspi2_DeviceClass_unmap_modifier(AtspiDevice*, gint);
// extern void _gotk4_atspi2_DeviceClass_ungrab_keyboard(AtspiDevice*);
// extern void _gotk4_atspi2_DeviceClass_remove_key_grab(AtspiDevice*, guint);
// extern void _gotk4_atspi2_DeviceClass_generate_mouse_event(AtspiDevice*, AtspiAccessible*, gint, gint, gchar*, GError**);
// extern guint _gotk4_atspi2_DeviceClass_map_modifier(AtspiDevice*, gint);
// extern guint _gotk4_atspi2_DeviceClass_get_modifier(AtspiDevice*, gint);
// extern guint _gotk4_atspi2_DeviceClass_get_locked_modifiers(AtspiDevice*);
// extern gboolean _gotk4_atspi2_DeviceClass_grab_keyboard(AtspiDevice*);
// extern gboolean _gotk4_atspi2_DeviceClass_add_key_grab(AtspiDevice*, AtspiKeyDefinition*);
// gboolean _gotk4_atspi2_Device_virtual_add_key_grab(void* fnptr, AtspiDevice* arg0, AtspiKeyDefinition* arg1) {
//   return ((gboolean (*)(AtspiDevice*, AtspiKeyDefinition*))(fnptr))(arg0, arg1);
// };
// gboolean _gotk4_atspi2_Device_virtual_grab_keyboard(void* fnptr, AtspiDevice* arg0) {
//   return ((gboolean (*)(AtspiDevice*))(fnptr))(arg0);
// };
// guint _gotk4_atspi2_Device_virtual_get_locked_modifiers(void* fnptr, AtspiDevice* arg0) {
//   return ((guint (*)(AtspiDevice*))(fnptr))(arg0);
// };
// guint _gotk4_atspi2_Device_virtual_get_modifier(void* fnptr, AtspiDevice* arg0, gint arg1) {
//   return ((guint (*)(AtspiDevice*, gint))(fnptr))(arg0, arg1);
// };
// guint _gotk4_atspi2_Device_virtual_map_modifier(void* fnptr, AtspiDevice* arg0, gint arg1) {
//   return ((guint (*)(AtspiDevice*, gint))(fnptr))(arg0, arg1);
// };
// void _gotk4_atspi2_Device_virtual_generate_mouse_event(void* fnptr, AtspiDevice* arg0, AtspiAccessible* arg1, gint arg2, gint arg3, gchar* arg4, GError** arg5) {
//   ((void (*)(AtspiDevice*, AtspiAccessible*, gint, gint, gchar*, GError**))(fnptr))(arg0, arg1, arg2, arg3, arg4, arg5);
// };
// void _gotk4_atspi2_Device_virtual_remove_key_grab(void* fnptr, AtspiDevice* arg0, guint arg1) {
//   ((void (*)(AtspiDevice*, guint))(fnptr))(arg0, arg1);
// };
// void _gotk4_atspi2_Device_virtual_ungrab_keyboard(void* fnptr, AtspiDevice* arg0) {
//   ((void (*)(AtspiDevice*))(fnptr))(arg0);
// };
// void _gotk4_atspi2_Device_virtual_unmap_modifier(void* fnptr, AtspiDevice* arg0, gint arg1) {
//   ((void (*)(AtspiDevice*, gint))(fnptr))(arg0, arg1);
// };
import "C"

// GType values.
var (
	GTypeDevice = coreglib.Type(C.atspi_device_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeDevice, F: marshalDevice},
	})
}

// KeyCallback: callback that will be invoked when a key is pressed.
type KeyCallback func(device *Device, pressed bool, keycode, keysym, modifiers uint, keystring string)

// DeviceOverrides contains methods that are overridable.
type DeviceOverrides struct {
	AddKeyGrab func(kd *KeyDefinition) bool
	// GenerateMouseEvent synthesizes a mouse event at a specific screen
	// coordinate. Most AT clients should use the Action interface when
	// tempted to generate mouse events, rather than this method. Event names:
	// b1p = button 1 press; b2r = button 2 release; b3c = button 3 click; b2d =
	// button 2 double-click; abs = absolute motion; rel = relative motion.
	//
	// The function takes the following parameters:
	//
	//   - obj that should receive the click.
	//   - x indicating the x coordinate of the mouse event, relative to obj..
	//   - y indicating the y coordinate of the mouse event, relative to obj..
	//   - name: string indicating which mouse event to be synthesized (e.g.
	//     "b1p", "b1c", "b2r", "rel", "abs").
	GenerateMouseEvent func(obj *Accessible, x, y int, name string) error
	// LockedModifiers returns the locked modifiers (ie, num lock, caps lock)
	// associated with this keyboard.
	//
	// The function returns the following values:
	//
	//   - guint of modifier flags.
	LockedModifiers func() uint
	// Modifier gets the modifier for a given keycode, if one exists.
	// Does not create a new mapping. This function should be used when
	// the intention is to query a locking modifier such as num lock via
	// atspi_device_get_locked_modifiers, rather than to add key grabs.
	//
	// The function takes the following parameters:
	//
	//   - keycode to map.
	//
	// The function returns the following values:
	//
	//   - guint: modifier that is mapped to this keycode.
	Modifier func(keycode int) uint
	// GrabKeyboard attempts to grab the entire keyboard. This should only be
	// done temporarily, as it may conflict with other applications that also
	// want to grab the keyboard.
	//
	// The function returns the following values:
	//
	//   - ok if successful, LSE otherwise.
	GrabKeyboard func() bool
	// MapModifier maps the specified key code to a modifier so that it can be
	// used in conjunction with other keys to create a key grab. If the given
	// keycode is already mapped, then this function will return the modifier
	// that is currently mapped to the keycode, without doing anything else.
	// Otherwise, it will use the last modifier that AT-SPI used to map a key.
	// If no keys have yet been mapped using this device, then it will look for
	// a modifier that is not currently being used. If no unused modifier can be
	// found, then it will use the first modifier by default.
	//
	// The function takes the following parameters:
	//
	//   - keycode to map.
	//
	// The function returns the following values:
	//
	//   - guint: modifier that is now mapped to this keycode. This return value
	//     can be passed to atspi_device_add_key_grab.
	MapModifier func(keycode int) uint
	// RemoveKeyGrab removes the key grab specified by id.
	//
	// The function takes the following parameters:
	//
	//   - id: identifier of the grab to be removed.
	RemoveKeyGrab func(id uint)
	// UngrabKeyboard removes a keyboard grab added via a call to
	// atspi_device_add_keyboard.
	UngrabKeyboard func()
	// UnmapModifier removes a mapped modifier from the given keycode.
	//
	// The function takes the following parameters:
	//
	//   - keycode to unmap.
	UnmapModifier func(keycode int)
}

func defaultDeviceOverrides(v *Device) DeviceOverrides {
	return DeviceOverrides{
		AddKeyGrab:         v.addKeyGrab,
		GenerateMouseEvent: v.generateMouseEvent,
		LockedModifiers:    v.lockedModifiers,
		Modifier:           v.modifier,
		GrabKeyboard:       v.grabKeyboard,
		MapModifier:        v.mapModifier,
		RemoveKeyGrab:      v.removeKeyGrab,
		UngrabKeyboard:     v.ungrabKeyboard,
		UnmapModifier:      v.unmapModifier,
	}
}

type Device struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Device)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*Device, *DeviceClass, DeviceOverrides](
		GTypeDevice,
		initDeviceClass,
		wrapDevice,
		defaultDeviceOverrides,
	)
}

func initDeviceClass(gclass unsafe.Pointer, overrides DeviceOverrides, classInitFunc func(*DeviceClass)) {
	pclass := (*C.AtspiDeviceClass)(unsafe.Pointer(C.g_type_check_class_cast((*C.GTypeClass)(gclass), C.GType(GTypeDevice))))

	if overrides.AddKeyGrab != nil {
		pclass.add_key_grab = (*[0]byte)(C._gotk4_atspi2_DeviceClass_add_key_grab)
	}

	if overrides.GenerateMouseEvent != nil {
		pclass.generate_mouse_event = (*[0]byte)(C._gotk4_atspi2_DeviceClass_generate_mouse_event)
	}

	if overrides.LockedModifiers != nil {
		pclass.get_locked_modifiers = (*[0]byte)(C._gotk4_atspi2_DeviceClass_get_locked_modifiers)
	}

	if overrides.Modifier != nil {
		pclass.get_modifier = (*[0]byte)(C._gotk4_atspi2_DeviceClass_get_modifier)
	}

	if overrides.GrabKeyboard != nil {
		pclass.grab_keyboard = (*[0]byte)(C._gotk4_atspi2_DeviceClass_grab_keyboard)
	}

	if overrides.MapModifier != nil {
		pclass.map_modifier = (*[0]byte)(C._gotk4_atspi2_DeviceClass_map_modifier)
	}

	if overrides.RemoveKeyGrab != nil {
		pclass.remove_key_grab = (*[0]byte)(C._gotk4_atspi2_DeviceClass_remove_key_grab)
	}

	if overrides.UngrabKeyboard != nil {
		pclass.ungrab_keyboard = (*[0]byte)(C._gotk4_atspi2_DeviceClass_ungrab_keyboard)
	}

	if overrides.UnmapModifier != nil {
		pclass.unmap_modifier = (*[0]byte)(C._gotk4_atspi2_DeviceClass_unmap_modifier)
	}

	if classInitFunc != nil {
		class := (*DeviceClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapDevice(obj *coreglib.Object) *Device {
	return &Device{
		Object: obj,
	}
}

func marshalDevice(p uintptr) (interface{}, error) {
	return wrapDevice(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewDevice creates a new Device with a specified callback function.
//
// The function returns the following values:
//
//   - device: pointer to a newly-created Device.
func NewDevice() *Device {
	var _cret *C.AtspiDevice // in

	_cret = C.atspi_device_new()

	var _device *Device // out

	_device = wrapDevice(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _device
}

// GenerateMouseEvent synthesizes a mouse event at a specific screen coordinate.
// Most AT clients should use the Action interface when tempted to generate
// mouse events, rather than this method. Event names: b1p = button 1 press;
// b2r = button 2 release; b3c = button 3 click; b2d = button 2 double-click;
// abs = absolute motion; rel = relative motion.
//
// The function takes the following parameters:
//
//   - obj that should receive the click.
//   - x indicating the x coordinate of the mouse event, relative to obj..
//   - y indicating the y coordinate of the mouse event, relative to obj..
//   - name: string indicating which mouse event to be synthesized (e.g. "b1p",
//     "b1c", "b2r", "rel", "abs").
func (device *Device) GenerateMouseEvent(obj *Accessible, x, y int, name string) error {
	var _arg0 *C.AtspiDevice     // out
	var _arg1 *C.AtspiAccessible // out
	var _arg2 C.gint             // out
	var _arg3 C.gint             // out
	var _arg4 *C.gchar           // out
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg2 = C.gint(x)
	_arg3 = C.gint(y)
	_arg4 = (*C.gchar)(unsafe.Pointer(C.CString(name)))
	defer C.free(unsafe.Pointer(_arg4))

	C.atspi_device_generate_mouse_event(_arg0, _arg1, _arg2, _arg3, _arg4, &_cerr)
	runtime.KeepAlive(device)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)
	runtime.KeepAlive(name)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

func (device *Device) GrabByID(id uint) *KeyDefinition {
	var _arg0 *C.AtspiDevice        // out
	var _arg1 C.guint               // out
	var _cret *C.AtspiKeyDefinition // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = C.guint(id)

	_cret = C.atspi_device_get_grab_by_id(_arg0, _arg1)
	runtime.KeepAlive(device)
	runtime.KeepAlive(id)

	var _keyDefinition *KeyDefinition // out

	_keyDefinition = (*KeyDefinition)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_keyDefinition)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)

	return _keyDefinition
}

// LockedModifiers returns the locked modifiers (ie, num lock, caps lock)
// associated with this keyboard.
//
// The function returns the following values:
//
//   - guint of modifier flags.
func (device *Device) LockedModifiers() uint {
	var _arg0 *C.AtspiDevice // out
	var _cret C.guint        // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))

	_cret = C.atspi_device_get_locked_modifiers(_arg0)
	runtime.KeepAlive(device)

	var _guint uint // out

	_guint = uint(_cret)

	return _guint
}

// Modifier gets the modifier for a given keycode, if one exists.
// Does not create a new mapping. This function should be used when
// the intention is to query a locking modifier such as num lock via
// atspi_device_get_locked_modifiers, rather than to add key grabs.
//
// The function takes the following parameters:
//
//   - keycode to map.
//
// The function returns the following values:
//
//   - guint: modifier that is mapped to this keycode.
func (device *Device) Modifier(keycode int) uint {
	var _arg0 *C.AtspiDevice // out
	var _arg1 C.gint         // out
	var _cret C.guint        // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = C.gint(keycode)

	_cret = C.atspi_device_get_modifier(_arg0, _arg1)
	runtime.KeepAlive(device)
	runtime.KeepAlive(keycode)

	var _guint uint // out

	_guint = uint(_cret)

	return _guint
}

// GrabKeyboard attempts to grab the entire keyboard. This should only be done
// temporarily, as it may conflict with other applications that also want to
// grab the keyboard.
//
// The function returns the following values:
//
//   - ok if successful, LSE otherwise.
func (device *Device) GrabKeyboard() bool {
	var _arg0 *C.AtspiDevice // out
	var _cret C.gboolean     // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))

	_cret = C.atspi_device_grab_keyboard(_arg0)
	runtime.KeepAlive(device)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// MapModifier maps the specified key code to a modifier so that it can be used
// in conjunction with other keys to create a key grab. If the given keycode
// is already mapped, then this function will return the modifier that is
// currently mapped to the keycode, without doing anything else. Otherwise,
// it will use the last modifier that AT-SPI used to map a key. If no keys have
// yet been mapped using this device, then it will look for a modifier that is
// not currently being used. If no unused modifier can be found, then it will
// use the first modifier by default.
//
// The function takes the following parameters:
//
//   - keycode to map.
//
// The function returns the following values:
//
//   - guint: modifier that is now mapped to this keycode. This return value can
//     be passed to atspi_device_add_key_grab.
func (device *Device) MapModifier(keycode int) uint {
	var _arg0 *C.AtspiDevice // out
	var _arg1 C.gint         // out
	var _cret C.guint        // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = C.gint(keycode)

	_cret = C.atspi_device_map_modifier(_arg0, _arg1)
	runtime.KeepAlive(device)
	runtime.KeepAlive(keycode)

	var _guint uint // out

	_guint = uint(_cret)

	return _guint
}

// The function takes the following parameters:
//
//   - pressed
//   - keycode
//   - keysym
//   - state
//   - text
func (device *Device) NotifyKey(pressed bool, keycode, keysym, state int, text string) bool {
	var _arg0 *C.AtspiDevice // out
	var _arg1 C.gboolean     // out
	var _arg2 C.int          // out
	var _arg3 C.int          // out
	var _arg4 C.gint         // out
	var _arg5 *C.gchar       // out
	var _cret C.gboolean     // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	if pressed {
		_arg1 = C.TRUE
	}
	_arg2 = C.int(keycode)
	_arg3 = C.int(keysym)
	_arg4 = C.gint(state)
	_arg5 = (*C.gchar)(unsafe.Pointer(C.CString(text)))
	defer C.free(unsafe.Pointer(_arg5))

	_cret = C.atspi_device_notify_key(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5)
	runtime.KeepAlive(device)
	runtime.KeepAlive(pressed)
	runtime.KeepAlive(keycode)
	runtime.KeepAlive(keysym)
	runtime.KeepAlive(state)
	runtime.KeepAlive(text)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// RemoveKeyGrab removes the key grab specified by id.
//
// The function takes the following parameters:
//
//   - id: identifier of the grab to be removed.
func (device *Device) RemoveKeyGrab(id uint) {
	var _arg0 *C.AtspiDevice // out
	var _arg1 C.guint        // out

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = C.guint(id)

	C.atspi_device_remove_key_grab(_arg0, _arg1)
	runtime.KeepAlive(device)
	runtime.KeepAlive(id)
}

// UngrabKeyboard removes a keyboard grab added via a call to
// atspi_device_add_keyboard.
func (device *Device) UngrabKeyboard() {
	var _arg0 *C.AtspiDevice // out

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))

	C.atspi_device_ungrab_keyboard(_arg0)
	runtime.KeepAlive(device)
}

// UnmapModifier removes a mapped modifier from the given keycode.
//
// The function takes the following parameters:
//
//   - keycode to unmap.
func (device *Device) UnmapModifier(keycode int) {
	var _arg0 *C.AtspiDevice // out
	var _arg1 C.gint         // out

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = C.gint(keycode)

	C.atspi_device_unmap_modifier(_arg0, _arg1)
	runtime.KeepAlive(device)
	runtime.KeepAlive(keycode)
}

func (device *Device) addKeyGrab(kd *KeyDefinition) bool {
	gclass := (*C.AtspiDeviceClass)(coreglib.PeekParentClass(device))
	fnarg := gclass.add_key_grab

	var _arg0 *C.AtspiDevice        // out
	var _arg1 *C.AtspiKeyDefinition // out
	var _cret C.gboolean            // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = (*C.AtspiKeyDefinition)(gextras.StructNative(unsafe.Pointer(kd)))

	_cret = C._gotk4_atspi2_Device_virtual_add_key_grab(unsafe.Pointer(fnarg), _arg0, _arg1)
	runtime.KeepAlive(device)
	runtime.KeepAlive(kd)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// generateMouseEvent synthesizes a mouse event at a specific screen coordinate.
// Most AT clients should use the Action interface when tempted to generate
// mouse events, rather than this method. Event names: b1p = button 1 press;
// b2r = button 2 release; b3c = button 3 click; b2d = button 2 double-click;
// abs = absolute motion; rel = relative motion.
//
// The function takes the following parameters:
//
//   - obj that should receive the click.
//   - x indicating the x coordinate of the mouse event, relative to obj..
//   - y indicating the y coordinate of the mouse event, relative to obj..
//   - name: string indicating which mouse event to be synthesized (e.g. "b1p",
//     "b1c", "b2r", "rel", "abs").
func (device *Device) generateMouseEvent(obj *Accessible, x, y int, name string) error {
	gclass := (*C.AtspiDeviceClass)(coreglib.PeekParentClass(device))
	fnarg := gclass.generate_mouse_event

	var _arg0 *C.AtspiDevice     // out
	var _arg1 *C.AtspiAccessible // out
	var _arg2 C.gint             // out
	var _arg3 C.gint             // out
	var _arg4 *C.gchar           // out
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg2 = C.gint(x)
	_arg3 = C.gint(y)
	_arg4 = (*C.gchar)(unsafe.Pointer(C.CString(name)))
	defer C.free(unsafe.Pointer(_arg4))

	C._gotk4_atspi2_Device_virtual_generate_mouse_event(unsafe.Pointer(fnarg), _arg0, _arg1, _arg2, _arg3, _arg4, &_cerr)
	runtime.KeepAlive(device)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)
	runtime.KeepAlive(name)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// lockedModifiers returns the locked modifiers (ie, num lock, caps lock)
// associated with this keyboard.
//
// The function returns the following values:
//
//   - guint of modifier flags.
func (device *Device) lockedModifiers() uint {
	gclass := (*C.AtspiDeviceClass)(coreglib.PeekParentClass(device))
	fnarg := gclass.get_locked_modifiers

	var _arg0 *C.AtspiDevice // out
	var _cret C.guint        // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))

	_cret = C._gotk4_atspi2_Device_virtual_get_locked_modifiers(unsafe.Pointer(fnarg), _arg0)
	runtime.KeepAlive(device)

	var _guint uint // out

	_guint = uint(_cret)

	return _guint
}

// Modifier gets the modifier for a given keycode, if one exists.
// Does not create a new mapping. This function should be used when
// the intention is to query a locking modifier such as num lock via
// atspi_device_get_locked_modifiers, rather than to add key grabs.
//
// The function takes the following parameters:
//
//   - keycode to map.
//
// The function returns the following values:
//
//   - guint: modifier that is mapped to this keycode.
func (device *Device) modifier(keycode int) uint {
	gclass := (*C.AtspiDeviceClass)(coreglib.PeekParentClass(device))
	fnarg := gclass.get_modifier

	var _arg0 *C.AtspiDevice // out
	var _arg1 C.gint         // out
	var _cret C.guint        // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = C.gint(keycode)

	_cret = C._gotk4_atspi2_Device_virtual_get_modifier(unsafe.Pointer(fnarg), _arg0, _arg1)
	runtime.KeepAlive(device)
	runtime.KeepAlive(keycode)

	var _guint uint // out

	_guint = uint(_cret)

	return _guint
}

// grabKeyboard attempts to grab the entire keyboard. This should only be done
// temporarily, as it may conflict with other applications that also want to
// grab the keyboard.
//
// The function returns the following values:
//
//   - ok if successful, LSE otherwise.
func (device *Device) grabKeyboard() bool {
	gclass := (*C.AtspiDeviceClass)(coreglib.PeekParentClass(device))
	fnarg := gclass.grab_keyboard

	var _arg0 *C.AtspiDevice // out
	var _cret C.gboolean     // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))

	_cret = C._gotk4_atspi2_Device_virtual_grab_keyboard(unsafe.Pointer(fnarg), _arg0)
	runtime.KeepAlive(device)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// mapModifier maps the specified key code to a modifier so that it can be used
// in conjunction with other keys to create a key grab. If the given keycode
// is already mapped, then this function will return the modifier that is
// currently mapped to the keycode, without doing anything else. Otherwise,
// it will use the last modifier that AT-SPI used to map a key. If no keys have
// yet been mapped using this device, then it will look for a modifier that is
// not currently being used. If no unused modifier can be found, then it will
// use the first modifier by default.
//
// The function takes the following parameters:
//
//   - keycode to map.
//
// The function returns the following values:
//
//   - guint: modifier that is now mapped to this keycode. This return value can
//     be passed to atspi_device_add_key_grab.
func (device *Device) mapModifier(keycode int) uint {
	gclass := (*C.AtspiDeviceClass)(coreglib.PeekParentClass(device))
	fnarg := gclass.map_modifier

	var _arg0 *C.AtspiDevice // out
	var _arg1 C.gint         // out
	var _cret C.guint        // in

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = C.gint(keycode)

	_cret = C._gotk4_atspi2_Device_virtual_map_modifier(unsafe.Pointer(fnarg), _arg0, _arg1)
	runtime.KeepAlive(device)
	runtime.KeepAlive(keycode)

	var _guint uint // out

	_guint = uint(_cret)

	return _guint
}

// removeKeyGrab removes the key grab specified by id.
//
// The function takes the following parameters:
//
//   - id: identifier of the grab to be removed.
func (device *Device) removeKeyGrab(id uint) {
	gclass := (*C.AtspiDeviceClass)(coreglib.PeekParentClass(device))
	fnarg := gclass.remove_key_grab

	var _arg0 *C.AtspiDevice // out
	var _arg1 C.guint        // out

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = C.guint(id)

	C._gotk4_atspi2_Device_virtual_remove_key_grab(unsafe.Pointer(fnarg), _arg0, _arg1)
	runtime.KeepAlive(device)
	runtime.KeepAlive(id)
}

// ungrabKeyboard removes a keyboard grab added via a call to
// atspi_device_add_keyboard.
func (device *Device) ungrabKeyboard() {
	gclass := (*C.AtspiDeviceClass)(coreglib.PeekParentClass(device))
	fnarg := gclass.ungrab_keyboard

	var _arg0 *C.AtspiDevice // out

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))

	C._gotk4_atspi2_Device_virtual_ungrab_keyboard(unsafe.Pointer(fnarg), _arg0)
	runtime.KeepAlive(device)
}

// unmapModifier removes a mapped modifier from the given keycode.
//
// The function takes the following parameters:
//
//   - keycode to unmap.
func (device *Device) unmapModifier(keycode int) {
	gclass := (*C.AtspiDeviceClass)(coreglib.PeekParentClass(device))
	fnarg := gclass.unmap_modifier

	var _arg0 *C.AtspiDevice // out
	var _arg1 C.gint         // out

	_arg0 = (*C.AtspiDevice)(unsafe.Pointer(coreglib.InternObject(device).Native()))
	_arg1 = C.gint(keycode)

	C._gotk4_atspi2_Device_virtual_unmap_modifier(unsafe.Pointer(fnarg), _arg0, _arg1)
	runtime.KeepAlive(device)
	runtime.KeepAlive(keycode)
}

// DeviceClass: instance of this type is always passed by reference.
type DeviceClass struct {
	*deviceClass
}

// deviceClass is the struct that's finalized.
type deviceClass struct {
	native *C.AtspiDeviceClass
}
