// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
import "C"

//export _gotk4_atspi2_EventListenerCB
func _gotk4_atspi2_EventListenerCB(arg1 *C.AtspiEvent, arg2 *C.void) {
	var fn EventListenerCB
	{
		v := gbox.Get(uintptr(arg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(EventListenerCB)
	}

	var _event *Event // out

	_event = (*Event)(gextras.NewStructNative(unsafe.Pointer(arg1)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_event)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)

	fn(_event)
}
