// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
// extern void callbackDelete(gpointer);
// extern void _gotk4_atspi2_EventListenerCB(AtspiEvent*, void*);
import "C"

// GType values.
var (
	GTypeEventListener = coreglib.Type(C.atspi_event_listener_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeEventListener, F: marshalEventListener},
	})
}

// EventListenerCB: function prototype for callbacks via which clients are
// notified of AT-SPI events.
type EventListenerCB func(event *Event)

// EventListenerOverrides contains methods that are overridable.
type EventListenerOverrides struct {
}

func defaultEventListenerOverrides(v *EventListener) EventListenerOverrides {
	return EventListenerOverrides{}
}

// EventListener: generic interface implemented by objects for the receipt of
// event notifications.
//
// A generic interface implemented by objects for the receipt of event
// notifications. atspi-event-listener is the interface via which clients of
// the atspi-registry receive notification of changes to an application's user
// interface and content.
type EventListener struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*EventListener)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*EventListener, *EventListenerClass, EventListenerOverrides](
		GTypeEventListener,
		initEventListenerClass,
		wrapEventListener,
		defaultEventListenerOverrides,
	)
}

func initEventListenerClass(gclass unsafe.Pointer, overrides EventListenerOverrides, classInitFunc func(*EventListenerClass)) {
	if classInitFunc != nil {
		class := (*EventListenerClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapEventListener(obj *coreglib.Object) *EventListener {
	return &EventListener{
		Object: obj,
	}
}

func marshalEventListener(p uintptr) (interface{}, error) {
	return wrapEventListener(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewEventListener creates a new EventListener associated with a specified
// callback.
//
// The function takes the following parameters:
//
//   - callback to be called when an event is fired.
//
// The function returns the following values:
//
//   - eventListener: new EventListener.
func NewEventListener(callback EventListenerCB) *EventListener {
	var _arg1 C.AtspiEventListenerCB // out
	var _arg2 C.gpointer
	var _arg3 C.GDestroyNotify
	var _cret *C.AtspiEventListener // in

	_arg1 = (*[0]byte)(C._gotk4_atspi2_EventListenerCB)
	_arg2 = C.gpointer(gbox.Assign(callback))
	_arg3 = (C.GDestroyNotify)((*[0]byte)(C.callbackDelete))

	_cret = C.atspi_event_listener_new(_arg1, _arg2, _arg3)
	runtime.KeepAlive(callback)

	var _eventListener *EventListener // out

	_eventListener = wrapEventListener(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _eventListener
}

// Deregister deregisters an EventListener from the registry, for a specific
// event type.
//
// The function takes the following parameters:
//
//   - eventType: string specifying the event type for which this listener is to
//     be deregistered.
func (listener *EventListener) Deregister(eventType string) error {
	var _arg0 *C.AtspiEventListener // out
	var _arg1 *C.gchar              // out
	var _cerr *C.GError             // in

	_arg0 = (*C.AtspiEventListener)(unsafe.Pointer(coreglib.InternObject(listener).Native()))
	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(eventType)))
	defer C.free(unsafe.Pointer(_arg1))

	C.atspi_event_listener_deregister(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(listener)
	runtime.KeepAlive(eventType)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// Register adds an in-process callback function to an existing EventListener.
//
// Legal object event types:
//
//	  (property change events)
//
//	          object:property-change
//	          object:property-change:accessible-name
//	          object:property-change:accessible-description
//	          object:property-change:accessible-parent
//	          object:property-change:accessible-value
//	          object:property-change:accessible-role
//	          object:property-change:accessible-table-caption
//	          object:property-change:accessible-table-column-description
//	          object:property-change:accessible-table-column-header
//	          object:property-change:accessible-table-row-description
//	          object:property-change:accessible-table-row-header
//	          object:property-change:accessible-table-summary
//
//	  (other object events)
//
//	          object:state-changed
//	          object:children-changed
//	          object:visible-data-changed
//	          object:selection-changed
//	          object:text-selection-changed
//	          object:text-changed
//	          object:text-caret-moved
//	          object:row-inserted
//	          object:row-reordered
//	          object:row-deleted
//	          object:column-inserted
//	          object:column-reordered
//	          object:column-deleted
//	          object:model-changed
//	          object:active-descendant-changed
//	          object:announcement
//
//	(screen reader events)
//	           screen-reader:region-changed
//
//	(window events)
//
//	          window:minimize
//	          window:maximize
//	          window:restore
//	          window:close
//	          window:create
//	          window:reparent
//	          window:desktop-create
//	          window:desktop-destroy
//	          window:activate
//	          window:deactivate
//	          window:raise
//	          window:lower
//	          window:move
//	          window:resize
//	          window:shade
//	          window:unshade
//	          window:restyle
//
//	(other events)
//
//	          focus:
//	          mouse:abs
//	          mouse:rel
//	          mouse:b1p
//	          mouse:b1r
//	          mouse:b2p
//	          mouse:b2r
//	          mouse:b3p
//	          mouse:b3r
//
// NOTE: this character string may be UTF-8, but should not contain byte value
// 56 (ascii ':'), except as a delimiter, since non-UTF-8 string delimiting
// functions are used internally. In general, listening to toolkit-specific
// events is not recommended.
//
// Currently, object:text-reading-position needs to be specified explicitly (it
// is not implied by object:text), since it is generated by the screen reader
// and is thus a special case internally.
//
// The function takes the following parameters:
//
//   - eventType: character string indicating the type of
//     events for which notification is requested. Format is
//     EventClass:major_type:minor_type:detail where all subfields other
//     than EventClass are optional. EventClasses include "object", "window",
//     "mouse", and toolkit events (e.g. "Gtk", "AWT"). Examples: "focus:",
//     "Gtk:GtkWidget:button_press_event".
func (listener *EventListener) Register(eventType string) error {
	var _arg0 *C.AtspiEventListener // out
	var _arg1 *C.gchar              // out
	var _cerr *C.GError             // in

	_arg0 = (*C.AtspiEventListener)(unsafe.Pointer(coreglib.InternObject(listener).Native()))
	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(eventType)))
	defer C.free(unsafe.Pointer(_arg1))

	C.atspi_event_listener_register(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(listener)
	runtime.KeepAlive(eventType)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// EventListenerClass: instance of this type is always passed by reference.
type EventListenerClass struct {
	*eventListenerClass
}

// eventListenerClass is the struct that's finalized.
type eventListenerClass struct {
	native *C.AtspiEventListenerClass
}
