// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeCollection = coreglib.Type(C.atspi_collection_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeCollection, F: marshalCollection},
	})
}

// Collection: interface designed to allow accessibles which satisfy a set of
// criteria to be returned.
//
// An interface designed to allow accessibles which satisfy a set of criteria
// to be returned. This interface can be used to avoid iteration or client-side
// search of the object tree.
//
// Collection wraps an interface. This means the user can get the
// underlying type by calling Cast().
type Collection struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Collection)(nil)
)

// Collectioner describes Collection's interface methods.
type Collectioner interface {
	coreglib.Objector

	ActiveDescendant() (*Accessible, error)
	// Matches gets all Accessible objects from the collection matching a given
	// rule.
	Matches(rule *MatchRule, sortby CollectionSortOrder, count int, traverse bool) ([]*Accessible, error)
	// MatchesFrom gets all Accessible objects from the collection, before
	// current_object, matching a given rule.
	MatchesFrom(currentObject *Accessible, rule *MatchRule, sortby CollectionSortOrder, tree CollectionTreeTraversalType, count int, traverse bool) ([]*Accessible, error)
	// MatchesTo gets all Accessible objects from the collection, after
	// current_object, matching a given rule.
	MatchesTo(currentObject *Accessible, rule *MatchRule, sortby CollectionSortOrder, tree CollectionTreeTraversalType, limitScope bool, count int, traverse bool) ([]*Accessible, error)
	// IsAncestorOf: not yet implemented.
	IsAncestorOf(test *Accessible) error
}

var _ Collectioner = (*Collection)(nil)

func wrapCollection(obj *coreglib.Object) *Collection {
	return &Collection{
		Object: obj,
	}
}

func marshalCollection(p uintptr) (interface{}, error) {
	return wrapCollection(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// The function returns the following values:
//
//   - accessible: active descendant of the given object. Not yet implemented.
func (collection *Collection) ActiveDescendant() (*Accessible, error) {
	var _arg0 *C.AtspiCollection // out
	var _cret *C.AtspiAccessible // in
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiCollection)(unsafe.Pointer(coreglib.InternObject(collection).Native()))

	_cret = C.atspi_collection_get_active_descendant(_arg0, &_cerr)
	runtime.KeepAlive(collection)

	var _accessible *Accessible // out
	var _goerr error            // out

	_accessible = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessible, _goerr
}

// Matches gets all Accessible objects from the collection matching a given
// rule.
//
// The function takes the following parameters:
//
//   - rule describing the match criteria.
//   - sortby specifying the way the results are to be sorted.
//   - count: maximum number of results to return, or 0 for no limit.
//   - traverse: not supported.
//
// The function returns the following values:
//
//   - accessibles: all Accessible objects matching the given match rule.
func (collection *Collection) Matches(rule *MatchRule, sortby CollectionSortOrder, count int, traverse bool) ([]*Accessible, error) {
	var _arg0 *C.AtspiCollection         // out
	var _arg1 *C.AtspiMatchRule          // out
	var _arg2 C.AtspiCollectionSortOrder // out
	var _arg3 C.gint                     // out
	var _arg4 C.gboolean                 // out
	var _cret *C.GArray                  // in
	var _cerr *C.GError                  // in

	_arg0 = (*C.AtspiCollection)(unsafe.Pointer(coreglib.InternObject(collection).Native()))
	_arg1 = (*C.AtspiMatchRule)(unsafe.Pointer(coreglib.InternObject(rule).Native()))
	_arg2 = C.AtspiCollectionSortOrder(sortby)
	_arg3 = C.gint(count)
	if traverse {
		_arg4 = C.TRUE
	}

	_cret = C.atspi_collection_get_matches(_arg0, _arg1, _arg2, _arg3, _arg4, &_cerr)
	runtime.KeepAlive(collection)
	runtime.KeepAlive(rule)
	runtime.KeepAlive(sortby)
	runtime.KeepAlive(count)
	runtime.KeepAlive(traverse)

	var _accessibles []*Accessible // out
	var _goerr error               // out

	{
		var len uintptr
		p := C.g_array_steal(&_cret, (*C.gsize)(&len))
		src := unsafe.Slice((*C.GArray)(p), len)
		_accessibles = make([]*Accessible, len)
		for i := 0; i < len; i++ {
			_accessibles[i] = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(&src[i])))
		}
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessibles, _goerr
}

// MatchesFrom gets all Accessible objects from the collection, before
// current_object, matching a given rule.
//
// The function takes the following parameters:
//
//   - currentObject: upon reaching this object, searching should stop.
//   - rule describing the match criteria.
//   - sortby specifying the way the results are to be sorted.
//   - tree specifying restrictions on the objects to be traversed.
//   - count: maximum number of results to return, or 0 for no limit.
//   - traverse: not supported.
//
// The function returns the following values:
//
//   - accessibles: all Accessible objects matching the given match rule that
//     preceed current_object.
func (collection *Collection) MatchesFrom(currentObject *Accessible, rule *MatchRule, sortby CollectionSortOrder, tree CollectionTreeTraversalType, count int, traverse bool) ([]*Accessible, error) {
	var _arg0 *C.AtspiCollection                 // out
	var _arg1 *C.AtspiAccessible                 // out
	var _arg2 *C.AtspiMatchRule                  // out
	var _arg3 C.AtspiCollectionSortOrder         // out
	var _arg4 C.AtspiCollectionTreeTraversalType // out
	var _arg5 C.gint                             // out
	var _arg6 C.gboolean                         // out
	var _cret *C.GArray                          // in
	var _cerr *C.GError                          // in

	_arg0 = (*C.AtspiCollection)(unsafe.Pointer(coreglib.InternObject(collection).Native()))
	_arg1 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(currentObject).Native()))
	_arg2 = (*C.AtspiMatchRule)(unsafe.Pointer(coreglib.InternObject(rule).Native()))
	_arg3 = C.AtspiCollectionSortOrder(sortby)
	_arg4 = C.AtspiCollectionTreeTraversalType(tree)
	_arg5 = C.gint(count)
	if traverse {
		_arg6 = C.TRUE
	}

	_cret = C.atspi_collection_get_matches_from(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, &_cerr)
	runtime.KeepAlive(collection)
	runtime.KeepAlive(currentObject)
	runtime.KeepAlive(rule)
	runtime.KeepAlive(sortby)
	runtime.KeepAlive(tree)
	runtime.KeepAlive(count)
	runtime.KeepAlive(traverse)

	var _accessibles []*Accessible // out
	var _goerr error               // out

	{
		var len uintptr
		p := C.g_array_steal(&_cret, (*C.gsize)(&len))
		src := unsafe.Slice((*C.GArray)(p), len)
		_accessibles = make([]*Accessible, len)
		for i := 0; i < len; i++ {
			_accessibles[i] = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(&src[i])))
		}
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessibles, _goerr
}

// MatchesTo gets all Accessible objects from the collection, after
// current_object, matching a given rule.
//
// The function takes the following parameters:
//
//   - currentObject: object at which to start searching.
//   - rule describing the match criteria.
//   - sortby specifying the way the results are to be sorted.
//   - tree specifying restrictions on the objects to be traversed.
//   - limitScope: if UE, only descendants of current_object's parent will be
//     returned. Otherwise (if LSE), any accessible may be returned if it would
//     preceed current_object in a flattened hierarchy.
//   - count: maximum number of results to return, or 0 for no limit.
//   - traverse: not supported.
//
// The function returns the following values:
//
//   - accessibles: all Accessible objects matching the given match rule after
//     current_object.
func (collection *Collection) MatchesTo(currentObject *Accessible, rule *MatchRule, sortby CollectionSortOrder, tree CollectionTreeTraversalType, limitScope bool, count int, traverse bool) ([]*Accessible, error) {
	var _arg0 *C.AtspiCollection                 // out
	var _arg1 *C.AtspiAccessible                 // out
	var _arg2 *C.AtspiMatchRule                  // out
	var _arg3 C.AtspiCollectionSortOrder         // out
	var _arg4 C.AtspiCollectionTreeTraversalType // out
	var _arg5 C.gboolean                         // out
	var _arg6 C.gint                             // out
	var _arg7 C.gboolean                         // out
	var _cret *C.GArray                          // in
	var _cerr *C.GError                          // in

	_arg0 = (*C.AtspiCollection)(unsafe.Pointer(coreglib.InternObject(collection).Native()))
	_arg1 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(currentObject).Native()))
	_arg2 = (*C.AtspiMatchRule)(unsafe.Pointer(coreglib.InternObject(rule).Native()))
	_arg3 = C.AtspiCollectionSortOrder(sortby)
	_arg4 = C.AtspiCollectionTreeTraversalType(tree)
	if limitScope {
		_arg5 = C.TRUE
	}
	_arg6 = C.gint(count)
	if traverse {
		_arg7 = C.TRUE
	}

	_cret = C.atspi_collection_get_matches_to(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, &_cerr)
	runtime.KeepAlive(collection)
	runtime.KeepAlive(currentObject)
	runtime.KeepAlive(rule)
	runtime.KeepAlive(sortby)
	runtime.KeepAlive(tree)
	runtime.KeepAlive(limitScope)
	runtime.KeepAlive(count)
	runtime.KeepAlive(traverse)

	var _accessibles []*Accessible // out
	var _goerr error               // out

	{
		var len uintptr
		p := C.g_array_steal(&_cret, (*C.gsize)(&len))
		src := unsafe.Slice((*C.GArray)(p), len)
		_accessibles = make([]*Accessible, len)
		for i := 0; i < len; i++ {
			_accessibles[i] = wrapAccessible(coreglib.AssumeOwnership(unsafe.Pointer(&src[i])))
		}
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _accessibles, _goerr
}

// IsAncestorOf: not yet implemented.
func (collection *Collection) IsAncestorOf(test *Accessible) error {
	var _arg0 *C.AtspiCollection // out
	var _arg1 *C.AtspiAccessible // out
	var _cerr *C.GError          // in

	_arg0 = (*C.AtspiCollection)(unsafe.Pointer(coreglib.InternObject(collection).Native()))
	_arg1 = (*C.AtspiAccessible)(unsafe.Pointer(coreglib.InternObject(test).Native()))

	C.atspi_collection_is_ancestor_of(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(collection)
	runtime.KeepAlive(test)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}
