// Code generated by girgen. DO NOT EDIT.

package atspi

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <atspi/atspi.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeText      = coreglib.Type(C.atspi_text_get_type())
	GTypeRange     = coreglib.Type(C.atspi_range_get_type())
	GTypeTextRange = coreglib.Type(C.atspi_text_range_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeText, F: marshalText},
		coreglib.TypeMarshaler{T: GTypeRange, F: marshalRange},
		coreglib.TypeMarshaler{T: GTypeTextRange, F: marshalTextRange},
	})
}

// Text: interface implemented by objects which place textual information
// onscreen.
//
// The text interface should be implemented by objects which place textual
// information onscreen as character strings or glyphs. The text interface
// allows access to textual content including display attributes and semantic
// hints associated with runs of text, and to bounding information for glyphs
// and substrings. It also allows portions of text to be selected, if the
// objects StateSet includes STATE_SELECTABLE_TEXT.
//
// Text wraps an interface. This means the user can get the
// underlying type by calling Cast().
type Text struct {
	_ [0]func() // equal guard
	*coreglib.Object
}

var (
	_ coreglib.Objector = (*Text)(nil)
)

// Texter describes Text's interface methods.
type Texter interface {
	coreglib.Objector

	// AddSelection selects some text (adds a text selection) in an Text object.
	AddSelection(startOffset, endOffset int) error
	// AttributeRun gets a set of attributes applied to a range of text from an
	// Text object, optionally including its 'default' attributes.
	AttributeRun(offset int, includeDefaults bool) (startOffset, endOffset int, hashTable map[string]string, goerr error)
	// TextAttributeValue gets the value of a named attribute at a given offset.
	TextAttributeValue(offset int, attributeName string) (string, error)
	// TextAttributes gets the attributes applied to a range of text from an
	// Text object.
	TextAttributes(offset int) (startOffset, endOffset int, hashTable map[string]string, goerr error)
	// BoundedRanges gets the ranges of text from an Text object which lie
	// within the bounds defined by (x, y) and (x+width, y+height).
	BoundedRanges(x, y, width, height int, typ CoordType, clipTypeX, clipTypeY TextClipType) ([]TextRange, error)
	// CaretOffset gets the current offset of the text caret in an Text object.
	CaretOffset() (int, error)
	// CharacterAtOffset gets the character at a given offset for an Text
	// object.
	CharacterAtOffset(offset int) (uint, error)
	// CharacterCount gets the character count of an Text object.
	CharacterCount() (int, error)
	// CharacterExtents gets a bounding box containing the glyph representing
	// the character at a particular text offset.
	CharacterExtents(offset int, typ CoordType) (*Rect, error)
	// DefaultAttributes gets the default attributes applied to an Text object.
	DefaultAttributes() (map[string]string, error)
	// NSelections gets the number of active non-contiguous selections for an
	// Text object.
	NSelections() (int, error)
	// OffsetAtPoint gets the character offset into the text at a given point.
	OffsetAtPoint(x, y int, typ CoordType) (int, error)
	// RangeExtents gets the bounding box for text within a range in an Text
	// object.
	RangeExtents(startOffset, endOffset int, typ CoordType) (*Rect, error)
	// Selection gets the bounds of the selection_num-th active text selection
	// for an Text object.
	Selection(selectionNum int) (*Range, error)
	// StringAtOffset gets a portion of the text exposed through an Text
	// according to a given offset and a specific granularity, along with the
	// start and end offsets defining the boundaries of such a portion of text.
	StringAtOffset(offset int, granularity TextGranularity) (*TextRange, error)
	// Text gets a range of text from an Text object.
	Text(startOffset, endOffset int) (string, error)
	// TextAfterOffset gets delimited text from an Text object which follows a
	// given text offset.
	TextAfterOffset(offset int, typ TextBoundaryType) (*TextRange, error)
	// TextAtOffset gets delimited text from an Text object which includes a
	// given text offset.
	TextAtOffset(offset int, typ TextBoundaryType) (*TextRange, error)
	// TextBeforeOffset gets delimited text from an Text object which precedes a
	// given text offset.
	TextBeforeOffset(offset int, typ TextBoundaryType) (*TextRange, error)
	// RemoveSelection de-selects a text selection.
	RemoveSelection(selectionNum int) error
	// ScrollSubstringTo scrolls whatever container of the Text text range so it
	// becomes visible on the screen.
	ScrollSubstringTo(startOffset, endOffset int, typ ScrollType) error
	// ScrollSubstringToPoint scrolls whatever container of the Text text range
	// so it becomes visible on the screen at a given position.
	ScrollSubstringToPoint(startOffset, endOffset int, coords CoordType, x, y int) error
	// SetCaretOffset moves the text caret to a given position.
	SetCaretOffset(newOffset int) error
	// SetSelection changes the bounds of an existing Text text selection.
	SetSelection(selectionNum, startOffset, endOffset int) error
}

var _ Texter = (*Text)(nil)

func wrapText(obj *coreglib.Object) *Text {
	return &Text{
		Object: obj,
	}
}

func marshalText(p uintptr) (interface{}, error) {
	return wrapText(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// AddSelection selects some text (adds a text selection) in an Text object.
//
// The function takes the following parameters:
//
//   - startOffset: starting offset of the desired new selection.
//   - endOffset: offset of the first character after the new selection.
func (obj *Text) AddSelection(startOffset, endOffset int) error {
	var _arg0 *C.AtspiText // out
	var _arg1 C.gint       // out
	var _arg2 C.gint       // out
	var _cerr *C.GError    // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(startOffset)
	_arg2 = C.gint(endOffset)

	C.atspi_text_add_selection(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(startOffset)
	runtime.KeepAlive(endOffset)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// AttributeRun gets a set of attributes applied to a range of text from an Text
// object, optionally including its 'default' attributes.
//
// The function takes the following parameters:
//
//   - offset indicating the offset from which the attribute search is based.
//   - includeDefaults that, when set as LSE, indicates the call should only
//     return those attributes which are explicitly set on the current attribute
//     run, omitting any attributes which are inherited from the default values.
//
// The function returns the following values:
//
//   - startOffset pointer indicating the start of the desired text range.
//   - endOffset pointer indicating the first character past the desired range.
//   - hashTable with attributes defined at the indicated offset, optionally
//     including the 'default' ones.
func (obj *Text) AttributeRun(offset int, includeDefaults bool) (startOffset, endOffset int, hashTable map[string]string, goerr error) {
	var _arg0 *C.AtspiText  // out
	var _arg1 C.gint        // out
	var _arg2 C.gboolean    // out
	var _arg3 C.gint        // in
	var _arg4 C.gint        // in
	var _cret *C.GHashTable // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(offset)
	if includeDefaults {
		_arg2 = C.TRUE
	}

	_cret = C.atspi_text_get_attribute_run(_arg0, _arg1, _arg2, &_arg3, &_arg4, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(offset)
	runtime.KeepAlive(includeDefaults)

	var _startOffset int             // out
	var _endOffset int               // out
	var _hashTable map[string]string // out
	var _goerr error                 // out

	_startOffset = int(_arg3)
	_endOffset = int(_arg4)
	_hashTable = make(map[string]string, gextras.HashTableSize(unsafe.Pointer(_cret)))
	gextras.MoveHashTable(unsafe.Pointer(_cret), true, func(k, v unsafe.Pointer) {
		ksrc := *(**C.gchar)(k)
		vsrc := *(**C.gchar)(v)
		var kdst string // out
		var vdst string // out
		kdst = C.GoString((*C.gchar)(unsafe.Pointer(ksrc)))
		defer C.free(unsafe.Pointer(ksrc))
		vdst = C.GoString((*C.gchar)(unsafe.Pointer(vsrc)))
		defer C.free(unsafe.Pointer(vsrc))
		_hashTable[kdst] = vdst
	})
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _startOffset, _endOffset, _hashTable, _goerr
}

// TextAttributeValue gets the value of a named attribute at a given offset.
//
// Deprecated: Use atspi_text_get_text_attribute_value instead.
//
// The function takes the following parameters:
//
//   - offset: character offset at which to query the attribute.
//   - attributeName: attribute to query.
//
// The function returns the following values:
//
//   - utf8 (optional): value of a given attribute at the given offset, or NULL
//     if not present.
func (obj *Text) TextAttributeValue(offset int, attributeName string) (string, error) {
	var _arg0 *C.AtspiText // out
	var _arg1 C.gint       // out
	var _arg2 *C.gchar     // out
	var _cret *C.gchar     // in
	var _cerr *C.GError    // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(offset)
	_arg2 = (*C.gchar)(unsafe.Pointer(C.CString(attributeName)))
	defer C.free(unsafe.Pointer(_arg2))

	_cret = C.atspi_text_get_attribute_value(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(offset)
	runtime.KeepAlive(attributeName)

	var _utf8 string // out
	var _goerr error // out

	if _cret != nil {
		_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
		defer C.free(unsafe.Pointer(_cret))
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// TextAttributes gets the attributes applied to a range of text from an Text
// object. The text attributes correspond to CSS attributes where possible.
//
// Deprecated: Use atspi_text_get_text_attributes instead.
//
// The function takes the following parameters:
//
//   - offset indicating the offset from which the attribute search is based.
//
// The function returns the following values:
//
//   - startOffset pointer indicating the start of the desired text range.
//   - endOffset pointer indicating the first character past the desired range.
//   - hashTable the attributes at the given character offset.
func (obj *Text) TextAttributes(offset int) (startOffset, endOffset int, hashTable map[string]string, goerr error) {
	var _arg0 *C.AtspiText  // out
	var _arg1 C.gint        // out
	var _arg2 C.gint        // in
	var _arg3 C.gint        // in
	var _cret *C.GHashTable // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(offset)

	_cret = C.atspi_text_get_attributes(_arg0, _arg1, &_arg2, &_arg3, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(offset)

	var _startOffset int             // out
	var _endOffset int               // out
	var _hashTable map[string]string // out
	var _goerr error                 // out

	_startOffset = int(_arg2)
	_endOffset = int(_arg3)
	_hashTable = make(map[string]string, gextras.HashTableSize(unsafe.Pointer(_cret)))
	gextras.MoveHashTable(unsafe.Pointer(_cret), true, func(k, v unsafe.Pointer) {
		ksrc := *(**C.gchar)(k)
		vsrc := *(**C.gchar)(v)
		var kdst string // out
		var vdst string // out
		kdst = C.GoString((*C.gchar)(unsafe.Pointer(ksrc)))
		defer C.free(unsafe.Pointer(ksrc))
		vdst = C.GoString((*C.gchar)(unsafe.Pointer(vsrc)))
		defer C.free(unsafe.Pointer(vsrc))
		_hashTable[kdst] = vdst
	})
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _startOffset, _endOffset, _hashTable, _goerr
}

// BoundedRanges gets the ranges of text from an Text object which lie within
// the bounds defined by (x, y) and (x+width, y+height).
//
// The function takes the following parameters:
//
//   - x: 'starting' x coordinate of the bounding box.
//   - y: 'starting' y coordinate of the bounding box.
//   - width: x extent of the bounding box.
//   - height: y extent of the bounding box.
//   - typ indicating the coordinate system to use for the returned values.
//   - clipTypeX indicating how to treat characters that intersect the bounding
//     box's x extents.
//   - clipTypeY indicating how to treat characters that intersect the bounding
//     box's y extents.
//
// The function returns the following values:
//
//   - textRanges: null-terminated list of pointers to TextRange structs
//     detailing the bounded text.
func (obj *Text) BoundedRanges(x, y, width, height int, typ CoordType, clipTypeX, clipTypeY TextClipType) ([]TextRange, error) {
	var _arg0 *C.AtspiText        // out
	var _arg1 C.gint              // out
	var _arg2 C.gint              // out
	var _arg3 C.gint              // out
	var _arg4 C.gint              // out
	var _arg5 C.AtspiCoordType    // out
	var _arg6 C.AtspiTextClipType // out
	var _arg7 C.AtspiTextClipType // out
	var _cret *C.GArray           // in
	var _cerr *C.GError           // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(x)
	_arg2 = C.gint(y)
	_arg3 = C.gint(width)
	_arg4 = C.gint(height)
	_arg5 = C.AtspiCoordType(typ)
	_arg6 = C.AtspiTextClipType(clipTypeX)
	_arg7 = C.AtspiTextClipType(clipTypeY)

	_cret = C.atspi_text_get_bounded_ranges(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)
	runtime.KeepAlive(width)
	runtime.KeepAlive(height)
	runtime.KeepAlive(typ)
	runtime.KeepAlive(clipTypeX)
	runtime.KeepAlive(clipTypeY)

	var _textRanges []TextRange // out
	var _goerr error            // out

	{
		var len uintptr
		p := C.g_array_steal(&_cret, (*C.gsize)(&len))
		src := unsafe.Slice((*C.GArray)(p), len)
		_textRanges = make([]TextRange, len)
		for i := 0; i < len; i++ {
			_textRanges[i] = *(*TextRange)(gextras.NewStructNative(unsafe.Pointer((&src[i]))))
			runtime.SetFinalizer(
				gextras.StructIntern(unsafe.Pointer(&_textRanges[i])),
				func(intern *struct{ C unsafe.Pointer }) {
					C.free(intern.C)
				},
			)
		}
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _textRanges, _goerr
}

// CaretOffset gets the current offset of the text caret in an Text object.
//
// The function returns the following values:
//
//   - gint indicating the current position of the text caret.
func (obj *Text) CaretOffset() (int, error) {
	var _arg0 *C.AtspiText // out
	var _cret C.gint       // in
	var _cerr *C.GError    // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_text_get_caret_offset(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// CharacterAtOffset gets the character at a given offset for an Text object.
//
// The function takes the following parameters:
//
//   - offset indicating the text offset where the desired character is located.
//
// The function returns the following values:
//
//   - guint representing the UCS-4 unicode code point of the given character,
//     or 0xFFFFFFFF if the character in question cannot be represented in the
//     UCS-4 encoding.
func (obj *Text) CharacterAtOffset(offset int) (uint, error) {
	var _arg0 *C.AtspiText // out
	var _arg1 C.gint       // out
	var _cret C.guint      // in
	var _cerr *C.GError    // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(offset)

	_cret = C.atspi_text_get_character_at_offset(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(offset)

	var _guint uint  // out
	var _goerr error // out

	_guint = uint(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _guint, _goerr
}

// CharacterCount gets the character count of an Text object.
//
// The function returns the following values:
//
//   - gint indicating the total number of characters in the Text object.
func (obj *Text) CharacterCount() (int, error) {
	var _arg0 *C.AtspiText // out
	var _cret C.gint       // in
	var _cerr *C.GError    // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_text_get_character_count(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// CharacterExtents gets a bounding box containing the glyph representing the
// character at a particular text offset. The returned values are meaningful
// only if the Text has both STATE_VISIBLE and STATE_SHOWING.
//
// The function takes the following parameters:
//
//   - offset indicating the offset of the text character for whom boundary
//     information is requested.
//   - typ indicating the coordinate system to use for the returned values.
//
// The function returns the following values:
//
//   - rect specifying the position and size of the character.
func (obj *Text) CharacterExtents(offset int, typ CoordType) (*Rect, error) {
	var _arg0 *C.AtspiText     // out
	var _arg1 C.gint           // out
	var _arg2 C.AtspiCoordType // out
	var _cret *C.AtspiRect     // in
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(offset)
	_arg2 = C.AtspiCoordType(typ)

	_cret = C.atspi_text_get_character_extents(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(offset)
	runtime.KeepAlive(typ)

	var _rect *Rect  // out
	var _goerr error // out

	_rect = (*Rect)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_rect)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _rect, _goerr
}

// DefaultAttributes gets the default attributes applied to an Text object.
// The text attributes correspond to CSS attributes where possible.
// The combination of this attribute set and the attributes reported by
// #atspi_text_get_attributes describes the entire set of text attributes over a
// range.
//
// The function returns the following values:
//
//   - hashTable: Table containing the default attributes applied to a text
//     object, (exclusive of explicitly-set attributes), encoded as UTF-8.
func (obj *Text) DefaultAttributes() (map[string]string, error) {
	var _arg0 *C.AtspiText  // out
	var _cret *C.GHashTable // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_text_get_default_attributes(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _hashTable map[string]string // out
	var _goerr error                 // out

	_hashTable = make(map[string]string, gextras.HashTableSize(unsafe.Pointer(_cret)))
	gextras.MoveHashTable(unsafe.Pointer(_cret), true, func(k, v unsafe.Pointer) {
		ksrc := *(**C.gchar)(k)
		vsrc := *(**C.gchar)(v)
		var kdst string // out
		var vdst string // out
		kdst = C.GoString((*C.gchar)(unsafe.Pointer(ksrc)))
		defer C.free(unsafe.Pointer(ksrc))
		vdst = C.GoString((*C.gchar)(unsafe.Pointer(vsrc)))
		defer C.free(unsafe.Pointer(vsrc))
		_hashTable[kdst] = vdst
	})
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _hashTable, _goerr
}

// NSelections gets the number of active non-contiguous selections for an Text
// object.
//
// The function returns the following values:
//
//   - gint indicating the current number of non-contiguous text selections
//     active within an Text object.
func (obj *Text) NSelections() (int, error) {
	var _arg0 *C.AtspiText // out
	var _cret C.gint       // in
	var _cerr *C.GError    // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))

	_cret = C.atspi_text_get_n_selections(_arg0, &_cerr)
	runtime.KeepAlive(obj)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// OffsetAtPoint gets the character offset into the text at a given point.
//
// The function takes the following parameters:
//
//   - x coordinate of the point to be queried.
//   - y coordinate of the point to be queried.
//   - typ indicating the coordinate system in which the values should be
//     returned.
//
// The function returns the following values:
//
//   - gint: offset (as a #gint) at the point (x, y) in the specified coordinate
//     system.
func (obj *Text) OffsetAtPoint(x, y int, typ CoordType) (int, error) {
	var _arg0 *C.AtspiText     // out
	var _arg1 C.gint           // out
	var _arg2 C.gint           // out
	var _arg3 C.AtspiCoordType // out
	var _cret C.gint           // in
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(x)
	_arg2 = C.gint(y)
	_arg3 = C.AtspiCoordType(typ)

	_cret = C.atspi_text_get_offset_at_point(_arg0, _arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)
	runtime.KeepAlive(typ)

	var _gint int    // out
	var _goerr error // out

	_gint = int(_cret)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _gint, _goerr
}

// RangeExtents gets the bounding box for text within a range in an Text object.
// The returned values are meaningful only if the Text has both STATE_VISIBLE
// and STATE_SHOWING.
//
// The function takes the following parameters:
//
//   - startOffset indicating the offset of the first text character for whom
//     boundary information is requested.
//   - endOffset indicating the offset of the text character after the last
//     character for whom boundary information is requested.
//   - typ indicating the coordinate system to use for the returned values.
//
// The function returns the following values:
//
//   - rect giving the position and size of the specified range of text.
func (obj *Text) RangeExtents(startOffset, endOffset int, typ CoordType) (*Rect, error) {
	var _arg0 *C.AtspiText     // out
	var _arg1 C.gint           // out
	var _arg2 C.gint           // out
	var _arg3 C.AtspiCoordType // out
	var _cret *C.AtspiRect     // in
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(startOffset)
	_arg2 = C.gint(endOffset)
	_arg3 = C.AtspiCoordType(typ)

	_cret = C.atspi_text_get_range_extents(_arg0, _arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(startOffset)
	runtime.KeepAlive(endOffset)
	runtime.KeepAlive(typ)

	var _rect *Rect  // out
	var _goerr error // out

	_rect = (*Rect)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_rect)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _rect, _goerr
}

// Selection gets the bounds of the selection_num-th active text selection for
// an Text object.
//
// The function takes the following parameters:
//
//   - selectionNum indicating which selection to query.
func (obj *Text) Selection(selectionNum int) (*Range, error) {
	var _arg0 *C.AtspiText  // out
	var _arg1 C.gint        // out
	var _cret *C.AtspiRange // in
	var _cerr *C.GError     // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(selectionNum)

	_cret = C.atspi_text_get_selection(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(selectionNum)

	var __range *Range // out
	var _goerr error   // out

	__range = (*Range)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(__range)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return __range, _goerr
}

// StringAtOffset gets a portion of the text exposed through an Text according
// to a given offset and a specific granularity, along with the start and end
// offsets defining the boundaries of such a portion of text.
//
// If granularity is ATSPI_TEXT_GRANULARITY_CHAR the character at the offset is
// returned.
//
// If granularity is ATSPI_TEXT_GRANULARITY_WORD the returned string is from the
// word start at or before the offset to the word start after the offset.
//
// The returned string will contain the word at the offset if the offset is
// inside a word and will contain the word before the offset if the offset is
// not inside a word.
//
// If granularity is ATSPI_TEXT_GRANULARITY_SENTENCE the returned string is from
// the sentence start at or before the offset to the sentence start after the
// offset.
//
// The returned string will contain the sentence at the offset if the offset
// is inside a sentence and will contain the sentence before the offset if the
// offset is not inside a sentence.
//
// If granularity is ATSPI_TEXT_GRANULARITY_LINE the returned string is from the
// line start at or before the offset to the line start after the offset.
//
// If granularity is ATSPI_TEXT_GRANULARITY_PARAGRAPH the returned string is
// from the start of the paragraph at or before the offset to the start of the
// following paragraph after the offset.
//
// The function takes the following parameters:
//
//   - offset: position.
//   - granularity: TextGranularity.
//
// The function returns the following values:
//
//   - textRange: newly allocated string containing the text at the offset
//     bounded by the specified granularity. Use g_free() to free the returned
//     string. Returns NULL if the offset is invalid or no implementation is
//     available.
func (obj *Text) StringAtOffset(offset int, granularity TextGranularity) (*TextRange, error) {
	var _arg0 *C.AtspiText           // out
	var _arg1 C.gint                 // out
	var _arg2 C.AtspiTextGranularity // out
	var _cret *C.AtspiTextRange      // in
	var _cerr *C.GError              // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(offset)
	_arg2 = C.AtspiTextGranularity(granularity)

	_cret = C.atspi_text_get_string_at_offset(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(offset)
	runtime.KeepAlive(granularity)

	var _textRange *TextRange // out
	var _goerr error          // out

	_textRange = (*TextRange)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_textRange)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _textRange, _goerr
}

// Text gets a range of text from an Text object. The number of bytes in the
// returned string may exceed either end_offset or start_offset, since UTF-8 is
// a variable-width encoding.
//
// The function takes the following parameters:
//
//   - startOffset indicating the start of the desired text range.
//   - endOffset indicating the first character past the desired range.
//
// The function returns the following values:
//
//   - utf8: text string containing characters from start_offset to
//     end_offset-1, inclusive, encoded as UTF-8.
func (obj *Text) Text(startOffset, endOffset int) (string, error) {
	var _arg0 *C.AtspiText // out
	var _arg1 C.gint       // out
	var _arg2 C.gint       // out
	var _cret *C.gchar     // in
	var _cerr *C.GError    // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(startOffset)
	_arg2 = C.gint(endOffset)

	_cret = C.atspi_text_get_text(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(startOffset)
	runtime.KeepAlive(endOffset)

	var _utf8 string // out
	var _goerr error // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _utf8, _goerr
}

// TextAfterOffset gets delimited text from an Text object which follows a given
// text offset.
//
// The function takes the following parameters:
//
//   - offset indicating the offset from which the delimiter search is based.
//   - typ indicating whether the desired text string is a word, sentence, line,
//     or attribute run.
//
// The function returns the following values:
//
//   - textRange containing a UTF-8 string representing the delimited text,
//     both of whose delimiting boundaries are after or inclusive of the current
//     offset, or an empty string if no such text exists.
func (obj *Text) TextAfterOffset(offset int, typ TextBoundaryType) (*TextRange, error) {
	var _arg0 *C.AtspiText            // out
	var _arg1 C.gint                  // out
	var _arg2 C.AtspiTextBoundaryType // out
	var _cret *C.AtspiTextRange       // in
	var _cerr *C.GError               // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(offset)
	_arg2 = C.AtspiTextBoundaryType(typ)

	_cret = C.atspi_text_get_text_after_offset(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(offset)
	runtime.KeepAlive(typ)

	var _textRange *TextRange // out
	var _goerr error          // out

	_textRange = (*TextRange)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_textRange)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _textRange, _goerr
}

// TextAtOffset gets delimited text from an Text object which includes a given
// text offset.
//
// Deprecated: Use atspi_text_get_string_at_offset.
//
// The function takes the following parameters:
//
//   - offset indicating the offset from which the delimiter search is based.
//   - typ indicating whether the desired text string is a word, sentence, line,
//     or attribute run.
//
// The function returns the following values:
//
//   - textRange containing a UTF-8 string representing the delimited text,
//     whose delimiting boundaries bracket the current offset, or an empty
//     string if no such text exists.
func (obj *Text) TextAtOffset(offset int, typ TextBoundaryType) (*TextRange, error) {
	var _arg0 *C.AtspiText            // out
	var _arg1 C.gint                  // out
	var _arg2 C.AtspiTextBoundaryType // out
	var _cret *C.AtspiTextRange       // in
	var _cerr *C.GError               // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(offset)
	_arg2 = C.AtspiTextBoundaryType(typ)

	_cret = C.atspi_text_get_text_at_offset(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(offset)
	runtime.KeepAlive(typ)

	var _textRange *TextRange // out
	var _goerr error          // out

	_textRange = (*TextRange)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_textRange)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _textRange, _goerr
}

// TextBeforeOffset gets delimited text from an Text object which precedes a
// given text offset.
//
// The function takes the following parameters:
//
//   - offset indicating the offset from which the delimiter search is based.
//   - typ indicating whether the desired text string is a word, sentence, line,
//     or attribute run.
//
// The function returns the following values:
//
//   - textRange containing a UTF-8 string representing the delimited text,
//     both of whose delimiting boundaries are before the current offset,
//     or an empty string if no such text exists.
func (obj *Text) TextBeforeOffset(offset int, typ TextBoundaryType) (*TextRange, error) {
	var _arg0 *C.AtspiText            // out
	var _arg1 C.gint                  // out
	var _arg2 C.AtspiTextBoundaryType // out
	var _cret *C.AtspiTextRange       // in
	var _cerr *C.GError               // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(offset)
	_arg2 = C.AtspiTextBoundaryType(typ)

	_cret = C.atspi_text_get_text_before_offset(_arg0, _arg1, _arg2, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(offset)
	runtime.KeepAlive(typ)

	var _textRange *TextRange // out
	var _goerr error          // out

	_textRange = (*TextRange)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_textRange)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _textRange, _goerr
}

// RemoveSelection de-selects a text selection.
//
// The function takes the following parameters:
//
//   - selectionNum indicating which text selection to remove.
func (obj *Text) RemoveSelection(selectionNum int) error {
	var _arg0 *C.AtspiText // out
	var _arg1 C.gint       // out
	var _cerr *C.GError    // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(selectionNum)

	C.atspi_text_remove_selection(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(selectionNum)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// ScrollSubstringTo scrolls whatever container of the Text text range so it
// becomes visible on the screen.
//
// The function takes the following parameters:
//
//   - startOffset indicating the start of the desired text range.
//   - endOffset indicating the first character past the desired range.
//   - typ indicating where the object should be placed on the screen.
func (obj *Text) ScrollSubstringTo(startOffset, endOffset int, typ ScrollType) error {
	var _arg0 *C.AtspiText      // out
	var _arg1 C.gint            // out
	var _arg2 C.gint            // out
	var _arg3 C.AtspiScrollType // out
	var _cerr *C.GError         // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(startOffset)
	_arg2 = C.gint(endOffset)
	_arg3 = C.AtspiScrollType(typ)

	C.atspi_text_scroll_substring_to(_arg0, _arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(startOffset)
	runtime.KeepAlive(endOffset)
	runtime.KeepAlive(typ)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// ScrollSubstringToPoint scrolls whatever container of the Text text range so
// it becomes visible on the screen at a given position.
//
// The function takes the following parameters:
//
//   - startOffset indicating the start of the desired text range.
//   - endOffset indicating the first character past the desired range.
//   - coords indicating whether the coordinates are relative to the screen,
//     to the window, or to the parent object.
//   - x coordinate of the point to reach.
//   - y coordinate of the point to reach.
func (obj *Text) ScrollSubstringToPoint(startOffset, endOffset int, coords CoordType, x, y int) error {
	var _arg0 *C.AtspiText     // out
	var _arg1 C.gint           // out
	var _arg2 C.gint           // out
	var _arg3 C.AtspiCoordType // out
	var _arg4 C.gint           // out
	var _arg5 C.gint           // out
	var _cerr *C.GError        // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(startOffset)
	_arg2 = C.gint(endOffset)
	_arg3 = C.AtspiCoordType(coords)
	_arg4 = C.gint(x)
	_arg5 = C.gint(y)

	C.atspi_text_scroll_substring_to_point(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(startOffset)
	runtime.KeepAlive(endOffset)
	runtime.KeepAlive(coords)
	runtime.KeepAlive(x)
	runtime.KeepAlive(y)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// SetCaretOffset moves the text caret to a given position.
//
// The function takes the following parameters:
//
//   - newOffset: offset to which the text caret is to be moved.
func (obj *Text) SetCaretOffset(newOffset int) error {
	var _arg0 *C.AtspiText // out
	var _arg1 C.gint       // out
	var _cerr *C.GError    // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(newOffset)

	C.atspi_text_set_caret_offset(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(newOffset)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// SetSelection changes the bounds of an existing Text text selection.
//
// The function takes the following parameters:
//
//   - selectionNum: zero-offset index indicating which text selection to
//     modify.
//   - startOffset indicating the new starting offset for the selection.
//   - endOffset indicating the desired new offset of the first character after
//     the selection.
func (obj *Text) SetSelection(selectionNum, startOffset, endOffset int) error {
	var _arg0 *C.AtspiText // out
	var _arg1 C.gint       // out
	var _arg2 C.gint       // out
	var _arg3 C.gint       // out
	var _cerr *C.GError    // in

	_arg0 = (*C.AtspiText)(unsafe.Pointer(coreglib.InternObject(obj).Native()))
	_arg1 = C.gint(selectionNum)
	_arg2 = C.gint(startOffset)
	_arg3 = C.gint(endOffset)

	C.atspi_text_set_selection(_arg0, _arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(obj)
	runtime.KeepAlive(selectionNum)
	runtime.KeepAlive(startOffset)
	runtime.KeepAlive(endOffset)

	var _goerr error // out

	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _goerr
}

// Range: instance of this type is always passed by reference.
type Range struct {
	*_range
}

// _range is the struct that's finalized.
type _range struct {
	native *C.AtspiRange
}

func marshalRange(p uintptr) (interface{}, error) {
	b := coreglib.ValueFromNative(unsafe.Pointer(p)).Boxed()
	return &Range{&_range{(*C.AtspiRange)(b)}}, nil
}

// NewRange creates a new Range instance from the given
// fields. Beware that this function allocates on the Go heap; be careful
// when using it!
func NewRange(startOffset, endOffset int) Range {
	var f0 C.gint // out
	f0 = C.gint(startOffset)
	var f1 C.gint // out
	f1 = C.gint(endOffset)

	v := C.AtspiRange{
		start_offset: f0,
		end_offset:   f1,
	}

	return *(*Range)(gextras.NewStructNative(unsafe.Pointer(&v)))
}

func (r *Range) StartOffset() int {
	valptr := &r.native.start_offset
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (r *Range) EndOffset() int {
	valptr := &r.native.end_offset
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (r *Range) SetStartOffset(startOffset int) {
	valptr := &r.native.start_offset
	*valptr = C.gint(startOffset)
}

func (r *Range) SetEndOffset(endOffset int) {
	valptr := &r.native.end_offset
	*valptr = C.gint(endOffset)
}

// Copy gets a copy of an Range object.
//
// The function returns the following values:
//
//   - _range copy of an Range object.
func (src *Range) Copy() *Range {
	var _arg0 *C.AtspiRange // out
	var _cret *C.AtspiRange // in

	_arg0 = (*C.AtspiRange)(gextras.StructNative(unsafe.Pointer(src)))

	_cret = C.atspi_range_copy(_arg0)
	runtime.KeepAlive(src)

	var __range *Range // out

	__range = (*Range)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(__range)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.free(intern.C)
		},
	)

	return __range
}

// TextRange: instance of this type is always passed by reference.
type TextRange struct {
	*textRange
}

// textRange is the struct that's finalized.
type textRange struct {
	native *C.AtspiTextRange
}

func marshalTextRange(p uintptr) (interface{}, error) {
	b := coreglib.ValueFromNative(unsafe.Pointer(p)).Boxed()
	return &TextRange{&textRange{(*C.AtspiTextRange)(b)}}, nil
}

func (t *TextRange) StartOffset() int {
	valptr := &t.native.start_offset
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (t *TextRange) EndOffset() int {
	valptr := &t.native.end_offset
	var _v int // out
	_v = int(*valptr)
	return _v
}

func (t *TextRange) Content() string {
	valptr := &t.native.content
	var _v string // out
	_v = C.GoString((*C.gchar)(unsafe.Pointer(*valptr)))
	return _v
}

func (t *TextRange) SetStartOffset(startOffset int) {
	valptr := &t.native.start_offset
	*valptr = C.gint(startOffset)
}

func (t *TextRange) SetEndOffset(endOffset int) {
	valptr := &t.native.end_offset
	*valptr = C.gint(endOffset)
}
